### ISSUE TITLE
Tokenizer at the character / unicode byte level ?

### ISSUE THREAD

**Issue by PonteIneptique** [huggingface/tokenizers#1003]
HI there :)
I am planning to use the Tokenizer and Model from this library but I would like to keep some ability to compare easily between a char level tokenizer ("abc"-> "a", "b", "c") and subword level tokenizers (BPE, WordPiece, etc.).
What would be the least hacky way to do that (in python) while not moving away from the classes of this library ?

Thanks in advance ;)

**Comment by Narsil** [comment]
Hi @PonteIneptique,

AFAIK there's no purely `char` (understood as Rust `char` class) level tokenization, since all `tokenizers` in this library use either `WordLevel`, `BPE` or `Unigram` models to produce tokens.

There exists `pre_tokenizers.ByteLevel` which does cast all bytes to single `char` enabling doing byte level ops should you need it.

But there is nothing like `ByT5` or pure bytes (or chars) levels ops.
You can actually craft them quite easily if you want by simply using `BPE` with a char level vocab and no merges for instance, but it's definitely a bit remote from the intents of this library.

Does this answer your question ?

**Comment by Narsil** [comment]
FYI training `examples/train_bytelevel_bpe.py` with `vocab_size=256` should yield a pure byte level (with no merges) tokenizers.


For `unicode` you would need to know in advances how many different unicode characters are within your dataset first.

**Comment by Narsil** [comment]
@PonteIneptique there's been small demand for things like ByT5 Fast version of the model.

Since bytes are very low level I am unsure adding an Empty model for that is necessary, but maybe. It's been asked for `offset_mappings` at least which slow tokenizers don't provide so that might be interesting.

**Comment by david-waterworth** [comment]
@PonteIneptique the way I did this was to train a BPE model using `train_from_iterator` passing in the character set - see https://github.com/huggingface/tokenizers/issues/828

**Comment by PonteIneptique** [comment]
@Narsil and @david-waterworth Thank you both for your feedback.

I must say I'd definitely enjoy having some more tools (or maybe I missed them) which could be used in the same fashion as the Tokenizer class for subwords. On the top of my head (feel free to direct me, I am still going through the documentation):

- Word level tokenizer. In some low-resource language like Latin or Greek, this has proven to be an efficient tool as the vocabulary is small for training set. This is what is done by Pie for example ( https://github.com/emanjavacas/pie )
- Char/Byte level tokenizer. Definitely used in some lemmatization system with high spelling variation (Medieval Latin and Old French come to mind but I have seen such argument made for Hungarian in a paper (could try to find it again)). It's definitely used also in HTR/OCR systems when dealing with abreviations (NFD or NFKD being quite useful).
- (This one I am pretty sure you already have, but I am still trying to find where) "Categorical" Label Encoders. If I have to deal with POS, Morphological features, etc. I'd like to stay within the Huggingface~tokenizers ecosystem. 

I hope it's useful feedback, and please, please, tell me if I am missing something already existing :)
