### ISSUE TITLE
Uppercase smart tokenization

### ISSUE THREAD

**Issue by JonathanAlis** [huggingface/tokenizers#1022]
I wanted to tokenize a large corpus from scratch.
In the context, the word casing is important, and can provide valuable imformation about the text.
It sometimes indicate a given context, differentiate proper names, organizations, titles, acronims, etc.

At the same time, it is not desirable to have 2 versions of the tokens (one uppercase, other lowercase, and maybe others first letter as uppercase). It would be better to have a small vocabulary as possible, and also to refer to the same tokens, as words in uppercase and lowercase has the same meaning.

My idea was to include a prefix (a special token, lets say [upper]) in uppercase words , and then transform to lowercase. Then, the word would be tokenized in subwords and the special character is part of the word. 
For example, the string:

> 'subword SUBWORD'
 
should be normalized as 

> 'subword [upper]subword'

, and tokenized as 

> ['sub', '##word', '[upper]', 'sub', '##word']

or

> ['_sub', 'word', '[upper]', '_sub', 'word'].

First:
Is this a good ideia? Could it improve the language models for contexts where uppercase matters? 

Second:
There is a way to do it with current implementations of Normalizers and/or pre-tokenizer?
The function Normalizers.Replace receives a regex and a str to replace, I can imagine that we could replace the '' (empty string) before a uppercase  word for '[upper]' (despite I dont know which regex to use).

However, how to proceed the tokenization? it is possible to include specific rules for when fiding the token for [upper]? 
For example, the sentencePiece like tokenizers starts words after whitespace with '_' , but in an normalized uppercase word, the first token is [upper], it would normally do as ['_[upper]', 'sub', 'word'], not exactly what I meant. So, we need different rules.

It is a pre-tokenizer problem or a post-processor with special characters?

I am struggling at finding solutions.
Thanks in advance

**Comment by Narsil** [comment]
>  Is this a good ideia? Could it improve the language models for contexts where uppercase matters?

I am not an expert on the subject. https://discuss.huggingface.co if you want to reach out more experiences users.
My take, is that in general no this doesn't seem like a good idea.
If you can do lowercase, do lowercase, otherwise, just use two tokens. First of all you don't need two tokens for each word, since the tokenization will find the appropriate amount of subtokens to use and can end up with a strategy like yours (and most likely a more efficient one).

I could very well be wrong, but Unigram and BPE are hard to beat ! (that's why everyone uses them).

> However, how to proceed the tokenization? it is possible to include specific rules for when fiding the token for [upper]?
> For example, the sentencePiece like tokenizers starts words after whitespace with '' , but in an normalized uppercase word, the first token is [upper], it would normally do as ['[upper]', 'sub', 'word'], not exactly what I meant. So, we need different rules.
> 
> It is a pre-tokenizer problem or a post-processor with special characters?

this is a more involved topic, all I can invite you to do is try and share it on discuss, or read the docs extensively do understand how each bits work.

I am closing this since it doesn't seem to be an issue. Feel free to reopen.
