### ISSUE TITLE
WordPiece model crashes with `unk_token=None`

### ISSUE THREAD

**Issue by stephantul** [huggingface/tokenizers#1037]
`BPE` and `Word` tokenizer models can be initialized using `unk_token=None`, which is useful when using byte-level LMs, since these will never show an UNK. If you don't pass an argument, `unk_token` is set to None.

`Wordpiece`, however, can't take `unk_token=None`, and has `[UNK]` as its default. The [docs](https://huggingface.co/docs/tokenizers/api/models#tokenizers.models.WordPiece) also mention the parameter being Optional, which I take to mean that it can be `None`.

**Comment by Narsil** [comment]
`optional` means you are not required to pass it as a value (because it has a default), it doesn't mean that the type `None` is valid.

As a matter of fact, Rust, which is statically type, requires a String (https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/models/wordpiece/mod.rs#L126)

We could silently ignore `None` and use `[UNK]` instead but IMO it would be violating your wish. You as a developer just sent us `None` so we try to best handle it (in this case by crashing as early as possible.)

Does that make sense?

**Comment by stephantul** [comment]
Ah ok, that makes sense. In python typing Optional means you can pass None, which is where my confusion came from.
