### ISSUE TITLE
Understanding min_frequency argument in the tokenizer.train()

### ISSUE THREAD

**Issue by KrishnanJothi** [huggingface/tokenizers#1041]
Hi,

I am training a ByteLevelBPETokenizer() on a indomain dataset, but I am unable to understand the purpose of min_frequency argument in the tokenizer.train(). 

I thought that it should be the minimum frequency of a token, in order to add it to the tokenizer vocabulary. And I used min_frequency values like 25 and 15.
for eg., 
During training if 'recommend' and 'ation' are two tokens, then the word 'recommendation' must be present min_frequency times in order to add it to the vocab.

But after training the tokenizer, I tokenized the training text with the trained tokenizer, and I can see many tokens whose frequency are less than the min_frequency and even sometimes zero. 

Please let me know what min_frequency argument is exactly doing.

**Comment by Narsil** [comment]
Hi @KrishnanJothi ,

BPE works by fusing characters iteratively until a token is created.

Meaning that if you have "bababa" as your training set, and want a vocab_size of 1 with `min_frequency=` you're going to get tokens `["a", "b", "ba"]`  and nothing else, even though once tokenized it's only going to output `["ba", "ba", "ba']`.

The reason is that BPE is progressive, to it would be able to tokenize a string contaning "abbbaabb" even though it hasn't seen that in trainig.  (that's why token `a` and token `b` are there.).

Does that answer your question ?

**Comment by KrishnanJothi** [comment]
> Hi @KrishnanJothi ,
> 
> BPE works by fusing characters iteratively until a token is created.
> 
> Meaning that if you have "bababa" as your training set, and want a vocab_size of 1 with `min_frequency=` you're going to get tokens `["a", "b", "ba"]` and nothing else, even though once tokenized it's only going to output `["ba", "ba", "ba']`.
> 
> The reason is that BPE is progressive, to it would be able to tokenize a string contaning "abbbaabb" even though it hasn't seen that in trainig. (that's why token `a` and token `b` are there.).
> 
> Does that answer your question ?

Thanks Narsil, got it. But is it a typo? Because the vocab_size is 3 and min_frequency is also 3 in your example?

**Comment by Narsil** [comment]
Yes sorry `3` and `3`. (The only thing is that it sholdn't produce `"baba"`nor `"bababa"` in my example (frequency=2)

**Comment by KrishnanJothi** [comment]
> Yes sorry `3` and `3`. (The only thing is that it sholdn't produce `"baba"`nor `"bababa"` in my example (frequency=2)

Okay thank you @Narsil , I am closing the issue.
