### ISSUE TITLE
Replace doesn't match all characters in [[:punct:]]

### ISSUE THREAD

**Issue by david-waterworth** [huggingface/tokenizers#1057]
The following code:

```
import tokenizers
import string

tokenizers.normalizers.Replace(tokenizers.Regex(r"[[:punct:]]"), "▁").normalize_str(string.punctuation)
```

returns

> '▁▁▁$▁▁▁▁▁▁+▁▁▁▁▁▁<=>▁▁▁▁▁^▁`▁|▁~

So it's not matching [$+<=>^\`~]

Yet these are all included in the rust [[:punct:]] class

```
use regex::Regex;
fn main() {
    let re = Regex::new(r"[[:punct:]]").unwrap();
    let haystack = "$+<>=^`|~";
    for m in re.find_iter(haystack) {
        println!("{:?}", m.as_str());
    }
}
```

> "$"
> "+"
> "<"
> ">"
> "="
> "^"
> "`"
> "|"
> "~"

Yet if I create another regex of just these characters it works

```
tokenizers.normalizers.Replace(tokenizers.Regex(r"[$+<=>^\`~\|]"), "▁").normalize_str("▁▁▁$▁▁▁▁▁▁+▁▁▁▁▁▁<=>▁▁▁▁▁^▁`▁|▁~")
```

**Comment by Narsil** [comment]
The regex engine is actually onigruma, not rust's one unfortunately (means it's harder to port to WASM among other things).

https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/utils/onig.rs

Here is the doc I could find on Onigruma: https://github.com/kkos/oniguruma/blob/master/doc/RE
And the equivalent for rust: https://docs.rs/regex/latest/regex/#ascii-character-classes

I am guessing all the missing symbols in onigruma is because they are classified as symbols and not punctuation.
I am unsure who's right in that situation, Rust is following o [UTS#18](https://unicode.org/reports/tr18/), Oniguruma I am not sure.

I found in the UTF#18 document `POSIX adds symbols. Not recommended generally, due to the confusion of having punct include non-punctuation marks. `. So maybe the normalization is not so clear ?

I must admit I never dived too deep in those things, personally I kind of expect different regex engines to behave differently on corner cases, but if there's one accepted standard that would be awesome to know. (Changing anything in that regard will be quite the undertaking though if we don't want to break backward compatibility)

**Comment by david-waterworth** [comment]
Ahh right, I was confused by the fact that my fork of tokenizers includes both `regex` and `onig` dependencies and I didn't recognise `onig` as a regex library. 

I agree the distinction between symbols and punctuation isn't at all clear, in particular why onigruma would leave out just those symbols. This definition implies punctuation should be all graphical characters that aren't letters or numbers which is how the `regex` rust crate and others like regex101 seem to behave

https://en.wikibooks.org/wiki/Regular_Expressions/POSIX_Basic_Regular_Expressions

I've asked the question on the onigruma repo as I cannot find what definition they've used. Being the same as regex101 would be nice - it's a good tool for developing expressions and if you're building a tokenizer in python it's tricky if you cannot easily test the expression (because it doesn't behave the same as the python engine or the online ones).

**Comment by david-waterworth** [comment]
So `Oniguruma` is using the `Standard` rather than the `POSIX Compatible` definition of :punc: from [UTF#18 Annex C](https://unicode.org/reports/tr18/#Compatibility_Properties) 

Specifically, they used the Unicode classes defined in [UnicodeData.txt](https://www.unicode.org/Public/14.0.0/ucd/UnicodeData.txt)

Which is correct I have no idea, I guess either in different situations. I don't think it warrants any changes, in particular, the `\p{P}` and `\p{S}` classes should probably be used in place of `[[:punct:]]` since there's no equivalent for symbol as far as I understand.

**Comment by david-waterworth** [comment]
Also after I raised this they (Oniguruma) changed the definition of `[:punct:]` to be `\p{P} + \p{S}` rather than `\p{P}`

**Comment by Narsil** [comment]
> Also after I raised this they (Oniguruma) changed the definition of [:punct:] to be \p{P} + \p{S} rather than \p{P}

Seems like a breaking change to me, thanks for reporting upstream !
We will probably have to take a look at this for `wasm` support (which uses yet another crate for regexp, but it's unstable so we can modify at will): https://github.com/huggingface/tokenizers/issues/935

Linking here so we don't forget about this case.
