### ISSUE TITLE
BERT-based Tokenizer will Skip Some Unicode Tokens without warning 

### ISSUE THREAD

**Issue by lolipopshock** [huggingface/tokenizers#1077]
TLDR: BERT-based tokenizer will silently produce an empty string for some Unicode Tokens. This affects 141318 out of 1114112 all unicode tokens. 

More details can be found in  https://github.com/allenai/vila/blob/225148ff7739be3ed832eacf5f4e6d32f3e2edcd/examples/find-empty-unicode-chars/unicode-char-search.ipynb

And a list of `ord` for these affected unicode tokens are stored in https://github.com/allenai/vila/blob/225148ff7739be3ed832eacf5f4e6d32f3e2edcd/examples/find-empty-unicode-chars/zero-length-unicode-ord.txt

**Comment by Narsil** [comment]
Hi @lolipopshock ,

What is the isssue ? Tokenizers in general do some sanitation/normalization, and flat out ignoring some characters is among the perfectly valid behaviors.

What do you expect would happen ?

**Comment by Narsil** [comment]
Yes.

You cannot expect a tokenizer to produce a known in advance number of ids. 
You can use `offsets` in order to figure where the id is coming from in the original string.

Matching two different tokenization is a tricky job in the general case. `offsets` make it possible at least (otherwise it's plain impossible). But many edge cases have to be handled.

Pre tokenized inputs like token classification or sequence labelling is really not super general, meaning in most cases you just have to use whatever tokenization was already there.

**Comment by creat89** [comment]
I guess the biggest problem comes when we use the option `is_split_into_words=True`. Maybe it could be interesting to have an option where these tokens are converted automatically into unknown tokens. Because, they might still provide some kind of information to a model.

**Comment by Narsil** [comment]
> e use the option `is_split_into_words=True`

You almost certainly do not want to use that option when aligning two different tokenizations. At least not when using it in the models it was trained against.

Let's say you have a sentence:

`abcdef`

That was pretokenized `abc` + `def` by some tokenizer, and the other one wants to do `abcd` + `ef`.

If you use `is_split_into_words` you will maybe have a final tokenization for the second one like `ab` + `c` +  `d` + `e` + `f`.
You entirely prevented it from using the tokens it's supposed to see, sending the model into out of domain (most likely).

As I said, using `offsets` is your best best for using two different tokenization (but it is tricky).

And sending `unknown` tokens changes the meaning of the tokenization, it's also not really possible.

**Comment by creat89** [comment]
The reasons of why or why not to use `is_split_into_words=True` is debatable and that's not the point of question here.
Regarding the possibility of returning `unknown` with  `is_split_into_words=True`, I don't understand why it is not possible. For instance, I have the following output of a tokenizer for the `words_ids` field:
`[None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 11, 12, 13, 13, 14, 15, 16, 17, 17, 17, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, None, None ]`
I clearly see that word 18 was skipped, because it was a UTF-8 character that was removed by the tokenizer. However, the output tells me as well that the tokenizer is well aware of the skipped "word".  Why couldn't we have it replaced by an `unknown`?

Yes, there is an option of using offsets to realign my tokenized input with the tokenized version of HuggingFace, but that only complicates the things before and after using the model, specially in token classification tasks.
- For training, if the omitted token was a boundary of the labeled example, then we're passing a wrong input. For instance: If I had `B-ORG`, `I-ORG` and the first token is skipped, then I'm using as input `I-ORG`. And that means that I need to check and modify the labels in my training data just because a token was skipped.
  - I could insert the skipped tokens manually, but if I use stride, processing the tokenized output becomes a hell.
- For predicting, I need to check the context on which the skipped token is surrounded. If it is between a labeled example, I need to add labels.

**Comment by Narsil** [comment]
>  Why couldn't we have it replaced by an unknown? 

Because the original tokenizer skips it, doesn't expect a token there, modifying this changes the underlying input for the model putting it potentially out of domain, almost certainly not in the conditions it was supposed to be in.

It's really possible, but this requires changing the tokenizer. It would be a different one.

> For training, if the omitted token was a boundary of the labeled example, then we're passing a wrong input. For instance: If I had B-ORG, I-ORG and the first token is skipped, then I'm using as input I-ORG. And that means that I need to check and modify the labels in my training data just because a token was skipped. 

Use `offsets`. Discard `B-org` `I-org` as a first approach (it's a byproduct of tokenization, not a core component of the task).

`This org is led by Some One` With `org` starting at offset 5 finishing at offset 8, and `pers` starting at offset 19 and finishing at 27.

I purposefully removed any tokenization here, there's only a string, and two spans.

## Let's say you check tokenization 1:

`org` is a single token, perfectly aligned with the first span ->  Annotate it as `B-org`
`Some`+`One` (notice the missing internal space). Then also perfect, it's aligned with the original span. Annotate them `B-pers`  and `I-pers`. Notice than the internal space was skipped by the tokenizer, it's not a specific token and yet we're still able to annotate the tokens correctly.

As long as all starts and stop matches, there is no issue.
They only start when they do not. And all cases are possible.


## Now tokenization 2:

`org` is a single token, perfect everything is the same.
but for some reason

`by Some One` is a single token. Then I don't really know what's the correct solution for this, but you can say it's `B-pers` during training, which will lead to incorrect final solution but not so horrible usability wise.

What if it was `by So` + `me One` ? Same issue, I'm not really sure `me One` is probably `B-pers` or `I-pers` but the first one ? 

What it it was `by S`  +  `One` (missing `ome`, it's pretty bad tokenization but it's for the example, and it can happen when targeting chinese with an english tokenizer) ? 

All these are edge cases for sure, but you cannot tell the tokenizer what it should be doing, because that will affect the end result of the model it was trained with. 

And again, if you don't like tokenization 2, just create another one tokenization 3, but don't expect it to work with model 2.

**Comment by creat89** [comment]
Sorry to disagree with your reply @Narsil. I understand the usefulness of the offsets, they are useful when we use a raw text as input. Like, when we use HuggingFace Hosted inference API. 

However, there are occasions on which we cannot make use of them because we have an already tokenized input, and I think that's why it exists the flag `is_split_into_words=True`. Why is the input already tokenized it does not matter in this case and sometimes is out of our hands. And that is why, it would be nice to be able to convert the skip tokens into `unknown`.

Normally when we have an already tokenized input, we cannot provide a new tokenization, even if the original tokenized input is "wrong" according to the tokenizer model, e.g. `ArcelorMittal` -/-> `Arcelor`, `Mittal`. As well, using offsets is not useful, because we might end with discordant labels in one input token `Arcelor` (B-ORG), `Mittal` (I-ORG). You might ask, how do the model should deal with these cases, that is also out of the scope of this question, but you could take the first subtoken, e.g. `Arcelor`, like some BERT models do. 

With respect to the:

> putting [the model] potentially out of domain

by using `unknown` as a replacement. I do believe that it is a risk that exists in any ML model, and the developers and users of them should take them in consideration and assess them. There are always going to be cases in which the tokenizer do not know how to split a word, and there will be, in consequence, `unknown`s. And that's why they do exist. 

Moreover, it's to the developer/user of the model to determine if replacing or not skip tokens by an `unknown` is a good option or not. In the same way that we have the option to give the tokenizer a list of words, it would be nice to have the option to generate an output from the tokenizer that do not skip tokens, no matter what.

Finally, it might be good to have a note that certain tokenizers could skip certain tokens, thus the `words_ids` might not be continuous.

**Comment by Narsil** [comment]
>  we have an already tokenized input
> is out of our hands

I know, this is exactly what I'm trying to deconstruct. We have the same issue in `evaluate` for instance, it's really tricky to use a  model on a pretokenized input, or with a different tokenizer. `is_split_into_words=True` exists because of this reason, but it usually creates more issues than it solves. It's just because I see too many issues arise after using this that I push back against it. It does exist, we're going to continue supporting it, but it's causing a lot of issues and unnecessary headaches for users that do use it.

**I'm really trying to prevent further issues down the road.**

What you are really asking for is using an entirely other tokenizer, one that does align with the boundaries you have in mind and that outputs unknown tokens where you want. 

> Moreover, it's to the developer/user of the model to determine if replacing or not skip tokens by an unknown is a good option or not. 

You are entirely right if you were creating a new tokenizer, which you can very well do.
But when you are using an existing tokenizer, well not really. The original creators of a model created the tokenizer a certain way, to react on strings in a particular fashion, and you cannot really change that. Well, you actually can, but you're not using the same thing as them.

You can take it apart if you want, override the `normalizer`, `pre_tokenizer` if you want, it will start outputting those unk tokens you want, but it won't be the same tokenizer anymore.

> Finally, it might be good to have a note that certain tokenizers could skip certain tokens, thus the `words_ids` might not be continuous.

You are more than welcome to update the docs. They do need some love.
I don't think there are not any guarantees about the output of tokenizers other than it will get you the `input_ids` you need.

Even `words` don't mean what you imagine they do. In `tokenizers` a word is whatever was pre-cut by the `pre_tokenizer`. It the forced cutting bias put in place by the model/tokenizer creator. Nothing more. It's usually whitespace splitting which usually what everyone thinks about in the first place, but it could include digits or not, it could split or puncutation or not etc.. 

```python
from tokenizers import Tokenizer
tokenizer = Tokenizer.from_pretrained("bert-base-uncased")

tokenizer.encode("私は学生です").word_ids
# [None, 0, 1, 2, 3, 4, 4, None]


tokenizer = Tokenizer.from_pretrained("gpt2")
tokenizer.encode("私は学生です").word_ids
# [0, 0, 0, 0, 0, 0, 0, 0, 0]
```

There's no guarantee about them being complete, or contiguous, or the same with 2 different tokenizers.
They are in increasing order is I think the only guarantee we can have.
