### ISSUE TITLE
BERT regex replace normalizers 

### ISSUE THREAD

**Issue by galtay-tempus** [huggingface/tokenizers#1084]
hello tokenizers! 

I was watching this video on building HF tokenizers (https://www.youtube.com/watch?v=MR8tZm5ViWU)
am trying to understand the bert normalizers

```
tokenizer.normalizer = normalizers.Sequence([
    normalizers.Replace(Regex(r"[\p{Other}$$[^\n\t\r]]"), ""), 
    normalizers.Replace(Regex(r"[\s]"), " "),
    ...
])
```

In addition, I see this paragraph in HF course (https://huggingface.co/course/chapter6/8?fw=pt) 
```
To go further If you test the two versions of the previous normalizers on a string
containing the unicode character u"\u0085" you will surely notice that these two
normalizers are not exactly equivalent. To not over-complicate the version with 
normalizers.Sequence too much , we haven’t included the Regex replacements 
that the BertNormalizer requires when the clean_text argument is set to True - 
which is the default behavior. But don’t worry: it is possible to get exactly the same
normalization without using the handy BertNormalizer by adding two normalizers.Replace’s 
to the normalizers sequence.
```

I understand that `normalizers.Replace(Regex(r"[\s]"), " ")` is normalizing whitespace and `normalizers.Replace(Regex(r"[\p{Other}$$[^\n\t\r]]"), "")` is doing something with line-feed, tab, and carriage returns  ... but I can't parse the first part `\p{Other}$$` ... can anyone help me understand this?

**Comment by galtay-tempus** [comment]
this post helps https://github.com/huggingface/tokenizers/issues/1057

good to know the regex engine is onigurama

and this link to their docs is helpful https://github.com/kkos/oniguruma/blob/master/doc/RE#L112

so `\p` is a character property but I'm still unsure what `\p{Other}` specifies

**Comment by Narsil** [comment]
Here is a rust doc that includes, basically `\p{X}` is matching something that is in the class `X`.
https://docs.rs/regex/latest/regex/#matching-one-character

**Comment by ahgraber** [comment]
I found this conversation because the huggingface NLP Course mentioned above says that there are two normalizers to be added (`by adding two normalizers.Replace’s to the normalizers sequence`), but these are not specified in the site; I think it would be helpful to add these two Replace Regex's to the course.

Additionally, for others who may arrive here like I did, I believe the one ReplaceRegex uses ampersands `&&` instead of dollar signs `$$`:

`normalizers.Replace(Regex(r"[\p{Other}&&[^\n\t\r]]"), "")`
