### ISSUE TITLE
missing index entries when saving ConvBert vocab

### ISSUE THREAD

**Issue by lingdoc** [huggingface/tokenizers#1085]
I'm experimenting with different models for text classification and I find that the [ConvBert documentation](https://huggingface.co/docs/transformers/model_doc/convbert#transformers.ConvBertTokenizer) states that the tokenizer inherits from the `PreTrainedTokenizer`, which doesn't seem to be an issue with other Bert-based models. However, when I try to save a classifier using ConvBert, I get a series of the following error messages:

```The OrderedVocab you are attempting to save contains a hole for index 30517, your vocabulary could be corrupted !```

I'm thinking that there's something wrong with the way the tokenizer is creating the index, but I don't know how to figure out what needs to be fixed, and I haven't been able to find any info on this in current issues. Training proceeds normally but without being able to save a fine-tuned ConvBert model I have no way of testing whether the tokenizer is actually producing meaningful relations.

**Comment by Narsil** [comment]
Hi @lingdoc 

No the problem lies in the original convbert tokenizer.

There ARE holes in the original tokenizer, meaning some ids are unused.
In general, this is worrysome because it means you're creating a larger than necessary vocabulary.

The original convbert tokenizer DOES have the issue so it's not necessarily something we can really do something about, so the warnings are correct. You can still use the tokenizer, but you will be using more ressources than necessary in your final model.

Fixing it on your side will require manual surgery to the tokenizer's `vocab.txt` or `tokenizer.json` to remove duplicates.
Some users have done that with success, however it's beyond the scope of this library since it's not entirely clear HOW the tokenizer should be fixed in regard with your model.

Does that answer your question ?

**Comment by lingdoc** [comment]
ok, thanks @Narsil that helps a lot! i'll see what I can do on my end.
