### ISSUE TITLE
tokenizers 0.10.3 build fails

### ISSUE THREAD

**Issue by ashari4** [huggingface/tokenizers#1087]
```
 pip install tokenizers==0.10.3
```

output: many instances of "error[E0433]: failed to resolve: use of undeclared crate or module `ctor`"

system info:
windows 10
python 3.10.6
pip 22.2.1
rustc 1.64.0 (a55dd71d5 2022-09-19)

full output attached as [tokenizers_log.txt](https://github.com/huggingface/tokenizers/files/9815673/tokenizers_log.txt)

**Comment by Narsil** [comment]
Hi, I think we yanked `0.10.3` because it contained a pretty bad bug.

Can you try to upgrade to `0.10.6` (which I think it the latest in 0.10) ?

**Comment by Narsil** [comment]
Sorry I'm always confusing `0.10` and 0.11` , I was referring to  `0.11.6` which is not what you want.

Did you try using the wheels directly ? https://pypi.org/project/tokenizers/0.10.3/#files

**Comment by Narsil** [comment]
Ahhh you're using python3.10 which wasn't available at the time. Can you use Python 3.9? Otherwise you do have to rebuild and you're going to make it painful on yourself I think.

You could try rebuilding `0.10.3` from sources which would be the easiest but it's not necessarily going to be easy (again Python 3.10 wasn't available at the time)
