### ISSUE TITLE
How to prevent joined words in output of text generation?

### ISSUE THREAD

**Issue by auwsom** [huggingface/tokenizers#1091]
Hello, I am running output through some english word checking, and have covered a bunch of cases like contractions, lemmatization, punctuation, etc., but am having troubles with long strings of joined or concatenated words. I have seen some brute force ways to disentangle the words, but I thought it would be much more efficient to add spaces to the tokens. I'm not sure how doable this is. 

I saw a way to track the encoding tokens back to words, but with generation, the tokens arent necessarily complete words. The non-words could be checked though after joining to their neighbors. I guess I'm checking if there is a standard way to do this before hacking some code together.

**Comment by Narsil** [comment]
@auwsom ,

I'm sorry but I fail to understand your issue, could you share some code maybe about what you're trying to do and what's failing ?
Also what are your expectations about the output ?

**Comment by auwsom** [comment]
Sure. Thanks. I'm getting long strings of words like: thisisanexampleofalongstringofwordsanditcsntakeupthewholeoutputwithnowaytofindagoodstoppingpointitjustendsabruplbruptly.

Once a typo or "mutation" like 'eachother' gets into the chat history, the model seems to like making more of these.

I have a patch to decode the tokens separately and add white space. But it has to check for contractions and punctuation which don't automatically get a space character in front of it like: ` don` and `'t`. 

Also I'm now working on checking if the combined tokens are actually words, but this can get tedious when more than 2 tokens combine into a word.

Any suggestions for a better approach? Thank you

**Comment by Narsil** [comment]
Do you have code example to share so we can reproduce ?

> , the model seems to like making more of these.

Seems like maybe the issue is the model, and not the tokenizer then. Tokens are tokens, they (usually) don't store any information about being words are not. Some tokens are "other" and another one is " other". If the model chooses the wrong one then...

It seems to me like the model you are using is a bit sensitive to typos, and if that's really the case, then the best thing you can do is fine-tune it to make it robust to the sort of data you're seeing in the real world.

Maybe the original model had some data where each space was truncated (happens when you normalize your dataset and ignore weird characters including weird spaces which might exist in other languages for instance).

In any case, without a reproducible script it's hard to diagnose properly.

**Comment by auwsom** [comment]
Thanks again. I'm not at the computer or I could send more of the script, but I think the problem is described. I'm using the largest model that runs on my rtx3060, an optimized version of Eluether 6B. It works fine, until it gets some concatenated words into it's input. It's been trained on computer code, so perhaps it's trying to make function definitions. Retraining wouldn't fit on my hardware. I'm not sure if fine-tuning would help.

I would like to keep the code generation possible, but that's likely where it's coming from. Then again, many other models include Stack Exchange text as well.. like Bloom. And if "mutations" get into the chat history, they could propagate. So checking for them is probably best anyway. 

I'm wondering if there is a way to build an only-compete words into the tokenizer decoding. But as you may be hinting at, controlling the output of the model is nigh impossible.. (not sure if fine-tuning could overcome this).. outside of checking what goes into the tokenizer encoding.

Maybe I should be using a totally different tokenizer for the encoding. Like WhiteSpaceTokenizer or TweetTokenizer from the nltk package.
