### ISSUE TITLE
[Question] UNK token in Unigram Trainer

### ISSUE THREAD

**Issue by cakiki** [huggingface/tokenizers#1097]
Hi everyone! I was wondering why `unk_token` was an argument of the **models** for WordPiece and BPE but an argument of the **trainer** for Unigram.

- https://huggingface.co/docs/tokenizers/api/trainers#tokenizers.trainers.UnigramTrainer.unk_token
- https://huggingface.co/docs/tokenizers/api/models#tokenizers.models.BPE.unk_token
- https://huggingface.co/docs/tokenizers/api/models#tokenizers.models.WordPiece.unk_token

**Comment by Narsil** [comment]
Hi @cakiki , that's because it's a **core** part of the unigram training, which is not the case for the others, were it's just used for the model. It's also part of the UnigramModel.

The reason is that BPE is constructive. Meaning that during training, we don't need anything link unk as we're generating new tokens.

This is not the case for Unigram, where you start with total representation with a suffix array, and iteratively remove tokens until desired amount, but you always might remove a needed token for entire representation,, so unigram needs a UNK to represent skips during training (at least SPM expects one).

Does that explain it ?

**Comment by cakiki** [comment]
Makes perfect sense; thank you so much for the explanation @Narsil !
