### ISSUE TITLE
How to porting subword-nmt to tokenizers?

### ISSUE THREAD

**Issue by wannaphong** [huggingface/tokenizers#1138]
Hello! I have a bpe file that trained by [subword-nmt](https://github.com/rsennrich/subword-nmt). How to porting subword-nmt to tokenizers?

**Comment by wannaphong** [comment]
file: https://drive.google.com/uc?id=1ct9xaAUkqxbn9X8JgO8yKfBYWT1Dthld

```
from subword_nmt.apply_bpe import BPE
bpe = BPE(open("./th_18M.50000.bpe"))
```

**Comment by Narsil** [comment]
Hmm there is no official port mecanism, but what I see in your file the equivalent of a `merges.txt`  which is good but actually potentially incomplete.

You can do a best effort way to convert, by creating the equivalent of `vocab.json` but it's not sure it's going to be exactly the same without deep diving into what `subword-nmt` does.

Please don't hesitate to comment here, if you manage to produce a script that works.

**Comment by new5558** [comment]
Here is what I did to port `subword-nmt`/`fairseq`  Roberta model to Huggingface hub.
https://www.kaggle.com/code/norapatbuppodom/hoogberta-conversion

Turns out that for Fairseq's Roberta with subword-nmt you also need `dict.txt` which is very similar to `vocab.json` to initialize the model. If directly converting `merges.txt` to `vocab.json` without `dict.txt` your tokenizer will output different token_ids from the original tokenizer. 

By formatting both files to match with the input of `CharBPETokenizer(vocabs, merges)` and applying special token rules (eos, bos, pad, mask, etc.) you should have Huggingface tokenizer that matches with `subword-nmt`.
