### ISSUE TITLE
Unexpected tokens are included in BPE vocabulary.

### ISSUE THREAD

**Issue by Kaiwen-Zhu** [huggingface/tokenizers#1156]
Hello. I am using `BPETrainer` on English corpus, but I find unexpected tokens in the result vocabulary which are not in my corpus, such as Chinese characters. I don't want them because I could not control the number of valid tokens. How could I get rid of them? I tried to specify the parameter `initial_alphabet` but in vain. Or could I specify the number of merges?

**Comment by Narsil** [comment]
Do you mind sharing a reproducible script ?

Isn't it possible that there are some chinese characters in the original English corpus (it happens a lot more than one might think).

**Comment by Kaiwen-Zhu** [comment]
> Do you mind sharing a reproducible script ?
> 
> Isn't it possible that there are some chinese characters in the original English corpus (it happens a lot more than one might think).

Ah, I did find those very very strange characters in my corpus, sorry for the trouble. Could I dismiss characters with too low frequencies when collecting base characters? Or could I delete specified tokens from vocabulary? Thank you!

**Comment by Narsil** [comment]
There's no way to support that in the current trainer. 

https://github.com/google/sentencepiece does support that, through a percentage of acceptable characters.

`initial_alphabet` should be the go-to with the library (but it does force you to think about which characters are allowed or not).
The fact that it didn't work, should be a bug. 

You need an `unk` token for this to work (otherwise there's no way for the tokenizer to parse unknown tokens).
There might be odd/unobvious ways to pass this `initial_alphabet` which may have prevented this way from working in your earlier attempt.

Again a reproducible script would be nice, even on just test data.

**Comment by Kaiwen-Zhu** [comment]
> I tried to specify the parameter `initial_alphabet` but in vain.

@Narsil Well, by "in vain" I mean I expected that only characters in the parameter `initial_alphabet` would be the base characters, but after trial I found the function of this parameter is just adding specified base characters, which I guess is your expectation. So I think there are no bugs. Sorry for the trouble again and thanks for your patience!

**Comment by Narsil** [comment]
Perfect then! Closing this issue
