### ISSUE TITLE
Potentially wrong offset calculation?

### ISSUE THREAD

**Issue by tsinggggg** [huggingface/tokenizers#1201]
Hello I am not sure if this is a bug or I lack some understanding of unicodes..Would you please take a look at the simple example below?

- create training data for tokenizer in command line

```
echo "마실까해요" > temp.txt
cat temp.txt
```

- train tokenizer
```
import tokenizers
s = "마실까해요"
bpe_test = tokenizers.implementations.SentencePieceBPETokenizer(fuse_unk=True)
bpe_test.train(files='./temp.txt',
               min_frequency=1)
print(bpe_test.encode(s).offsets)
print(bpe_test.encode(s).tokens)
```

And this is the output I get 
![image](https://user-images.githubusercontent.com/20978879/228977144-f67f7e38-b24b-42d7-a80c-b272730e5bf9.png)

Shouldn't the offset of the second token be `9,11` since the length of the string is 11?

Thank you.

**Comment by Narsil** [comment]
This one is a tough one.

I think I agree with you on first approach.
I tried looking a bit more in detail with what was going on, but I couldn't figure out anything super out of the ordinary.

The error seems to be in the normalizer (which is simply NFKC).

I get this:

```
NormalizedString { original: "마실까해ᄋ", normalized: "마실까해요", alignments: [(0, 3), (0, 3), (0, 3), (6, 9), (6, 9), (6, 9), (15, 18), (15, 18), (15, 18), (21, 24), (21, 24), (21, 24), (27, 30), (27, 30), (27, 30)]
```

This means that the normalization, makes the normalized string consider only the first byte of each continuation byte bear the weight of the origin.

We should probably see something like (0, 6), (0, 6), (0, 6), (6, 15), (6, 15),....

However, this is deep within the library, and I know any modification here will be delicate.

If you try using NFD, the errors seems to be gone.

```
# Before train
bpe_test._tokenizer.normalizer = tokenizers.normalizers.NFD()
```

I don't remember all the specifics about the utf-8 normalization rules, therefore I'm unsure what's happening.


Hopefully that helps a bit.

**Comment by tsinggggg** [comment]
Thanks a lot @Narsil , modifying the normalizer helps this particular example. 

But it causes trouble for the class `tokenizers.implementations.SentencePieceBPETokenizer` to replicate `sentencepiece` behaviour in general..

**Comment by Narsil** [comment]
I understand.

Having looked at this again, I now remember.

NF(K)C work by *removing* the accented characters, leaving  the offsets only on the first char of the sequence.
That's why the offsets are as they are.

Changing that would be really a nice fit, especially for utf-8 heavy langages like korean.

However I must say off the bat:

- I don't have time to do such a change
- I would gladly spend some time providing guidance for anyone willing to take it on
- It's likely to be a core change, requiring a lot of checks everywhere, here and in `transformers` which is the biggest consumer of this lib.
- In general, I **think** this is a good change if we can make it. But I must say we might uncover things looking into it, which might explain that what was done before was done for good reasons and deliberate choice.
