### ISSUE TITLE
Feature request: tokenizer training benchmarks

### ISSUE THREAD

**Issue by sradc** [huggingface/tokenizers#1206]
Related forum post, [How long to expect training to take, and guidance on subset size?](https://discuss.huggingface.co/t/how-long-to-expect-training-to-take-and-guidance-on-subset-size/35380)

(I could potentially work on this.) 

I also think I'm getting some wierd bugs with CPU utilization. During one training run, all cores seemed to be fully used; and training took ~5 hours, but during another run where the only difference was pre-normalizing the data (and not using a normalizer in the tokenizer), the training is taking 15+ hours (and still going), but only 1 core seems to be active at a time.. 🤔

**Comment by Narsil** [comment]
> (I could potentially work on this.)

That would be super nice !

>  the only difference was pre-normalizing the data 

The data plays an essential role in the runtime of the algorithm. Especially for BPE.
Essentially BPE is really bad with long range data.

If you have a string of several megabytes, then when checking out the merges it's going to take an enormous time on fusing them. And this particular bit of the algorithm cannot be done in parallel.
It's most likely something like that.

@TevenLeScao if you want to share since you had a similar experience :)
