### ISSUE TITLE
What is the correct way to remove a token from the vocabulary?

### ISSUE THREAD

**Issue by tvallotton** [huggingface/tokenizers#1216]
I see that it works when I do something like this
```
del tokenizer.get_vocab()[unwanted_token]
```
~~And then it will work when running encode~~, but when I save the model the unwanted tokens remain in the json. Is there a blessed way to remove unwanted tokens?

EDIT: 
Now that I tried again see that does not actually work.

**Comment by Narsil** [comment]
No it doesn't work.

You can't really do that since vocabulary is not the only source of information for tokens.

You can save it on disk, look at the JSON and remove it there.
However you're likely to need to remove some `merges` too and it will probably render some other tokens unreachable.

If you're ok with that then it's OK.

**Comment by tvallotton** [comment]
I see, that is a little inconvenient but doable. Is the json output considered unstable?

**Comment by ArthurZucker** [comment]
Sorry for the late reply, but yes if you remove the merges that use the tokens you removed you should be alright. Note that there are going to be holes in your vocab
