### ISSUE TITLE
Bytelevel() pretokenizer vs BPE(byte_fallback =True)

### ISSUE THREAD

**Issue by chris-ha458** [huggingface/tokenizers#1218]
There is a bytelevel pretokenizer
And byte_fallback option in BPE

Does the bytelevel pretokenizer make byte_fallback redundant?
If not, how does the behavior change?

**Comment by Narsil** [comment]
They are 2 different things.

- ByteLevel is a trick originally from OpenAI gpt2 I believe which converts bytes into real printable valid utf-8 `char`. This is then fed into the BPE model to get tokenization which cannot contain any `unk` (since at least all bytes are covered).
- byte_fallback works differently by casting `unk` tokens into their bytes representation. That means that their is no mechanism to assemble those bytes back. 

Does that answer your question ?

**Comment by chris-ha458** [comment]
since ByteLevel in principle makes the tokenization not contain any unk, does byte_fallback become redundant?
My confusion is that since they work differently there might be value in having them both on. 
I am trying to build a tokenizer for a multilingual decoder only generative model
and I am not sure which one (or both) I should turn on.
I settled on both, since they work differently but another member pointed out that they might be redundant.
Would you recommend having them both on?

**Comment by mert-kurttutan** [comment]
I was also looking into sth related to this. In case, you want some original link, here is the code for converting byte values (original gpt2 tokenizer) into utf-8 compatible characters that narsil hinted at.
https://github.com/openai/gpt-2/blob/master/src/encoder.py#L9

**Comment by chris-ha458** [comment]
ByteLevel() pretokenizer ensures that the BPE algorithm + ByteLevel() alphabets can handle all cases without UNK issues.

Just as ByteLevel()  pretokenizer relies on the ByteLevel()  decoder, Byte_fallback relies on the reconstitution of utf-8 fallbacks byte into valid utf-8 tokens.
