### ISSUE TITLE
Cargo.lock is not available

### ISSUE THREAD

**Issue by bobvanderlinden** [huggingface/tokenizers#1226]
Since https://github.com/huggingface/tokenizers/pull/1131, all Cargo.lock files were removed. This makes development cleaner, but it becomes very hard to reproduce a specific release of tokenizers.

This helps with tools that are strict about its dependencies, like Nix. People have run into this problem with `poetry2nix` (https://github.com/nix-community/poetry2nix/issues/968) as well as packaging applications in nixpkgs (https://github.com/NixOS/nixpkgs/pull/227126).

The current solution in such cases is to generate a `Cargo.lock` ourselves and ship it with the package. The result is that tokenizers won't operate the same as the developers have intended. It could cause hard to reproduce bug-reports.

Would it be possible to distribute `Cargo.lock` in future releases?

**Comment by chris-ha458** [comment]
according to the other issues, it seems that current rate of development makes it difficult to support reproducible builds (cargo.lock)

**Comment by bobvanderlinden** [comment]
I can get why lock files will become annoying if they need to be updated multiple times a day.

I'm mostly asking about shipping them as part of releases. Those do not happen that regularly and since they exist for a longer time it helps a lot to know which dependencies were used.

Apart from it being helpful for tools like Nix, it also helps for applications relying on a tokenizers release. They will eventually run into incompatibilities because the dependencies are in flux and it will not be clear at that time what is a good set of dependencies.

**Comment by hvaara** [comment]
Thanks for raising the concern @bobvanderlinden. I'll try to clarify below. Please feel free to disagree with me or point out where I'm misunderstanding something -- I'm not familiar with NixOS.

`tokenizers` is library, not a binary. Some additional color and motivation for why lockfiles shouldn't be part of libraries can be found in [The Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock). It's also covered in the [FAQ section](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) of the book.

It's up to the distributor to do the pinning. The specific versions of the dependencies will vary across distributions. One version could be pinned in NixOS, another version in a different distribution. This is intentional and by design.

> The current solution in such cases is to generate a Cargo.lock ourselves and ship it with the package.

I think this is WAI. For reproducible builds you'd have to distribute the pins with the package somehow. Either as the `Cargo.lock` file or out of band as part of the metadata.

> The result is that tokenizers won't operate the same as the developers have intended. It could cause hard to reproduce bug-reports.

Why do you think this is the case? [Semver](https://semver.org/) is intended to prevent this problem. See also [Specifying Dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies) in the Cargo Book). Can you point me to specific instances where seen issues in the past? What does your post-packaging QA process look like in NixOS? Do you run any testing as part of the release cycle?

How does Nix and NixOS usually handle reproducible builds for Rust and Python dependencies? Upstream not specifying a lockfile is a pretty common pattern in general in the Rust and Python world.

**Comment by Narsil** [comment]
> It's up to the distributor to do the pinning. The specific versions of the dependencies will vary across distributions. One version could be pinned in NixOS, another version in a different distribution. This is intentional and by design.

The Python library is distributed as-is and it is indeed quite hard to reproduce without the associated `Cargo.lock`. It's actually only necessary on release branches and not really anywhere else. But until I can figure out a way to make it easy to add specifically on those branches we ca readd everywhere (only in the python bindings). It's still annoying  most likely but number of commits has gone down significantly since the file was removed.

**Comment by bobvanderlinden** [comment]
Thanks for the explanation! Yes I should've made clear that this is mostly an issue for the python (and probably nodejs) library. For these libraries the Cargo.toml is the top-level toml, so there won't be any Cargo.lock file available in an application.

For my purposes it would be enough to have the lock file in the pypi package and not on a branch.

Though I can imagine that when releasing a new patch version of tokenizers that the same rust dependencies are to be used from the precious release unless they were explicitly updated. That would be an pro for including the lock file in release branches/tags.

Is there something I can help with to make sure this happens for an upcoming release?

> How does Nix and NixOS usually handle reproducible builds for Rust and Python dependencies?

Nix can be seen as a build system where the build results can be used as packages. It is language-, distribution-, and os-agnostic. The build results are stored under a unique name that contains a hash of _all_ inputs of a build (like source code, build tools and dependencies). Outside sources (like source code) always require an url to fetch and a content hash to verify. A change of hash would change the hash/name of all dependant packages(!)

Packages are typically built inside a sandbox where only the explicitly stated dependencies are available.

Poetry2nix is a project that converts each python package it finds in a poetry.lock into a Nix package. Python packages often have a number of implicit dependencies. This includes build tools like pkg-config, rust or native dependencies like ffmpeg, libz and others. Poetry2nix maintains a list of 'overrides' that add these kinds of dependencies. These become part of the hash of the Nix-wrapped python packages. When you want to build with a newer rustc version, all of these python packages that depend on rust will be rebuild.

**Comment by hvaara** [comment]
Oh yeah, that's a very good point. I didn't think about this. I see how the current state will inhibit reproducible builds now, thanks for pointing it out!

Did this issue get resolved already, or is there an action pending?

**Comment by bobvanderlinden** [comment]
It's still a problem :sweat_smile: I just ran into this again when trying to lock down the dependencies using poetry2nix for a different project this time. The issue there is still open: https://github.com/nix-community/poetry2nix/issues/968

Also, I see the same thing happening for safetensors as well.

It would be really nice if the Cargo.lock were there for those that need to build these libraries from source.

**Comment by Narsil** [comment]
There hasn't been a release since.

And yes I removed the `Cargo.lock` from both `main` because they keep messing the CI (and benchmarks in safetensors).
I'll figure out a way to add them in the release branches.

**Comment by MostAwesomeDude** [comment]
Hi, I'm going to attempt to fix this permanently in `poetry2nix`. Please note that if you do not provide `Cargo.lock`, then downstream gets to choose the versions of dependencies, which can lead to bug reports that you cannot reproduce later. Please also note that this is common across the HuggingFace libraries, which could lead to permanent version drift later.

**Comment by Narsil** [comment]
> fix this permanently in poetry2nix

That would be nice, how would that work ?
Happy to make the switch to pyproject.toml/poetry if that can make future maintenance easier

From my side, the ideal thing would be a GH action I insert in the release that creates a commit with the `Cargo.lock` in the release branch (or any other mecanism that makes it not care).

Having a few hurdles recently with weird things happening on MacOS (13, 14 don't pull from pypi as before the 12_0 wheels). It might be that the actual build uses different packages for different platforms.
Not sure you care in nix, but still.

**Comment by MostAwesomeDude** [comment]
> That would be nice, how would that work?

See the linked PR; I'm hardcoding a `Cargo.lock`, and every time you release, I'll add another one.

> tokenizers is library, not a binary.

From the Python perspective, it's a binary. You should lock your dependencies on every release, minimum. Preferably, you would check your lockfile into git.

> …I removed the Cargo.lock from both main because they keep messing the CI…

If this is a problem for CI, then I recommend adding a CI step which deletes or regenerates your lockfile; this will allow your CI to interoperate cleanly with Rust.

**Comment by bobvanderlinden** [comment]
I think this is still relevant.

**Comment by ArthurZucker** [comment]
No, the lock files are now part of the release: https://github.com/huggingface/tokenizers/commit/284fbd8e215a34d3b8de849a1d0bca292116b11f

**Comment by bobvanderlinden** [comment]
Oh nice! Thanks for the heads-up. That should allow a cleaner solution in poetry2nix. I'll close this issue.
