### ISSUE TITLE
LlamaTokenizer adds space when decoding `<s>`

### ISSUE THREAD

**Issue by lizelive** [huggingface/tokenizers#1237]
```python
from transformers import LlamaTokenizer
model_id = "lmsys/vicuna-13b-delta-v1.1"
tokenizer = LlamaTokenizer.from_pretrained(model_id, add_bos_token = False, )
message = "<s>hello</s>"
decoded = tokenizer.decode(tokenizer(message)['input_ids'])
print(decoded, decoded == message)
```

this makes me sad.

**Comment by Narsil** [comment]
This property can never be guaranteed.

@ArthurZucker 

Cf : https://github.com/huggingface/transformers/pull/20846

**Comment by lizelive** [comment]
This happens regardless of that value.

**Comment by Narsil** [comment]
You're right, clean actually removes those spaces, here it's adding one.

I'm pretty sure then this is working as intended.

In general tokenizers add a prefix space to incoming strings in order to match "full words" instead of "within word" token.


Like so:
`Hello Hello` you want to match the same id (let's say 42 so `[42, 42]`.

But since this tokenizer is including the space within tokens to mark them "start of word" (without actually explicitly using a mecanism for that, those tokens just happen to include the whitespace).

That means 42 is actually `" Hello"` (with prefix space).
In order to get `"`Hello Hello" -> [42, 42]` the normalize adds a prefix space to the string.

And during decoding well `42 ->  " Hello"` so the prefixed space is included.

**Comment by lizelive** [comment]
Okay but if I call it repeatedly it just keeps adding spaces

**Comment by Narsil** [comment]
Yes, as I said the tokenizer prefixes whatever comes its way with a space.

I really think doing `decode(encode(x))` is the root of your issues. If you explain what you're trying to do I might be able to provide alternate more robust routes.
