### ISSUE TITLE
Bug with tokenizer.add_tokens()

### ISSUE THREAD

**Issue by liujuncn** [huggingface/tokenizers#1243]
See test case below:

![image](https://github.com/huggingface/tokenizers/assets/902005/82dca17c-0ce7-4491-8230-627b33371fa1)

The behavior is not what it said:
" The given tokens are added only if they don't already exist in the vocabulary."

**Comment by Narsil** [comment]
Can you provide a fully reproducing script ?

**Comment by liujuncn** [comment]
`from tokenizers import Tokenizer

vocab = "my_vocab.json"
tokenizer = Tokenizer.from_file(vocab)

# test case
token = "中文"
# show token's original id
print(tokenizer.encode(token).ids)
print(tokenizer.decode([6778]))
assert tokenizer.add_tokens([token,]) == 1
# show token's new id
print(tokenizer.encode(token).ids)`

**Comment by liujuncn** [comment]
from tokenizers import Tokenizer

vocab = "my_vocab.json"
tokenizer = Tokenizer.from_file(vocab)

# test case
token = "中文"
# show token's original id
print(tokenizer.encode(token).ids)
print(tokenizer.decode([6778]))
assert tokenizer.add_tokens([token,]) == 1
# show token's new id
print(tokenizer.encode(token).ids)

**Comment by chris-ha458** [comment]
your link does not work. but its a simple fix : [https://huggingface.co/fnlp/moss-moon-003-base/resolve/main/vocab.json](https://github.com/huggingface/tokenizers/issues/url)

Also it is only the vocab file rather than the tokenizer.json file. Can you please provide the original one?

I think atleast for this case, the issue is that you are using bytelevel() pretokenizer. as such 中文 token does not exist as is inside your vocabulary. it exists as a bytelevel() pretokenized version.
As such if you try to add 中文 it is possible while for other english words that retain their form are not affected.

The way you added the token 中文 would be make it different from the learned version of 中文 which would look more like 'Ġä¸Ńæĸĩ' and/or 'ä¸Ńæĸĩ' depending on how you initialized bytelevel() or what it learned.

**Comment by liujuncn** [comment]
Yes, I do use bytelevel() pretokenizer. I think this can ensure that Chinese characters that are not in the vocabulary can also be encoded.

I make a simple vocab file for you: [https://github.com/liujuncn/strategy_dataset/blob/master/test_vocab.json](url)

`bpe = BPE()
tokenizer = Tokenizer(bpe)
tokenizer.pre_tokenizer = ByteLevel(add_prefix_space=False)
tokenizer.decoder = decoders.ByteLevel()
trainer = BpeTrainer(vocab_size=100)`

**Comment by chris-ha458** [comment]
1. check current vocab by using tokenizer.decoder.decode on the vocab to check if the target has been encoded
2. if not, use bytelevel.pre_tokenize_str before adding the tokens

However, it is usually not a good idea to manually add "normal" tokens and not "special tokens"
Try expanding your training corpus, especially with text that would include the target tokens.
since 中文 are fundamental characters you could also use initial alphabet functions too.

**Comment by liujuncn** [comment]
@chris-ha458 thank you!

**Comment by liujuncn** [comment]
Because I can optimize the result of words count production better for CJK and control memory cost.

**Comment by liujuncn** [comment]
I have reimplemented BBPE with reference to your rust code, achieving the efficiency I expect. This issue can be closed.
