### ISSUE TITLE
pre_tokenizers/byte_level.rs lacking docs

### ISSUE THREAD

**Issue by steventrouble** [huggingface/tokenizers#1276]
A couple functions in `tokenizers/src/pre_tokenizers/byte_level.rs` are lacking documentation and this significantly harms the code health of this file. In particular, the following functions are not self-explanatory and are not documented:

*  [`bytes_char()`](https://github.com/huggingface/tokenizers/blob/8c9cfb0b689bce00b615b9557a9a767f286d7a33/tokenizers/src/pre_tokenizers/byte_level.rs#L12): Which characters does it map to what?
*   [`RE`](https://github.com/huggingface/tokenizers/blob/8c9cfb0b689bce00b615b9557a9a767f286d7a33/tokenizers/src/pre_tokenizers/byte_level.rs#L36): I shouldn't need to explain why a regex named RE might need docs.

I'd be happy to document these myself, but I won't waste my time if the PR won't be accepted. Would a PR to fix the docs here be accepted?

**Comment by Narsil** [comment]
Hey doc is always welcome.

In this particular case I think the best thing to do would be to link to the original repo:

https://github.com/openai/gpt-2/blob/master/src/encoder.py#L9
https://github.com/openai/gpt-2/blob/master/src/encoder.py#L53

There's not much more doc to be added that that. This pretokenizer just mimicks what openai has done at the time. The reason why these objects are as they are doesn't seem to be included anywhere.
bytelevel in itself is just a mecanism to go from plain bytes to valid utf-8 strings so that there cannot be a decoding error internally as decribed here: https://github.com/huggingface/tokenizers/blob/8c9cfb0b689bce00b615b9557a9a767f286d7a33/tokenizers/src/pre_tokenizers/byte_level.rs#L110-L111
