### ISSUE TITLE
Seeding a tokenizer with initial tokens

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/tokenizers#1280]
As part of a distillation project I want to reduce the vocabulary size of a model without retraining the tokenizer. For instance, if I distil a multilingual model with 250k model to a monolingual LANG_X student model with only 30k vocabulary, I might do something like this:

- find a monolingual dataset in LANG_X
- tokenize it with the teacher model's tokenizer
- collect the token IDs that were generated
- keep topk=30k tokens
- save as updated tokenizer?

To do so, I first thought of "simply" removing the tokens from the tokenizer that I do not need but as far as I can tell that is near impossible to do automatically because of how the merges are generated if I understood @Narsil correctly (https://github.com/huggingface/tokenizers/issues/1216#issuecomment-1503759794). My second thought would be to do it the other way around: use the collected token IDs as a seed to a new tokenizer, and then train the tokenizer with those tokens to build the merges and potentially other files that are needed.

Does that make sense and is that at all possible?

**Comment by chris-ha458** [comment]
for the first point, that is my understanding as well.
For the second point, there does not seem to be an effective way to seed a tokenizer vocabulary.
Without the appropriate merge pairs it would be equivalent to just adding a lot of tokens.

**Comment by Narsil** [comment]
> Does that make sense and is that at all possible?

I'm not sure. One way you could get away with it is instead of `keep topk=30ktokens` you instead try to compute each subtoken for your top=1 token, keep ALL of them, then get to topk=2 etc.. 

You have no way of knowing how many subtokens are necessary to generate a given token, but you can reconstruct that on the fly.
Either you do a recursive descent:  `tokenize(token[:split]), tokenize(token(split:])` . Trivial to code but could be brittle.
The other way would be the compute the tree of tokens with both parent,children links, and once you have a token flag all children.
