### ISSUE TITLE
Incorrect treatment of special tokens added prior to training

### ISSUE THREAD

**Issue by mwaskom** [huggingface/tokenizers#1281]
Given the following example tokenizer:

```python
import tokenizers
print("Tokenizers version:", tokenizers.__version__)

tokenizer = tokenizers.Tokenizer(tokenizers.models.WordLevel())
tokenizer.pre_tokenizer = tokenizers.pre_tokenizers.Sequence([
    tokenizers.pre_tokenizers.Punctuation(),
    tokenizers.pre_tokenizers.WhitespaceSplit(),
])
trainer = tokenizers.trainers.WordLevelTrainer(vocab_size=100, min_frequency=0)
```
```
Tokenizers version: 0.13.3
```

Prior to training I add a special token:

```python
tokenizer.add_special_tokens(["__bar__"])
print("Vocab pre-training:", tokenizer.get_vocab())
```
```
Vocab pre-training: {'__bar__': 0}
```

Then I train the tokenizer on a "corpus":
```python
s = "foo __bar__ buz bum"
tokenizer.train_from_iterator([s], trainer)
print("Vocab pre-serialization:", tokenizer.get_vocab())
print("IDs pre-serialization:", tokenizer.encode(s).ids)
```
```
Vocab pre-serialization: {'__bar__': 0, '_': 0, 'bar': 1, 'foo': 4, 'buz': 3, 'bum': 2}
IDs pre-serialization: [4, 0, 3, 2]
```

Finally, I serialize the tokenizer to json, then deserialize and use it:
```python
tokenizer_from_ser = tokenizers.Tokenizer.from_str(tokenizer.to_str())
print("Vocab post-serialization:", tokenizer_from_ser.get_vocab())
print("IDs post-serialization:", tokenizer_from_ser.encode(s).ids)
```
```
Vocab post-serialization: {'_': 0, '__bar__': 5, 'bum': 2, 'buz': 3, 'bar': 1, 'foo': 4}
IDs post-serialization: [4, 5, 3, 2]
```

I see two issues here:

1. Prior to serialization, there is a collision in the vocabulary between the special token added prior to training and the components of the special token (after the punctuation split).
2. When deserializing the tokenizer, *the special token is assigned a new ID*. This caused a serious problem in a workflow where a tokenizer was trained at the same time as a model and serialized together, then deserialized and used.

**Comment by Narsil** [comment]
Hey thanks for the report.

The issue is very clear and is actually a slightly more general problem. In general the arguments from `tokenizer` and `trainer` don't properly flow from one to the other (either direction). Here it's the added vocabulary.

PRs are welcome, but imo the issue is that we cannot keep any ids from the original added vocabulary. It's impossible to make things consistent that way (special ids can have holes and start anywhere which make it imposible for the model to figure it out). 

Any suggestions on how to make this easier on users with low effort on our end is also welcome.

**Comment by mwaskom** [comment]
Not sure I 100% understand the underlying limitations, but if that's the case, would it make sense to add some guardrails to avoid nasty surprises like this? E.g. the training process could perhaps raise if the tokenizer already has a vocabulary.

**Comment by mwaskom** [comment]
Two other comments:

- It's a little bit hard to understand the expected behavior for special tokens (/ "added" tokens, and what the difference is) or what the best practices are for training a tokenizer from the documentation, which is rather terse in many respects. Normally I would at least be able to read through the code, but not knowing Rust makes that more difficult.

- Maybe it doesn't matter here but it feels like a defect for `to_str`/`from_str` not to round-trip, even with a malformed vocabulary.

**Comment by Narsil** [comment]
Hi, I perfectly understand.

However my time is really stretched at the moment, and unfortunately `tokenizers` is not the top at my priority list, training a tokenizer even less so.

It kind of works, following the documentation stricto sensus should work, but anything outside of it might yield suprises as you've seen.
It's hard to know if the issue in the round trip you've seen is a display error, a core error, or something else, and diving in requires a good chunk of time, even more to figure out a fix. And if I did I would be more tempted to *close* API surface that *open* it (which is breaking which is why it's never great for users, even when it prevents footguns).

**Comment by mwaskom** [comment]
Given that the encodings themselves change post-serialization (and not just the printed vocab) I don't think it's limited to a display problem?

**Comment by Narsil** [comment]
I don't know.

**Comment by ArthurZucker** [comment]
I will try to investigate, for now I recreated the script with pure rust, and it seems like the problem is not from here: the following codeis failing as expected:
```rust 
fn wordlevel_values_after_training() {
    let pretokenizers = vec![
        PreTokenizerWrapper::WhitespaceSplit(WhitespaceSplit),
        PreTokenizerWrapper::Punctuation(Punctuation::default()),
    ];
    let pretok = PreTokenizerWrapper::Sequence(Sequence::new(pretokenizers));
    let mut tokenizer: tokenizers::TokenizerImpl<WordLevel, NormalizerWrapper, PreTokenizerWrapper, PostProcessorWrapper, DecoderWrapper> = TokenizerBuilder::<
        WordLevel,
        NormalizerWrapper,
        PreTokenizerWrapper,
        PostProcessorWrapper,
        DecoderWrapper,
    >::default()
    .with_model(
        WordLevel::builder()
            .unk_token("[UNK]".to_string())
            .build()
            .unwrap(),
    ).with_pre_tokenizer(Some(pretok))
    .build()
    .unwrap();


    tokenizer.add_special_tokens(&[AddedToken::from("__bar__", true)]);
    let mut trainer = tokenizer.get_model().get_trainer();
    tokenizer
        .train(&mut trainer, vec!["foo __bar__ buz bum".to_string()].iter())
        .unwrap();

    assert_eq!(tokenizer.get_model().unk_token, "[UNK]".to_string());
    println!("{:?}", tokenizer.encode("foo __bar__ buz bum", false));
    assert_eq!(tokenizer.encode("foo __bar__ buz bum", false).unwrap().get_ids(), vec![4,0,3,2]);

    println!("{:?}", tokenizer.to_string(true));

    let ser: String = serde_json::to_string(&tokenizer).unwrap();
    let tokenizer_from_ser:Tokenizer = serde_json::from_str(&ser).unwrap();
    println!("Vocab post-serialization: {:?}", tokenizer_from_ser.get_vocab(true));
    println!("IDs post-serialization: {:?}", tokenizer_from_ser.encode("foo __bar__ buz bum", false).unwrap().get_ids());
    assert_eq!(tokenizer_from_ser.encode("foo __bar__ buz bum", false).unwrap().get_ids(), vec![4,0,3,2]);

}
```

**Comment by ArthurZucker** [comment]
Okay, the `Vocab pre-serialization: {'__bar__': 0, '_': 0, 'bar': 1, 'foo': 4, 'buz': 3, 'bum': 2}` gives it out, you should not have to tokens pointing to the same index. 
When you add the token to the vocab, if you want to add it at the beginning it should be added to the actual vocabulary directly. 

`add_token` adds a token at the end of the vocab, but if the vocab is empty training will of course update it. That's because the order is wrong IMO. You should pass a `special_tokens = ["__bar__"]` to the word level training
