### ISSUE TITLE
Is there a way to supress this warning?

### ISSUE THREAD

**Issue by shatz01** [huggingface/tokenizers#1298]
```
warn!("The OrderedVocab you are attempting to save contains a hole for index {}, your vocabulary could be corrupted !", i);
```
Found here: https://github.com/huggingface/tokenizers/blob/5f6e9784526a4cd5e4f6dcdcc045cdceba5463e1/tokenizers/src/models/mod.rs#L42C53-L42C53

Our OrderedVocab has holes on purpose, so this warning is quite annoying.

Thanks!

**Comment by Narsil** [comment]
> has holes on purpose

You do understand how this waste model memory (by having unused slots) and that this is definitely a very odd situation to be in.
This should technically be a hard error, but unfortunately, some relatively popular legacy models do have holes (by accident), that's why we downgraded to hard warning.

Do you mind sharing a bit more details on the 'on purpose' situation ? I don't understand how this can be a normal situation.

**Comment by floccinauc** [comment]
@Narsil, we maintain a collection of tokenizers that all map to a consistent ID space. e.g. tokenizer A and B have same special tokens (mapping to IDs 0-20), but different regular tokens (tokenizer A mapping to IDs 21-100, and tokenizer B to IDs 101-1000). Tokenizer B has a hole in ID space where A's regular tokens are mapped, but when these are combined, the ID space is contiguous. 
Furthermore, we want to maintain buffers to add future tokens, and for these we also need to leave holes in all tokenizers. This way, if we add tokens (or whole tokenizers) in the future, we won't have to change existing mapping. We're aware of the memory waste, but it's a price we're willing to pay for the modularity.

**Comment by Narsil** [comment]
I understand.

This seems like a very power user thing to do then. I think leaving and ignoring the message (since you're aware it doesn't apply to you) is bearable then, no ?

And the final A+B tokenizer should have no holes in the end, which I imagine will be the final thing, correct  ?

**Comment by Narsil** [comment]
I can work out having a single warning instead of many, but I really don't want to make the warning suppressible. It is a critical issue, that as I mention, should ideally be a `raise Exception` and cannot only because of legacy tokenizers.

Having subtokenizers is not really something intended than I can realistically support. I just don't have the bandwidth for it.

**Comment by floccinauc** [comment]
If possible, single warning instead of per-ID, would be a significant improvement, thanks!

**Comment by floccinauc** [comment]
Thanks!
