### ISSUE TITLE
Rust panic when tokenizing after adding vocabulary that contains zero-width chars

### ISSUE THREAD

**Issue by ali-tny** [huggingface/tokenizers#1349]
Tokenization fails for certain chars when vocabulary is extended with tokens that contain zero-width chars. 

```
from transformers import AutoTokenizer

extra_tokens = [
    'aaaa',
    'eg',
    'deb',
    '\u200c',
    'ccfc'
]

tokenizer = AutoTokenizer.from_pretrained("thenlper/gte-base")
# This runs fine
print(tokenizer("£"))

tokenizer.add_tokens(extra_tokens)
# This fails with `thread '<unnamed>' panicked at 'AddedVocabulary bad split'`
tokenizer("£")
```

What's particularly weird is that the above is a minimal example - if I drop any of the extra tokens, or even edit the strings themselves in certain ways (eg turn `"aaaa"` to `"aaab"` or `"aaa"`), it no longer fails. 🤯 

The solution in our case will be to try to avoid the weird characters in our extra vocabulary, but it was quite difficult to discover the issue here, and the failure is difficult to understand. Even if it's not fixed, failing in a more understandable way that points the user to try to clean the data would be v useful!

Error is present in v0.13.4.rc3 and v0.14

**Comment by ArthurZucker** [comment]
There is indeed a problem:
```python
BertTokenizerFast(name_or_path='thenlper/gte-base', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
        0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        30522: AddedToken("aaaa", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
        30523: AddedToken("eg", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
        30524: AddedToken("deb", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
        30525: AddedToken("‌", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
        30526: AddedToken("ccfc", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
}
```
an emptyu token was added: ` 30525: AddedToken("‌", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),` which is from `'\u200c'`. 

I am not sure if the problem is that the tokenizer does not support adding unicode (which to me is expected) or that we are not preventing the addition of empty tokens! 

I think we should add a check in the `add_tokens` to make sure empty tokens are skipper.

**Comment by Narsil** [comment]
@ArthurZucker I think they are not empty, they are zero-width. Which is different.

The bad split exceptions are defined here :https://github.com/huggingface/tokenizers/blob/main/tokenizers/src/tokenizer/added_vocabulary.rs#L433  (3 locations).

Could be that the slices are somehow confused by offsets..

**Comment by ali-tny** [comment]
interestingly, emoji don't cause the panic, eg using
```
extra_tokens = [
    'aaaa',
    'eg',
    'deb',
    '🤗'
    'ccfc'
]
```
despite being unicode (although even after added to the vocab they get tokenized to [UNK], which sounds like it's expected)

**Comment by Narsil** [comment]
@ali-tny We dug this up, the issue is thet those tokens are "regular" tokens, therefore they get normalized.

If your tokenizer uses lowercase tokenization for instance and you add token "HEY" it will first get normalized to "hey" and we will tokenize on "hey". This is normal and intended behavior.

What happens here with the zero-width, is that the token gets normalized to empty string, which is obviously not going to yield good results.
What's going to happen instead in the short term is that we may panic on `add_tokens(,..)` call since the zero-width is not valid token. 

If you *really* want to split on this zero-width, you need to add it as special token (which doesn't get normalized, and is capture before).

Is this clearer ?

**Comment by ali-tny** [comment]
@Narsil makes sense. I don't really see any reason why someone would want to split on the zero-width - in our case, we built the extra vocabulary via training a BPE tokenizer, and didn't realise the weird chars were in there. Totally agree that moving the panic to the `add_tokens` call would be helpful, especially if the error message points to a zero-width char would solve the problem. 

thanks!
