### ISSUE TITLE
is there a guidance to adapt tokenizers to c++ project?

### ISSUE THREAD

**Issue by 7908459077d71a548753960a12b71146** [huggingface/tokenizers#1440]
I want to use tokenizers in my c++ project for its perfomance, what should I do? Or is there already a guidance? 
Any advice would be greatly appreciated.

**Comment by Narsil** [comment]
There are no C bindings currently available.

However you could probably setup some yourself relatively easily depending on the surface you need:

https://developers.redhat.com/articles/2022/09/05/how-create-c-binding-rust-library#logging_in_the_c_binding
https://docs.rust-embedded.org/book/interoperability/rust-with-c.html

Depending on your project you could probably expose a handeful of function lile `Tokenizer::from_file` and `Tokenizer::encode`  (Using wrapper C struct containing pointers to the actual rust structs which are NOT `#[repr(C)]`.)

Providing a fully functional C API is much more complicated in the context of this library, given the lack of ownership control in C, which makes creating security issues very easy, which is why it is not done.

**Comment by chenpei2** [comment]
Will there be c++ bindings in the future?
