### ISSUE TITLE
Can I use SentencePieceBPETokenizer to replace google/sentencepiece?

### ISSUE THREAD

**Issue by npuichigo** [huggingface/tokenizers#1614]
I'm not sure if it's 100% replaceable

**Comment by ArthurZucker** [comment]
Hey, `google/sentencepiece` can be replaced by `tokenizers` not by the `SentencePieceBPETokenizer`. The reason is that `sentencepiece` also includes `Unigram`, which can also be created with `tokenizers` but not with the `SentencePieceBPETokenizer`. 

Which model do you want to convert? We have conversion scripts in `transformers` see: https://github.com/huggingface/transformers/blob/main/src/transformers/convert_slow_tokenizer.py#L75

**Comment by ArthurZucker** [comment]
You can convert any `google/sentencepiece` to `tokenizers`

**Comment by npuichigo** [comment]
What if I direct call train method on SentencePieceBPETokenizer?

**Comment by ArthurZucker** [comment]
It should behave the same way. You won't get 1-1 the same trained tokenizer (seeds and dropout) but it's gonna be almost the same

**Comment by npuichigo** [comment]
Thanks.
