### ISSUE TITLE
Creating a ByteLevelBPETokenizer from own corpora, special tokens problem

### ISSUE THREAD

**Issue by simonefrancia** [huggingface/tokenizers#166]
Hi,
I would like to create a GPT2 tokenizer based on my own data.

My data are formatted in a certain way and I would like to recreate the structure; for this reason I want to add a special token <nl> instead of \n because I want GPT2 to learn also when it has to put newlines inside text. This is my code:

```
# Initialize a tokenizer
tokenizer = ByteLevelBPETokenizer(add_prefix_space=False)

# Customize training
tokenizer.train(files=paths, 
                vocab_size=8_000, 
                min_frequency=2, 
                special_tokens=["<unk>", "<s>", "</s>", "<pad>", "<mask>", "<nl>"])

print(tokenizer.encode("Training <nl> hi ciao <nl> ").tokens)
tokenizer.save("./my-gpt2/", name="my")
```
Output of last code line is:
```
['T', 'ra', 'ining', 'Ġ', '<nl>', 'Ġhi', 'Ġc', 'ia', 'o', 'Ġ', '<nl>', 'Ġ']
```
My doubt is that <nl> is encoded ok but it has the special token before as single token and I don't understand if it's ok.

After I create my own tokenizer, I would like to use it as input tokenizer for language model training for the script: https://github.com/huggingface/transformers/blob/master/examples/run_language_modeling.py
with the --tokenizer_name parameter pointing at my own tokenizer.
Thanks

**Comment by n1t0** [comment]
Hi @simonefrancia! Using `ByteLevelBPETokenizer`, nothing gets stripped out or cleaned up in any way from your original text. This means that the spaces you are using around both `<nl>` get encoded as you can see with the `'Ġ'` tokens (they represent a space in the byte-level encoding).

You can check what I'm saying by doing:
```
print(tokenizer.encode("Training<nl>hi ciao<nl>").tokens)
```
The various single `'Ġ'` shouldn't be there anymore, they are just still there at the beginning of words that follow a space.

Now, I can't really advise you on whether it is better to pre-process your text, using your special `<nl>` token or not, but please note that since `ByteLevelBPETokenizer` is not removing anything, the real newline character stays in your encodings:
```
test = """Training
hi ciao"""
print(tokenizer.encode(test).tokens)
```
will give you the following output:
```
['T', 'ra', 'ining', 'Ċ', 'hi', 'Ġc', 'ia', 'o']
```
where `'Ċ'` represents the said newline.

Closing this issue, feel free to reopen if needed!
