### ISSUE TITLE
Exception: WordPiece error: Missing [UNK] token from the vocabulary

### ISSUE THREAD

**Issue by dizzySummer** [huggingface/tokenizers#168]
Hi! 

As to the above-mentioned issue, I 've got this error message:

https://github.com/dizzySummer/temp/blob/master/errorMessage#L1-L30

Any comments?

Thank you!

**Comment by n1t0** [comment]
Hi @dizzySummer. 

From the file you linked, I can see that you are giving these tokens during training (cf [here](https://github.com/dizzySummer/temp/blob/master/errorMessage#L10-L14)):
```
    '<pad>',
    '<s>',
    '</s>',
    '<unk>',
    '<mask>'
```

Then later, you load this `BertWordPieceTokenizer` while not providing these special tokens to the model, so it uses the defaults (cf [here](https://github.com/huggingface/tokenizers/blob/master/bindings/python/tokenizers/implementations/bert_wordpiece.py#L16-L25)): 
```
        unk_token: str = "[UNK]",
        sep_token: str = "[SEP]",
        cls_token: str = "[CLS]",
```
That is confirmed when you `print(tokenizer)`:
```
Tokenizer(vocabulary_size=9937, model=BertWordPiece, add_special_tokens=True, 
unk_token=[UNK], sep_token=[SEP], cls_token=[CLS], clean_text=True, 
handle_chinese_chars=True, strip_accents=True, lowercase=True, 
wordpieces_prefix=##)
```
So what you need to do here is to provide the tokens during initialization:
```
tokenizer = BertWordPieceTokenizer(
    "/newBert-vocab.txt", 
    lowercase=True, 
    unk_token="<unk>",
    sep_token="</s>",
    cls_token="<s>"
)
```
And also let it know about your other special tokens so that they don't get split:
```
tokenizer.add_special_tokens([ "<pad>", "<mask>" ])
```

**Comment by dizzySummer** [comment]
@n1t0 Thanks! It's working now.
