### ISSUE TITLE
What's the best way to install a standalone version?

### ISSUE THREAD

**Issue by ylmeng** [huggingface/tokenizers#173]
I need to install the tokenizers on a high-security server, where internet access is impossible. The only thing I can do is to upload files there with scp.

I managed to download (and upload) the src, set environment etc. However when I run 

> cd tokenizers/bindings/python
> python setup.py install

I always got 

> error: Can not find Rust compiler

I did install Rust. So I suppose it is some configuration problem. But with the limited instructions it is very difficult to figure out what happened.

**Comment by n1t0** [comment]
Hi @ylmeng. Did you check if Rust is available in your environment? If you are running with sudo you should also make sure that it is available:
- `rustc --version` should output something.

Otherwise, I think there might be an easier process:
- Check here which `.whl` wheel file match your system most: https://pypi.org/project/tokenizers/#files
- Download it and transfer it with scp
- Then install it with pip `pip install the_wheel_file.whl`

**Comment by ylmeng** [comment]
> Hi @ylmeng. Did you check if Rust is available in your environment? If you are running with sudo you should also make sure that it is available:
> 
> * `rustc --version` should output something.
> 
> Otherwise, I think there might be an easier process:
> 
> * Check here which `.whl` wheel file match your system most: https://pypi.org/project/tokenizers/#files
> * Download it and transfer it with scp
> * Then install it with pip `pip install the_wheel_file.whl`

Oh that is great. Thanks.
