### ISSUE TITLE
How to train a BertWordPieceTokenizer

### ISSUE THREAD

**Issue by thak123** [huggingface/tokenizers#195]
What are the special tokesn that should be passed to train a BertWordPieceTokenizer ?

BPE tokenizer does not work with Bert style LM as the bert requires masks and other features from input

**Comment by n1t0** [comment]
Hi @thak123! You'll find an example of training for `BertWordPieceTokenizer` here: https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/train_bert_wordpiece.py.

As you can see, some special tokens are included (even `[MASK]`), but it is actually up to you to chose whatever special tokens you want to add. These will be added in order to the base vocabulary. So for example in the script I linked above `[PAD]` would have the id `0`.
