### ISSUE TITLE
[Help] Is it possible to split up a chunk of text into sentences?

### ISSUE THREAD

**Issue by martinnormark** [huggingface/tokenizers#210]
Is it correctly understood, that the `SentencePieceBPETokenizer` can be used to tokenize a chunck of text into sentences?

```javascript
const tokenizer = await tokenizers.SentencePieceBPETokenizer.fromOptions({ vocabFile: "./bert-large-uncased-vocab.txt" });
const wpEncoded = await tokenizer.encode(text);

console.log(wpEncoded.length);
console.log(wpEncoded.tokens);
console.log(wpEncoded.ids);
console.log(wpEncoded.attentionMask);
console.log(wpEncoded.offsets);
console.log(wpEncoded.overflowing);
console.log(wpEncoded.specialTokensMask);
console.log(wpEncoded.typeIds);
```

The above returns empty results:

```
0
[]
[]
[]
[]
[]
[]
[]
```

I am probably doing something wrong?

**Comment by n1t0** [comment]
Hi @martinnormark. The `SentencePieceBPETokenizer` is just a variant of the `BPE` algorithm as used by `SentencePiece`. It uses the `▁` meta token to replace any white space and keeps them in the generated tokens so that it can decode back to the original text.

This is not a util function that you can use to split into sentences.

**Comment by martinnormark** [comment]
Thanks, closing this.
