### ISSUE TITLE
encode() of BertWordPieceTokenizer has wrong behavior upon japanese symbols

### ISSUE THREAD

**Issue by hymzoque** [huggingface/tokenizers#215]
```python
import tokenizers # 0.6.0
import json
with open('temp_corpus', 'w', encoding='utf-8') as f:
    f.write('アリババ株式会社の公式サイトです。サービス、会社情報、採用情報などをご覧いただけます')
tokenizer = tokenizers.BertWordPieceTokenizer()
tokenizer.train('temp_corpus', vocab_size=20)
res = tokenizer.encode('アリババ株式会社の公式サイトです')
print(json.dumps([res.tokens, res.offsets], ensure_ascii=False))
>> [["ア", "##リ", "##ハ", "##ハ", "株", "式", "会", "社", "の", "公", "式", \
     "サ", "##イ", "##ト", "##て", "##す"], \
   [[0, 1], [1, 2], [2, 3], [3, 4], [5, 6], [8, 9], [11, 12], [14, 15], [16, 17], \
    [18, 19], [21, 22], [23, 24], [24, 25], [25, 26], [26, 27], [27, 28]]]
```

1. The symbol 'バ' is encoded to 'ハ', 'で' is encoded to 'て', and they are different symbols
2. Offsets are confusing

**Comment by n1t0** [comment]
Hi @hymzoque.

1. I think this is due to the Bert normalizer stripping accents by default, can you try with `BertWordPieceTokenizer(strip_accents=False)`?
2. This is something that we recently changed. Can you try with `tokenizers==0.7.0rc3`? Offsets used to be relative to the normalized string, whereas now, they are relative to the original string. So it shouldn't be confusing anymore!

**Comment by hymzoque** [comment]
@n1t0 
Thanks, it works!
