### ISSUE TITLE
decoding bug with bert word piece tokenizer?

### ISSUE THREAD

**Issue by abhishekkrthakur** [huggingface/tokenizers#216]
Recently, I came across the following:

```
from tokenizers import BertWordPieceTokenizer

tokenizer = BertWordPieceTokenizer(path_to_vocab, lowercase=True)
s = "foo (bar)"
s_token_ids = tokenizer.encode(s).ids

print(tokenizer.decode(s_token_ids))
>> foo ( bar )
```

vs.

```
s_offs = tokenizer.encode(s).offsets

decoded_s  = ""
for i in range(len(s_offs)):
    decoded_s += s[s_offs[i][0]: s_offs[i][1]]
    if (i+1) < len(s_offs) and s_offs[i][1] < s_offs[i+1][0]:
        decoded_s += " "
print(decoded_s)
>> foo (bar)
```

This however does not happen when using BPE tokenizer (as far as I checked).

The above snippets were shared by @akensert, in the comments to this kaggle kernel: https://www.kaggle.com/akensert/complete-tf2-1-mixed-precision-implementation

Is this a bug or expected behavior?

**Comment by n1t0** [comment]
Hi @abhishekkrthakur. This is the expected behavior indeed. 

The `BertWordPieceTokenizer` (As used in the original Bert) has a normalization step that is pretty destructive: It strips out any accents, character controls and other weird characters as well as all whitespace. In the end, there are two types of generated tokens:
  - With a `##` at the beginning, meaning that the token is part of a word
  - Without the `##` at the beginning, meaning this token starts a word.

Now with all this missing information, the decoding step tries its best and makes the assumption that the words are separated by one whitespace. So, in the end, it does something like:
```
" ".join(tokens).replace(" ##", "").strip()
```
and finally clean up some specific cases that we know of, like removing whitespaces before some punctuation characters, and things like that.

This won't work in every case, especially with languages that do not separate words with whitespace, or code for example. For code, I would advise looking at the `ByteLevelBPETokenizer` that will encode new lines, whitespace and everything else.

**Comment by n1t0** [comment]
Closing this. Please reopen if needed.
