### ISSUE TITLE
Do raw text files require sentence segmentation?

### ISSUE THREAD

**Issue by ck37** [huggingface/tokenizers#231]
Hello,

When training a byte-level BPE tokenizer from scratch, do the raw text files need to include only one sentence per line as in SentencePiece? I looked but was not able to find anything in the documentation or source code to clarify this. Apologies if I just missed it though.

Either way, it would be nice to note it here: https://github.com/huggingface/tokenizers#quick-examples-using-python (I can do a PR if it would be helpful).

Thanks,
Chris

**Comment by n1t0** [comment]
Hi @ck37. There are no hard requirements on the way the text files should be formated. It actually depends on the result you want to obtain, and the tokenizer you are using.

For example, if you were to train a tokenizer with code samples, it would make sense to keep the formating just as it is. This way, your tokenizer can learn somehow how the formatting is important in some cases. But this would work only with a Tokenizer that does not trim the whitespaces.

The default `ByteLevelBPETokenizer` that we provide as an example, does not trim anything from the input text so it is up to you to decide what to do with the input.

If you plan on using your trained tokenizer with raw text, I'd train on raw text. If you plan on using it with sentences, without whitespaces around it, then add a [Strip](https://github.com/huggingface/tokenizers/blob/81be207819ec386db8f69df1a7eb8df70ece8078/bindings/python/tokenizers/normalizers/__init__.pyi#L95) normalizer to your tokenizer, and train it on one sentence per line.

Does it make sense?

**Comment by ck37** [comment]
Thank you @n1t0, I really appreciate the detailed response!

I guess I have two broad areas of follow-up:

1. How do we translate SentencePiece's request that there should be one sentence per line to the use of the tokenizers software? Do we just ignore that, or do we need to consider our use case? https://github.com/google/sentencepiece#train-sentencepiece-model

![image](https://user-images.githubusercontent.com/50770/80013492-d22d7c80-8483-11ea-987b-3a044ea4accb.png)

I.e. if someone wants to replicate BPE results that one would get from SentencePiece, should I segment my sentences so that there is one per line?

2. Relatedly, are the results from the tokenizers library sensitive to line breaks in the raw text? I.e. should I have a blank line between documents as I have seen online somewhere (unfortunately I can't find the exact tutorial at this time)? Should I remove line breaks from the original text, or at least multiple consecutive line breaks? How does this relate to the line-by-line argument when training a LM, if at all?

Basically, would it be possible to create a short documentation section that provides guidance on the formatting of the input file(s) - what does matter, or what doesn't matter? Even a few bullet points to start out would help a lot, because right now there is no explicit guidance as to what matters with the input format and how I should proceed from e.g. a pandas dataframe with documents and compiling them into raw text files for tokenization and later language modeling. That would really help with translating the existing documentation examples to a custom corpus.

For my specific application I am analyzing "raw" social media comments. So they are short documents that may have one or more sentences, possibly with arbitrary line breaks (e.g. Reddit) or possibly just a single line (e.g. a tweet), and punctuation could be very complex. Currently I am not removing line breaks and am dumping all text to a file with an extra blank line between observations. I am currently not segmenting sentences since spacy seems to be the main tool for that and it explicitly says that it doesn't expect to be accurate for social media text (which seems quite reasonable).

Thanks very much for your time & thoughts, I'm sure you all are swamped with too many user questions.

**Comment by n1t0** [comment]
I totally agree with you about the documentation and it will definitely be one of the big focus of the coming months. In the meantime, I'll try to help you out here.

Basically, `tokenizers` does not make any assumption on the type of text you will provide. We want you to be able to process any type of data, and so by default, there is absolutely no data loss, ie nothing gets trimmed out (whitespace, newlines, special characters, or whatever).
When you train a tokenizer, the input files are processed line by line, and these lines contain everything from the raw text, including the final `\n`. Each of these lines goes through the `Normalizer`, and the `PreTokenizer` that are specified on the `Tokenizer`, and we train on this. Both the `Normalizer` and the `PreTokenizer` are actually optional, so you decide how you want your text to be processed.

1. If you want a behavior similar to the one with SentencePiece, you can build a tokenizer like this:
```
from tokenizers import Tokenizer, models, normalizers, pre_tokenizers
tokenizer = Tokenizer(models.BPE())
tokenizer.normalizer = normalizers.Sequence([
    normalizers.Strip(),
    normalizers.NFKC()
])
tokenizer.pre_tokenizer = pre_tokenizers.Metaspace()
```
Now, when you train, each line will get through the `Normalizer`: strip any whitespace from both ends of the line, and run NFKC Unicode normalization. This way, it wouldn't see any newlines.

2. When you train your LM, you are also choosing how you process the data. By that I mean, you could feed your model with lines, or tweets, or a window over a Wikipedia article. So what's important is for you to decide how is the best way to format your data for your model to understand it. If you think something (newlines for example) should be considered as noise because it brings no information, then you should probably strip it out.

For your specific application, you could, for example, append in a file each tweet/comment, separated by something you know like `\r\n`. You just make sure that each sample does not contain a `\r\n` by replacing it with `\n`. That way, you can easily split your file in tweet/comment again, but you keep the potential newlines included in the text. Then you can train a tokenizer like the `ByteLevelBPETokenizer` on this file.
You can analyze what the vocabulary looks like, and what are the generated tokens when you try to encode some text, in order to decide if there is anything that you want to remove. Training your tokenizer shouldn't take really long, so you should be able to iterate rapidly if you find something to change. In the end, your tokenizer is the first half of your LM so it is worth the time spent :slightly_smiling_face:

**Comment by ck37** [comment]
Thanks a bunch, this is incredibly helpful! This gives me plenty to work with - really appreciate the extra details here. I will go ahead and close this to avoid cluttering the open issues.
