### ISSUE TITLE
how to install tokenizers from conda

### ISSUE THREAD

**Issue by liuwei1206** [huggingface/tokenizers#237]
Hi, I usually install tokenizers using pip3, but now I want to install it with conda. Unfortunately, it failed when I used "conda install tokenizers" ?  can you give me some helo how to install it with conda?

**Comment by MaximilianIdahl** [comment]
Hi,
since there seems to be no (at least not official) distribution of the tokenizers package via conda, I recommend you do the following:
* Make sure the conda environment of your choice is activated
* Install using pip
  * Make sure to use the pip of your conda environment, usually located at .../anaconda3/envs/`<your-env-name>`/bin/pip
  * you can verify which pip is used by running `which pip`
* (optional) verify installation by running `conda list`
  * conda will be aware of the pip installed package, and `tokenizers` will show up with channel `pypi`

If you really require a conda package (you probably don't), you will find more information in the [conda docs](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs.html).

**Comment by liuwei1206** [comment]
Hi, I found that use the source code and run setup.py is just ok! Thank you

**Comment by n1t0** [comment]
You can now do `conda install -c huggingface tokenizers`
