### ISSUE TITLE
Difference to Roberta transformers tokenizer

### ISSUE THREAD

**Issue by psinger** [huggingface/tokenizers#240]
Hi all -

I am trying to understand some difference I receive when using transformers RobertaTokenizer vs. ByteLevelBPETokenizer.

```
tokenizer1 = transformers.RobertaTokenizer(
        vocab_file=f"vocab.json", 
        merges_file=f"merges.txt"
)

tokenizer2 = tokenizers.ByteLevelBPETokenizer(
        vocab_file=f"vocab.json", 
        merges_file=f"merges.txt", 
        lowercase=False,
        add_prefix_space=True
    )

s = "  'there"

tokenizer1.encode(s, add_special_tokens=False, add_prefix_space=True)
# [1437, 128, 8585]
# ['Ġ', "Ġ'", 'there']

tokenizer2.encode(s).ids
# [1437, 1437, 75, 10859]
# ['Ġ', 'Ġ', "'t", 'here']
```

There are two spaces at the beginning of the string, followed by an apostrophe. 

Am I using some different settings somehow? Any other explanation? Thanks!

**Comment by n1t0** [comment]
Hi @psinger. This is actually an edge case of the `ByteLevel` as implemented in `tokenizers`. This is happening because the original implementation uses a negative lookahead in the regular expression used to split tokens. In `tokenizers` we decided not to use any negative lookahead and instead post-process the result. This works in all cases except this specific one: two or more spaces, followed by one of `'s|'t|'re|'ve|'m|'ll|'d`.
Unfortunately, I don't see how we could fix this easily, and it seems to be a really rare edge case.
