### ISSUE TITLE
Upgrade bin-package/index.node to node v12.16.3

### ISSUE THREAD

**Issue by micah5** [huggingface/tokenizers#255]
Hi,

I am getting this error using the latest stable version of node (`v12.16.3` ~ `NODE_MODULE_VERSION 76`):
```
Error: The module '/Users/user/git/word-gui/word-gui/node_modules/tokenizers/bin-package/index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 76. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Rebuilding the package does not fix the issue. Does the package need to be recompiled to support node versions > 12.0.0?

**Comment by Pierrci** [comment]
Mmmmm this is strange, I just tried with Node v12.16.3 and it's working correctly for me (as it should be, see https://nodejs.org/en/download/releases/ for the matrix of Node / NODE_MODULE_VERSION versions).

Are you trying to use the lib in an electron project? Electron requires NODE_MODULE_VERSION 76 since version 8, so in this case it could explain your very specific bug.

**Comment by micah5** [comment]
> Mmmmm this is strange, I just tried with Node v12.16.3 and it's working correctly for me (as it should be, see https://nodejs.org/en/download/releases/ for the matrix of Node / NODE_MODULE_VERSION versions).
> 
> Are you trying to use the lib in an electron project? Electron uses NODE_MODULE_VERSION 76 since version 8, so in this case it could explain your very specific bug.

Hi, thanks for the reply.

Yes, I was using electron. I tried to rebuild the package as recommended but it doesn't work, I assume because the binary file in bin-package can't be rebuilt with node-pre-gyp.
