### ISSUE TITLE
Creating a custom pre-tokenizer

### ISSUE THREAD

**Issue by dimkart** [huggingface/tokenizers#269]
Hello, 

I was trying to subclass `PreTokenizer` class from `tokenizers.pre_tokenizers` in order to create my own custom pre-tokenizer for splitting the text at word level, but this doesn't seem to work since I'm getting the following:

```python
TypeError: type 'PreTokenizer' is not an acceptable base type.
```

Any ideas how I can do this? Thanks in advance.

**Comment by n1t0** [comment]
There is an example [here](https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/custom_pre_tokenizer.py) that shows how to build your own `PreTokenizer` in Python. Please note though that this is more like a proof-of-concept for now, and it may also change in the future. For example, it won't work with `encode_batch` (because of the multi-threading).

**Comment by dimkart** [comment]
Thanks for the reply. It seems trying to use a custom pre-tokenizer as in the example but for **training** a BPE model does not work, I assume that might be because training also uses multi-threading?

**Comment by dimkart** [comment]
On the same issue, is there any other way to pass directly the list of "big" tokens to the training code?

**Comment by n1t0** [comment]
Yes, you are right, it doesn't work because the training also uses multi-threading.

I don't understand what your mean with "big" tokens, can you elaborate?

**Comment by dimkart** [comment]
@n1t0 I just mean the tokens at the word level, the output of the pre-tokenizer; is there an alternative way to feed them at the train method directly, bypassing the pre-tokenizer mechanism? For the moment I have to pre-tokenize everything with my custom pre-tokenizer, re-assemble the tokens into sentences with whitespace as delimiter, and then train on this new input by using your WhiteSpace pretokenizer. It would be great if all this workaround could be avoided somehow and everything could be done in one step.

**Comment by BinhMinhs10** [comment]
![Screenshot from 2020-08-04 10-03-43](https://user-images.githubusercontent.com/22696815/89248402-e0219a80-d639-11ea-976e-d7df976e3ae8.png)
i have issue when run file example/custom_pre_tokenizer.py

**Comment by lsypl** [comment]
@n1t0 hi, any plan to support jieba as one of the pre-tokenizer, as it is quite used in chinese language nlp.

**Comment by RXminuS** [comment]
Also looking into making a custom pre-tokenizer but in Rust. Seems that the problem lies in the `PreTokenizerWrapper` which has a hard set of options and is goes into `with_pre_tokenizer`. In my case it would have been enough if the `re` in the Whitespace tokenizer was customizable since I only want to make a small modification there, but that's unrelated to this issue.

**Comment by lw00245** [comment]
i want to use bert masked language model to pre train for chinese sentence, i have alweady splited chinese sentence into meaninful word, the data file like follows:

我 是 一个 队员
他 不是 一个 合格 的 老师
......

i only want to use whitespace split them, but BertWordPieceTokenizer will split them to character level , the final vocabulary like follows:
{'[SEP]': 3,
'一': 7,
'是': 15,
'员': 12,
'[CLS]': 2,
'[UNK]': 1,
'': 6,
'[MASK]': 4,
'': 5,
'队': 19,
'的': 17,
'不': 8,
'我': 14,
'他': 10,
'老': 18,
'[PAD]': 0,
'格': 16,
'个': 9,
'师': 13,
'合': 11}
how to correct it ?

**Comment by Narsil** [comment]
Your vocabulary seems very small, did you try setting a larger vocabulary size ?
Tokenizers need first characters as a starting point before merges (therefore larger tokens) can appear.

If that does not solve it, do you mind sharing a toy example ? It could be a lot of things, file encoding, invisible spaces between your characters, or a specific setting.

**Comment by n1t0** [comment]
If you want to avoid the BertWordPieceTokenizer to split on characters, you can initialize it with `handle_chinese_chars=False`.

**Comment by tshauck** [comment]
Going back to the OP's point -- is there a way to do this?

For example, there doesn't seem to be a way to a) subclass the `PreTokenizer` so the pretokenizer is the right type or b) merely set `tokenizer.pre_tokenizer = MyClassThatImplementsPreTokenize`.

**Comment by hdvvip** [comment]
> There is an example [here](https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/custom_pre_tokenizer.py) that shows how to build your own `PreTokenizer` in Python. Please note though that this is more like a proof-of-concept for now, and it may also change in the future. For example, it won't work with `encode_batch` (because of the multi-threading).

Hi,
Thank you for the answer!
Could you double-check the link?
I think the link is dead.

**Comment by david-waterworth** [comment]
@tshauck I think the intention is to do this:

`tokenizer.pre_tokenizer = PreTokenizer.custom(MyClassThatImplementsPreTokenize()) `

See the response to my issue https://github.com/huggingface/tokenizers/issues/466

But then I still run into the issue that the trainer doesn't work, I guess because of the multithreading.

**Comment by n1t0** [comment]
Please see [this file](https://github.com/huggingface/tokenizers/blob/b24a2fc/bindings/python/examples/custom_components.py) for examples of custom components, using tokenizers v0.9 release (Python bindings only).

The `os.environ["TOKENIZERS_PARALLELISM"] = "false"` is necessary because of a bug (cf #470). Starting from `0.9.3` it won't be necessary anymore.
