### ISSUE TITLE
ByteLevelBPETokenizer drops umlaute

### ISSUE THREAD

**Issue by KappaDistributive** [huggingface/tokenizers#278]
ByteLevelBPETokenizer seems to ignore all umlaute. It doesn't raise an exception either -- just silently ignores them and tokenizes the remaining text.

Is this intentional?

Code:

```python
import json
import pathlib

import tokenizers
# Create dummy vocab and merges files to build tokeniser from 
with open('vocab.json', 'w') as f:
    json.dump({'A': 0, 'ä': 1, 'Aä': 2}, f)

with open('merges.txt', 'w') as f:
    f.write('#version 1\nA ä')

bpe_tokeniser_from_files = tokenizers.ByteLevelBPETokenizer(
    vocab_file='vocab.json',
    merges_file='merges.txt'
)

print(bpe_tokeniser_from_files.encode("Aä").ids)
```

Expected Result:
`[2]`

Actual Result:
`[0]`

Related: #164

**Comment by n1t0** [comment]
Hi @KappaDistributive. You cannot really create a dummy vocabulary like this for the byte-level BPE. The input starts by being converted into byte-level characters, and so the `ä` most likely gets encoded into something else. If you try with `CharBPETokenizer` instead of `ByteLevelBPETokenizer`, I guess it should work as you expected.

(cf https://github.com/huggingface/tokenizers/issues/203 for a quick explanation on how the byte-level works)

**Comment by KappaDistributive** [comment]
Oh, my bad. Thanks for the clarification!
