### ISSUE TITLE
Exception raised while trying to encode List[List[str]] with ElectraTokenizerFast

### ISSUE THREAD

**Issue by setu4993** [huggingface/tokenizers#294]
Seeing an unexpected issue being raised when trying to batch encode input of the type `List[List[str]]`.

Example:
```python
from transformers import ElectraTokenizerFast
fast_tokenizer = ElectraTokenizerFast.from_pretrained("google/electra-small-discriminator")
fast_tokenizer.batch_encode_plus([["this is", "a test"], ["this is", "another test"]])
```

Running this raises the exception:
`Exception: Input must be a list[str] or list[(str, str)]`

Replacing the inner list with a tuple works, but this was an unexpected error, since `List[List[str]]` gets encoded fine with the normal tokenizer.
```python
from transformers import ElectraTokenizer
tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-discriminator')
tokenizer.batch_encode_plus([["this is", "a test"], ["this is", "another test"]])
```

To make matters more weird, initializing the normal tokenizer with `use_fast` does not raise the same exception:
```python
from transformers import ElectraTokenizerFast
fast_tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-discriminator', use_fast=True)
fast_tokenizer.batch_encode_plus([["this is", "a test"], ["this is", "another test"]])
```

**Comment by LysandreJik** [comment]
The ELECTRA tokenizer directly overrides the BERT tokenizer, so that is probably also an issue with the BERT tokenizer.

**Comment by LysandreJik** [comment]
@mfuntowicz, what do you think we should do here?

**Comment by n1t0** [comment]
Yes, this happens with all the fast tokenizers because we don't support `List[str]` for sequence pairs, only `Tuple[str, str]`.

The reason we don't support this is that it allows us to have a very clear way to recursively parse the input, both for raw strings and when already pre-tokenized. Otherwise, it becomes ambiguous whether we are trying to get a pre-tokenized sequence, or a pair of sequences. Is there a reason for you that makes it difficult to use a `Tuple` for a pair of sequences?

By the way, this is also the contract that we declared in `transformers` (cf [here](https://github.com/huggingface/transformers/blob/12d0eb5f3e52e43b12b7592a2fdb1d31a50245ea/src/transformers/tokenization_utils.py#L67-L70)), but indeed it happens to be working with the full Python tokenizers, because `Tuple` and `List` share the same interface. (But it forces us to do things [like this](https://github.com/huggingface/transformers/blob/12d0eb5f3e52e43b12b7592a2fdb1d31a50245ea/src/transformers/tokenization_utils.py#L1791-L1795))

**Comment by n1t0** [comment]
> To make matters more weird, initializing the normal tokenizer with `use_fast` does not raise the same exception:
```python
from transformers import ElectraTokenizerFast
fast_tokenizer = ElectraTokenizer.from_pretrained('google/electra-small-discriminator', use_fast=True)
fast_tokenizer.batch_encode_plus([["this is", "a test"], ["this is", "another test"]])
```

I'm not sure about this, but I don't think you can use a "non-fast" class and initialize is with `use_fast=True`. I think you will still get a python tokenizer by doing this. Can you confirm @LysandreJik?

**Comment by LysandreJik** [comment]
Thanks for the explanation @n1t0!

I believe that the `use_fast` flag only works for the `AutoTokenizer` class, not for model-specific tokenizers like `BertTokenizer` or `ElectraTokenizer`.

**Comment by setu4993** [comment]
Thanks @n1t0 and @LysandreJik! Makes sense that this is the intended way to use it. Maybe this is documented somewhere and I missed it. Only brought it up because I assumed the Python and Rust tokenizers were at feature-parity and this seemed like a miss.

Also, re: `use_fast=True`, I checked the `is_fast` attribute and that wasn't set. So, the tokenizer initialized to the Python tokenizer and silently ignored `use_fast`, which led to my incorrect assumption that it was using the Rust tokenizer.
