### ISSUE TITLE
 add_special_tokens does not work with ByteLevelBPETokenizer (RoBERTa)

### ISSUE THREAD

**Issue by dsanyal** [huggingface/tokenizers#295]
Hi,

When I call the `encode` method with an object of the `ByteLevelBPETokenizer` class, the `add_special_tokens` flag  does not work (does not add the special tokens) even when it is set to True. But while using `BertWordPieceTokenizer` it works as expected.

Example:
```
tokenizer = tokenizers.ByteLevelBPETokenizer(vocab_file=ROBERTA_PATH+'vocab-roberta-base.json', 
                                             merges_file=ROBERTA_PATH+'merges-roberta-base.txt', 
                                             lowercase=True,add_prefix_space=True)
    
text = "hello there"
enc = tokenizer.encode(text, add_special_tokens = True) 
enc.tokens
```
The output is:
`['Ġhello', 'Ġthere']`

**Comment by n1t0** [comment]
Yes, the reason is that the `ByteLevelBPETokenizer` is a generic version of a byte-level BPE tokenizer. It is not customized for a specific model like `BertWordPieceTokenizer`, so it doesn't know anything about special tokens.
I can see from your example that you want to add the special tokens for a RoBERTa model, so you can build your tokenizer like this:
```python
from tokenizers import Tokenizer, pre_tokenizers, normalizers, decoders, models, processors

tokenizer = Tokenizer(models.BPE(
  vocab=ROBERTA_PATH+'vocab-roberta-base.json', 
  merges=ROBERTA_PATH+'merges-roberta-base.txt'
))
tokenizer.normalizer = normalizers.Lowercase()
tokenizer.pre_tokenizer = pre_tokenizers.ByteLevel(add_prefix_space=True)
tokenizer.decoder = decoders.ByteLevel()
tokenizer.post_processor = processors.RobertaProcessing(
  sep=("</s>", tokenizer.token_to_id("</s>")),
  cls=("<s>", tokenizer.token_to_id("<s>")),
)
```

Also, if you install the last dev version `0.8.0.dev2`, you can use the new serialization capabilities:
```python
tokenizer.save("roberta.tokenizer.json")
```
And then using it in the future will just require
```python
tokenizer = Tokenizer.from_file("roberta.tokenizer.json")
```

**Comment by dsanyal** [comment]
Thanks for the clarification @n1t0 .
The new capabilities look cool!
