### ISSUE TITLE
Some rough edges with add_tokens

### ISSUE THREAD

**Issue by thomwolf** [huggingface/tokenizers#302]
Here are some rough edges I identified when comparing with the python-based tokenizers in `transformers`. Maybe you would want to fix them?

- **Lower-casing**: adding not-lower-case tokens to the vocabulary with `add_tokens` when `do_lower_case` is `True` means these tokens won't be recognized later as they are stored without being lower-cased. Also, if we store them lower-cased then we don't recognize upper cased token that are identical <= I found no work-around for this issue in `transformers`.
- **Adding several identical tokens**: currently giving a list of identical tokens will add all of them instead of adding just a single token.
- **Adding tokens with spaces**: at the moment I don't think we can add tokens with spaces inside them.

**Comment by n1t0** [comment]
> - **Lower-casing**: adding not-lower-case tokens to the vocabulary with `add_tokens` when `do_lower_case` is `True` means these tokens won't be recognized later as they are stored without being lower-cased. Also, if we store them lower-cased then we don't recognize upper cased token that are identical <= I found no work-around for this issue in `transformers`.

```python
tokenizer = ByteLevelBPETokenizer(
    "../../data/roberta-base-vocab.json",
    "../../data/roberta-base-merges.txt",
    lowercase=True,
)

tokenizer.add_tokens([ "[PAD]", "[UNK]" ])
print(tokenizer.encode("I saw a [UNK] yesterday [PAD]").tokens)

# outputs
['i', 'Ġsaw', 'Ġa', 'Ġ', '[UNK]', 'Ġyesterday', 'Ġ', '[PAD]'] 
```
For me, since tokens lowercased are different from their non-lowercased counterparts, and usually tokenizers who deal with cased input end up having tokens for both, I think this is the right behavior. It let's the users add the tokens they want, and both cases should work whatever the options on `lowercasing` downstream in the pipeline. Did I miss something?

> - **Adding several identical tokens**: currently giving a list of identical tokens will add all of them instead of adding just a single token.

```python
tokenizer = ByteLevelBPETokenizer(
    "../../data/roberta-base-vocab.json",
    "../../data/roberta-base-merges.txt",
)

prev_vocab_size = tokenizer.get_vocab_size(True)
added = tokenizer.add_tokens([ "[PAD]", "[PAD]", "[PAD]", "[PAD]" ])

# outputs
Added 4 tokens
Vocab size when from 50265 to 50266
```
It added only 1 token, but the output from `add_tokens` is wrong! Will fix this.

> - **Adding tokens with spaces**: at the moment I don't think we can add tokens with spaces inside them.

```python
tokenizer = ByteLevelBPETokenizer(
    "../../data/roberta-base-vocab.json",
    "../../data/roberta-base-merges.txt",
)

tokenizer.add_tokens([ "[PA D]", "[U NK]" ])
print(tokenizer.encode("I saw a [U NK] yesterday [PA D]").tokens)

# outputs
['i', 'Ġsaw', 'Ġa', 'Ġ', '[U NK]', 'Ġyesterday', 'Ġ', '[PA D]'] 
```
It seems to work, did I miss something?

**Comment by n1t0** [comment]
Adding more precision on the use-cases that fail:
> - **Lower-casing**: adding not-lower-case tokens to the vocabulary with `add_tokens` when `do_lower_case` is `True` means these tokens won't be recognized later as they are stored without being lower-cased. Also, if we store them lower-cased then we don't recognize upper cased token that are identical <= I found no work-around for this issue in `transformers`.

If we add a lower-cased token, but then we try to encode it while it contains uppercase characters, we won't detect the added token because the check happens before normalization (ie, before it actually gets lowercased). So, this won't work:
```python
tokenizer.add_tokens([ "yesterday" ])
print(tokenizer.encode("I saw a rabbit Yesterday").tokens)
```

> - **Adding tokens with spaces**: at the moment I don't think we can add tokens with spaces inside them.

It is not possible to decode byte-level that contains added tokens with spaces insides. This is due to the fact that the space character is not part of the byte-level alphabet.
