### ISSUE TITLE
CharBPETokenizer.save() json misses first argument of add_tokens; unk token null

### ISSUE THREAD

**Issue by timothyjlaurent** [huggingface/tokenizers#320]
I'm really excited about the new 0.8.0 features.

I'm training a custom tokenizer and have 2 tokens to add, `<NUMBER>` and `<GENE>`. When i try to add them with 

```python
tokenizer.add_tokens(list(MASK_TOKENS))
```
and then look at the model output from `tokenizer.save_model` I see that I'm missing the first added token in the saved json file. 

If I add a sacrificial token, I can get it to show up
```python
    tokenizer.add_tokens(["throw-away", *MASK_TOKENS])
```

```json
  "added_tokens": [
    {
      "id": 0,
      "special": true,
      "content": "<unk>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": false
    },
    {
      "id": 1,
      "special": false,
      "content": "<NUMBER>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": true
    },
    {
      "id": 2,
      "special": false,
      "content": "<GENE>",
      "single_word": false,
      "lstrip": false,
      "rstrip": false,
      "normalized": true
    }
  ]
```

also note that the unk token is in this list despite it already being in the vocab, and 

```
  "model": {
    "type": "BPE",
    "dropout": null,
    "unk_token": null,
```
unk_token is null on the model

**Comment by n1t0** [comment]
Hi @timothyjlaurent. I just tried to reproduce what you described, and unfortunately, I was not able to. All the tokens I give to the method `add_tokens` do appear in the saved json file. Would you mind providing an example (maybe using a Colab?) that let me reproduce it?

Otherwise, the `unk_token` you see under `model` corresponds to the `unk_token` you give to the BPE model when you initialize it. You may want to use `<MY_SUPER_CUSTOM_UNK_TOKEN>` from your vocabulary, but BPE cannot guess it, so you have to tell it which token to use as UNK token:
https://github.com/huggingface/tokenizers/blob/69ed81e618c446f9dc271684fb04157ad45e46de/bindings/python/tokenizers/models/__init__.pyi#L74-L114

**Comment by timothyjlaurent** [comment]
@n1t0 Thanks for the explanation, that's how I expected it to work.

I made a colab with some failing assertions that can show you what I'm talking about :

https://colab.research.google.com/drive/1ff2BxI_sO91zlfR56pkp4Te3mKdYH5X7?usp=sharing

```python
# Download some text
!! wget https://www.gutenberg.org/files/11/11.txt

from tokenizers import CharBPETokenizer, AddedToken

MASK_TOKENS = ["<NUM>", "<GENE>"]

UNK_TOKEN = "<unk>"

tokens_to_add = [AddedToken(mask_token, single_word=True) for mask_token in MASK_TOKENS]


training_files = ["./11.txt"]

char_bpe_tokenizer = CharBPETokenizer(
    unk_token="<unk>",
    unicode_normalizer="nfkc",
    lowercase=True
)

num_added = char_bpe_tokenizer.add_tokens(tokens_to_add)

assert num_added == 2

char_bpe_tokenizer.train(
    training_files,
    vocab_size=5000,
    min_frequency=2,
    show_progress=True
)

model_fn = "./char_bpe.json"

char_bpe_tokenizer.save(model_fn, True)

# load model config from the json

from pathlib import Path
import json

saved_data = json.load(Path(model_fn).open())

from pprint import pprint
pprint({k: v for k, v in saved_data['model'].items() if k not in ['vocab', 'merges']})

assert saved_data['model']['unk_token'] == UNK_TOKEN

# saved_data['model']['unk_token'] is None !! but I initialized the char_bpe with "<unk>"

assert UNK_TOKEN in added_tokens_contents
for token in MASK_TOKENS:
  assert token in added_tokens_contents, f"{token} should be in added tokens" 

# "<NUM>" isn't in added tokens
```

**Comment by timothyjlaurent** [comment]
To mitigate the issue of currently being unable to serialize the tokenizer with `.save`, load it and get the same results, a thin wrapper class suffices.

This class takes the merges and vocab files and adds the special tokens in its `__init__` method.

**Comment by timothyjlaurent** [comment]
I see the 0.8.1-rc-1 has some work with AddedToken serializer. I tried this version but the behavior I noted above is still happening.

**Comment by n1t0** [comment]
Ok I see, there are a few different things at play here, and unfortunately, I won't be able to provide you with a perfect solution for now.

You can easily fix the part about added tokens by providing them to the `train` method, so that they are added to the initial vocabulary. 
The ability to `add_tokens` and `add_special_tokens` is there to provide a way to add tokens on top of an existing vocabulary, for example when you want to fine-tune an existing model, and need to add new tokens to its tokenizer.

As per the missing `<unk>` token in the saved file, this is due to a known bug that we didn't get a chance to fix yet (cf #201). The easiest way to get around it, for now, would be to edit the file manually to provide the said token.

**Comment by timothyjlaurent** [comment]
OK I added the tokens to the train method -- 

```
char_bpe_tokenizer.train(
    training_files,
    vocab_size=5000,
    min_frequency=2,
    show_progress=True,
    special_tokens=["unk"] + ["<NUM>", "<GENE>"]
)
```

These tokens show up as :

```json
  "added_tokens": [
    {
      "id": 0,
      "special": true,
      "content": "<NUM>",
      "single_word": true,
      "lstrip": false,
      "rstrip": false,
      "normalized": false
    },
    {
      "id": 1,
      "special": true,
      "content": "<GENE>",
      "single_word": true,
      "lstrip": false,
      "rstrip": false,
      "normalized": false
    }
  ],
```

So it's still missing one of the added tokens, <unk> and the added tokens are marked as "special" which means that they won't be included in decoded, encodings, which isn't what we want.

I think it's important to be able to specify vocab strings that aren't special, especially in the age of unsupervised word piece algorithms. 

Consider a subword entity that you want to identify -- we have cases where for example the span, "matgm" refers to 2 entities, "mat" - short for "maternal", and "gm" short for "grandmother". If we use a bpe vocab, we might have a token that crosses the boundary between these entities, making it impossible for a model to distinguish them. By adding in custom tokens, you can be assured that the split is maintained.

**Comment by timothyjlaurent** [comment]
I think that my usecase will be solved but subclassing using a 'fast' version subclassing from PretrainedTokenizerBase from Transformer library -- I'll close this.

**Comment by n1t0** [comment]
I'm sorry, I have been head down on some other things, and didn't take the time to update you on this.

You are right, we must be able to add "non-special" tokens to the vocabulary. At the moment we only support doing it on top of a trained vocabulary though, not before even training it. I think to achieve what you want to do, at the moment you would have to:
 - Train your BPE, and then call `.save_model` to save the vocabulary.
 - Load it back with all the right arguments, and call `add_tokens` to add your additional tokens
 - Finally save it using `.save`, so that everything is right in the JSON.

I'll reopen to keep track of the things that need to get modified, as you pointed out a few things don't work as expected:
 - You shouldn't be able to call `add_token` or `add_special_tokens` before training the tokenizer. These provide a way to add some additional vocabulary, and it should only be possible when the model (BPE here) is trained.
 - Some options given during initialization expect a trained model too, and they don't get forwarded as necessary when we call `train`.

**Comment by n1t0** [comment]
The second point being tracked here was related to #201 and has since been fixed. As for the first point, it is being tracked in #523
