### ISSUE TITLE
Different behaviors of tokenizer

### ISSUE THREAD

**Issue by kushalj001** [huggingface/tokenizers#339]
I am fine-tuning a DistilBERT for some downstream tasks. While preparing the data, I came across this weird behavior of the tokenizer `__call__` function and the `convert_tokens_to_ids` functions. 
When I use `convert_tokens_to_ids` function on an individual token, it returns an index of 1 i.e. the `[UNK]` token as shown below:  
  
![image](https://user-images.githubusercontent.com/32245327/87246095-91cd1180-c468-11ea-97e5-841f04e51146.png)

However, when I use the tokenizer's `__call__` method, it subtly changes the words and returns some indices as shown below  

![image](https://user-images.githubusercontent.com/32245327/87246102-9e516a00-c468-11ea-9ccb-01869c6b7623.png)

Is this behavior documented somewhere or specific to my language model? This is the Hindi language.
Thank you.

**Comment by n1t0** [comment]
`convert_tokens_to_ids` just converts the tokens to their respective ids as stated by its name. If you give it tokens that are not part of the vocabulary, then you will get an unknown token. When you use the `__call__` now you actually tokenize, so it will do it's job and find the relevant tokens.

If the tokens happen to be different, this may be due to some normalization step. I can't really know since you didn't share any information about your tokenizer but I expect it to be linked to a `do_lower_case=True` or something of the sort.

**Comment by n1t0** [comment]
Closing this issue as I think it answered your questions. Feel free to reopen if it's not the case!
