### ISSUE TITLE
Please confirm expected behaviour of replacement parameter in SentencePiece tokenizer and clarification for Unigram implementation.

### ISSUE THREAD

**Issue by jaingaurav3** [huggingface/tokenizers#345]
Dear Team,

I am using tokenizer version: '0.8.1.rc1' and trained a Sentence Piece tokenizer from scratch on my custom data.
```
# Instantiate the tokenizer with unk token and replacement
tokenizer_sp = SentencePieceBPETokenizer(unk_token="<unk>", replacement = "▁")
# train the tokenizer with special tokens. Content.txt is english text.
tokenizer_sp.train(["content.txt"], special_tokens = ["<unk>", "[CLS]", "[SEP]", "<s>", "</s>"])
# encode the unknown
tokenizer_sp.encode("どうやって").ids
output here is: [95]
# decode the ids
tokenizer_sp.id_to_token(95)
output is: '▁'
# token to id for unknown token.
tokenizer_sp.token_to_id("どうやって")
Output: Nothing
```
My understanding is when a token is not present in vocabulary then it will be replaced by <unk> token but here the text is replaced by replacement parameter value. Is this the expected behaviour?

Apart from this I've few more queries:
1. Any way to implement Sentence Piece with Unigram instead of BPE? if not, is it the pipeline to release that feature?

Please let me know if any information required from my end.

Regards
Gaurav

**Comment by n1t0** [comment]
Hi @jaingaurav3. Sorry for the time it took to give you an answer.

The bad news is, I'm not able to reproduce your issue. Would you be able to provide a notebook/collab showcasing this bug?

The good news is, with the latest version of `tokenizers` you can now build a similar tokenizer using `Unigram` instead of `BPE`. You can check `SentencePieceUnigramTokenizer` for more information!

Cheers.

**Comment by jaingaurav3** [comment]
Thanks @n1t0 , Glad to know unigram implementation is available now! I'll give it a try.
