### ISSUE TITLE
Tokenization with GPT2TokenizerFast not doing parallel tokenization

### ISSUE THREAD

**Issue by moinnadeem** [huggingface/tokenizers#358]
Hey!

Great work on this library as a whole!

I am doing tokenization using tokenizer.batch_encode_plus with a fast tokenizer using Tokenizers 0.8.1rc1 and Transformers 3.0.2. However, while running batch_encode_plus, it seems as if it is doing single-threaded tokenization, while I thought the Rust implementation would be parallelized. Is this true, or is there something I have to do to enable parallelization?

This is on GridOS 18.04 on a Intel Xeon 6248 processor.

Thanks!

**Comment by Narsil** [comment]
Hello,

It should be parallel by default, but you can turn it off with the environment variable "TOKENIZERS_PARALLELISM=0" (https://github.com/huggingface/tokenizers/blob/fcc68f27f6b0efab5b4cd0c61faa97ef2c7f3568/tokenizers/src/utils/parallelism.rs). 

Could you have added it somewhere in your script ?
It is due to DataLoader parallelism which clashes with the tokenizer parallelism and can lead to dead locks (more info here: https://github.com/huggingface/tokenizers/issues/187)


In order to test, I ran with the same versions as you the following script

```python
import transformers

tokenizer = transformers.BertTokenizerFast.from_pretrained("bert-base-uncased")

while True:
    tokenizer.batch_encode_plus(["I love apples", "I eat carrots"])
```
