### ISSUE TITLE
Tokenizers with custom tokens file use first word as padding

### ISSUE THREAD

**Issue by JestemAnia** [huggingface/tokenizers#397]
I used my own file with english vocabs, but for some reason it uses first word from this file as padding token:

> tokenizer = BertWordPieceTokenizer(os.path.join(data_path, "EN_VOCABS"), lowercase=True)
> tokenizer.enable_truncation(max_length=10)
> tokenizer.enable_padding(length=10)
> 
> tokenizer.encode("My name is Ania").ids
>   ->[20068, 18, 200, 10, 9057, 20067, 0, 0, 0, 0]

The first word is "the", so after decoding I receive "[CLS] my name is ania [SEP] the the the the", because  `tokenizer.id_to_token(0)` returns "the". What's more,  `tokenizer.encode("My name is Ania").tokens` returns ['[CLS]', 'my', 'name', 'is',  'ania', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]'].

**Comment by n1t0** [comment]
Hi @JestemAnia. This is happening because you need to customize the padding if the default values don't fit your use-case (cf [doc for `enable_padding` here]( https://github.com/huggingface/tokenizers/blob/504d8c8/bindings/python/py_src/tokenizers/__init__.pyi#L416-L449)).
You will most likely want to customize values for `pad_token_id` and `pad_token`
