### ISSUE TITLE
[BUG ] contiguous multi byte characters are collapsed on BertTokenizerFast

### ISSUE THREAD

**Issue by talolard** [huggingface/tokenizers#404]
Hi, 
Not sure if this is a bug in transformers or the bert tokenizer algo itself. 
## What I expect
If I use the gpt2 tokenizer I get what I want
```python
from transformers import BertTokenizerFast,GPT2TokenizerFast
tokenizer = GPT2TokenizerFast.from_pretrained('gpt2',)


for i in range(1,5):
    txt = "💩"*i
    enc = tokenizer(txt,return_offsets_mapping=True)
    token_at_i = enc.char_to_token(i-1)
    dec = tokenizer.decode(enc['input_ids'])
    
    print (f" I wrote {txt} but got back '{dec}' and char_to_tokens({i-1}) returned {token_at_i}")
```
```
 I wrote 💩 but got back '💩' and char_to_tokens(0) returned 0
 I wrote 💩💩 but got back '💩💩' and char_to_tokens(1) returned 3
 I wrote 💩💩💩 but got back '💩💩💩' and char_to_tokens(2) returned 6
 I wrote 💩💩💩💩 but got back '💩💩💩💩' and char_to_tokens(3) returned 9
```
## Whats not working
If I use the Bert Tokenizer, contiguous multi byte characters are collapsed. 
I think the tokenizers library is mishandling multi byte Unicode characters. 
I ran the following test
```python
from transformers import BertTokenizerFast
tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased',)

for i in range(1,5):
    txt = "💩"*i
    enc = tokenizer(txt,return_offsets_mapping=True)
    token_at_i = enc.char_to_token(i-1)
    dec = tokenizer.decode(enc['input_ids'])
    
    print (f" I wrote {txt} but got back '{dec}' and char_to_tokens({i-1}) returned {token_at_i}")
```
And got back
```
 I wrote 💩 but got back '[CLS] [UNK] [SEP]' and char_to_tokens(0) returned 1
 I wrote 💩💩 but got back '[CLS] [UNK] [SEP]' and char_to_tokens(1) returned 1
 I wrote 💩💩💩 but got back '[CLS] [UNK] [SEP]' and char_to_tokens(2) returned 1
 I wrote 💩💩💩💩 but got back '[CLS] [UNK] [SEP]' and char_to_tokens(3) returned 1

```

The big problem is that this makes char_to_tokens unreliable for any alignment work

**Comment by n1t0** [comment]
I'm not sure to understand what the bug is.

The BERT tokenizer sees all these inputs as a single word since there is no whitespace to separate them. Inside its vocabulary, it has no word corresponding to these inputs, so for each of them it just ends up being `[UNK]`. Finally, it adds the special tokens, so the `[UNK]` ends up being the token number 1 (`[CLS]` => 0, and `[SEP]` => 2). So from my understanding, it is absolutely correct that you get `1` for each of your calls to `char_to_tokens`, isn't it?
You can also check and print the offsets directly. For the last example `💩💩💩💩`, you will obtain `[(0, 0), (0, 4), (0, 0)]` which confirms what I'm saying: the token `[UNK]` corresponds to the entire input, the 4 characters. Does it make sense?

**Comment by talolard** [comment]
Yes that makes perfect sense. 
No bug here, sorry to trouble you
