### ISSUE TITLE
Tokenizer Cannot Encode String

### ISSUE THREAD

**Issue by antmarakis** [huggingface/tokenizers#408]
Hi!

I am encountering a bizarre issue. I am training a tokenizer, and then when I give it a word to encode, it just outputs a single [UNK] token. When, though, I split the string manually, the tokenizer outputs the correct tokens.

```
from tokenizers import BertWordPieceTokenizer
tokenizer = BertWordPieceTokenizer('trained_tokenizer/vocab.txt')

tokenizer.encode('Texas').tokens
>>> ['[CLS]', '[UNK]', '[SEP]']

tokenizer.encode('Te xas').tokens
>>> ['[CLS]', 'te', 'x', '##a', '##s', '[SEP]']
```

Is this the intended behaviour? I assumed that the tokenizer would only return UNK when there is no possible encoding. But here this is clearly not the case. Have I misunderstood something? Thanks!

**Comment by n1t0** [comment]
Hi! Yes, this is the intended behavior.

Your vocabulary probably doesn't contain the token `##x` which would be needed here to construct `Texas`, given the tokens it outputs when encoding `Te xas`.

When you split it manually, the output really corresponds to `Te xas` and not `Texas`. As you can see, the token `x` doesn't have the `##` at the beginning which means it is _inside a word_, and not _starting a word_. You can check this by trying to decode it:
```python
tokenizer.decode(['te', 'x', '##a', '##s']) 
>>> te xas
tokenizer.decode(['te', '##x', '##a', '##s'])
>>> texas
```

You can either try to increase the vocabulary size, so that your tokenizer has the opportunity to learn more words, or you can try using a `ByteLevelBPETokenizer` instead (as used in `GPT-2`, and probably `GPT-3` too). One big advantage of this one, is that it is impossible to get an `[UNK]` token. The output looks weird because it encodes at the byte-level (as opposed to characters), but it works great.
