### ISSUE TITLE
Bug with added_tokens in Unigram

### ISSUE THREAD

**Issue by Narsil** [huggingface/tokenizers#425]
```python
                new_toks = ["[ABC]", "[DEF]"]
                tokenizer.add_tokens(new_toks)
                input = "[ABC] [DEF] [ABC] [DEF]"
                encoded = tokenizer.encode(input, add_special_tokens=False)
                print(encoded)
                decoded = tokenizer.decode(encoded)
>               self.assertEqual(decoded, input)
E               AssertionError: '[ABC][DEF][ABC][DEF]' != '[ABC] [DEF] [ABC] [DEF]'
E               - [ABC][DEF][ABC][DEF]
E               + [ABC] [DEF] [ABC] [DEF]
E               ?      +     +     +
``

**Comment by n1t0** [comment]
As discussed with @thomwolf and @Narsil, this is a #wontfix. 

The problem described in this issue is that it might not be possible to `decode` back to the original input with destructive tokenizers. For example, when using a tokenizer that removes whitespace, when the information is not encoded in the various tokens in the vocabulary (ie one token with the space, one without it), it is impossible to know whether to add spaces or not while decoding from IDs only. So, there is no way to fix this exact use-case without worsening some others.
