### ISSUE TITLE
Need help interpreting the training args definitions 

### ISSUE THREAD

**Issue by Santosh-Gupta** [huggingface/tokenizers#471]
I am looking at the training args for the wordpiece trainer, and I'm trying to figure out what some of the args means

https://github.com/huggingface/tokenizers/blob/master/bindings/python/py_src/tokenizers/trainers/__init__.pyi#L82

```
            min_frequency: unsigned int:
                The minimum frequency a pair should have in order to be merged.
```

What is 'pair' referring to? It sort of sounds like the minimum amount of times a word or subtoken needs to appear before being included in the vocab list. Say that 'biology' appears frequently in the training text, but also other words that start with 'bio' (biomedical, bioscience, biometrics, biophysics, etc.); does this term play a factor if 'bio' is defined as a token vs 'biology' being defined as a token? 

```
            limit_alphabet: unsigned int:
                The maximum different characters to keep in the alphabet.
```

I was a little confused about the difference between alphabet and vocab initially, but it seems like alphabet is referring to all possible text characters that can tokenized. So if a period is not in the alphabet, the character would be ignored, eg ['The', 'cat', 'ate', 'The', 'cat', 'left'] vs ['The', 'cat', 'ate', '.', 'The', 'cat', 'left'].

**Comment by n1t0** [comment]
> min_frequency: unsigned int:

This option specifies how many times we should see a pair of tokens before we can create a new token out of them. So for example if we have the tokens `bio` and `logy`, and `min_frequency=5`, then the word `biology` would have to appear at least 5 times in the training corpus for these tokens to be merged together and `biology` added to the vocabulary.

> limit_alphabet: unsigned int:

Yes this is indeed the set of tokens formed by a single character. Since there are more than 130,000 different Unicode characters, it might be necessary to limit the initial alphabet to let the tokenizer figure out larger tokens.
