### ISSUE TITLE
Saving/loading tokenizers with save_model causes them to mishandle special tokens

### ISSUE THREAD

**Issue by Mindful** [huggingface/tokenizers#472]
I am new to `tokenizers`, so I apologize if this is rooted in a mistake on my part that. However, it looks very much like a bug. I've confirmed this behavior extends to at least SentencePieceBPETokenizer and ByteLevelBPETokenizer; I haven't tested any other tokenizers.

I tried this on `0.8.1rc2` (the version my `transformers` install depended on) and `0.9.2` and got the same results. 

A minimal recreation of the issue looks like this:

```
from tokenizers import SentencePieceBPETokenizer

test_string = '🤗 is<SEP> great!'
special_tokens = ['<SEP>']

with open('test.txt', 'w') as f:
    f.write(test_string)

tok = SentencePieceBPETokenizer()
tok.train(
    files='test.txt',
    special_tokens=special_tokens,
    min_frequency=2
)
first_encode = tok.encode(test_string)
tok = SentencePieceBPETokenizer(*tok.save_model('.', 'test'))
second_encode = tok.encode(test_string)
print(first_encode.tokens, second_encode.tokens, sep='\n')
```

Which gives me:

```
> ['▁', '🤗', '▁', 'i', 's', '<SEP>', '▁', 'g', 'r', 'e', 'a', 't', '!']
> ['▁', '🤗', '▁', 'i', 's', '<', 'S', 'E', 'P', '>', '▁', 'g', 'r', 'e', 'a', 't', '!']
```

The issue is that saving and loading a tokenizer appears to cause it to forget its special tokens and start splitting them up. Note however that if you re-add special tokens after loading the tokenizer, things appear to work fine.

```
tok.add_special_tokens(special_tokens)
third_encode = tok.encode(test_string)
print(third_encode.tokens)
print(first_encode.tokens == third_encode.tokens)
```

The above gives me:

```
> ['▁', '🤗', '▁', 'i', 's', '<SEP>', '▁', 'g', 'r', 'e', 'a', 't', '!']
> True
```

*Edit:* So I realized that if I use save() instead of save_model() and then load the tokenizer back with from_file() everything seems to work fine. This certainly solves the problem for me, but I will leave the issue open because I think it's potentially confusing.

**Comment by n1t0** [comment]
Hi @Mindful and thank you for reporting this.

You are right, the way to go is to use `save` instead of `save_model`. Saving the model is meant to provide  compatibility with some other libraries, and some legacy support, but it then doesn't give full support for all the additional features of this library. A lot of information is missing from the standard models files, and only the `Tokenizer.save` method saves the whole tokenizer.

I'm curious, what made you use `save_model` over `save`?

**Comment by Mindful** [comment]
@n1t0 

That all makes sense - thanks!

> I'm curious, what made you use save_model over save?

I had a lot of trouble finding documentation/an example of training a tokenizer from scratch, saving it, and then loading it. The thing I stumbled on was this blog post https://huggingface.co/blog/how-to-train about training models including tokenizers, and it used save_model.

**Comment by n1t0** [comment]
Thank you @Mindful! We should definitely update this blog post to make sure we use the latest API!

We are currently adding the documentation for this project, you can find it here: https://huggingface.co/docs/tokenizers

**Comment by fatihbeyhan** [comment]
This issue still exist (at least for `ByteLevelBPETokenizer`). There is an example script available [here](https://github.com/huggingface/tokenizers/blob/main/bindings/python/examples/train_bytelevel_bpe.py). However, if one goes and run this script, they will have their special tokens split into characters. Yes, you can use `Tokenizer.save` method instead of the `Tokenizer.save_model` method, but then `ByteLevelBPETokenizer.from_file` method fails since it expects separate `vocab.json` and `merges.txt` files. Any other way to load this tokenizer model?

**Comment by ashutoshsaboo** [comment]
+1 I'm facing something similar as what @fatihbeyhan reported in the above comment. Were you able to resolve it eventually - @fatihbeyhan ?

**Comment by fatihbeyhan** [comment]
Hi @ashutoshsaboo! Yes, but not in a clean way I suppose :) You can use `Tokenizer.save` method to save a single file that has the whole tokenizer configuration, then when you want to use this model you can use the `Tokenizer` class and it's `from_str` method.

```
...
model = ByteLevelBPETokenizer(...)
model.train(...)

model.save("mytokenizer", ...)

with open("mytokenizer") as f:
    same_model = Tokenizer.from_str(f.read())
```
Something like above should work!

**Comment by ashutoshsaboo** [comment]
Thanks @fatihbeyhan for getting back , i realised on diving deep my issue was related to something else.
