### ISSUE TITLE
Can't convert '永和' to NormalizedString

### ISSUE THREAD

**Issue by ismymajia** [huggingface/tokenizers#487]
when i run https://github.com/huggingface/tokenizers/blob/master/bindings/python/examples/custom_components.py, error occurs:

Exception: Exception: TypeError: Can't convert '永和' to NormalizedString

@n1t0

**Comment by n1t0** [comment]
What version of the library are you using? I'm able to run this just fine with the latest release.

**Comment by ismymajia** [comment]
I update tokenizers   to  0.9.3, but error still occurs.

I track the code and cannot find the code where it needs to convert str to NormalizedString. 
the code https://github.com/huggingface/tokenizers/blob/2364d376f7c1ccfe14389d71a1308e40635c0af3/bindings/python/examples/custom_components.py#L71
 jump to https://github.com/huggingface/tokenizers/blob/2364d376f7c1ccfe14389d71a1308e40635c0af3/bindings/python/py_src/tokenizers/pre_tokenizers/__init__.pyi#L16

**Comment by n1t0** [comment]
Can you provide more information, like a backtrack, the code or commands you are running, etc.

**Comment by ismymajia** [comment]
Thanks! I try again and it's ok.
Because  i modify JiebaPreTokenizer class, it is the change problem between str and NormalizedString.

**Comment by n1t0** [comment]
Ok then I guess the problem you encountered, was that you were returning a `str` instead of a `NormalizedString` in `jieba_split`. You need to return a `NormalizedString` here because that's the internal class we use to track the alignment. You can find the documentation for the `NormalizedString`, and the `PreTokenizedString` classes in this file: https://github.com/huggingface/tokenizers/blob/master/bindings/python/py_src/tokenizers/__init__.pyi

Let us know if we can help! You can close this issue if everything is good for you 🙂
