### ISSUE TITLE
Adding new token for fast tokenizer not working

### ISSUE THREAD

**Issue by suggestedUsername** [huggingface/tokenizers#507]
I am using Huggingface BERT for an NLP task. My texts contain names of companies which are split up into subwords.

```
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')
tokenizer.encode_plus("Somespecialcompany")
output: {'input_ids': [101, 2070, 13102, 8586, 4818, 9006, 9739, 2100, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
```

Now I would like to add those names to the tokenizer IDs so they are not split up.

```
tokenizer.add_tokens("Somespecialcompany")
output: 1
```

This extends the lenght of the tokenizer from 30522 to 30523.

The desired output would therefore be the new ID:

```
tokenizer.encode_plus("Somespecialcompany")
output: 30522
```

But the output is the same as before:

```
output: {'input_ids': [101, 2070, 13102, 8586, 4818, 9006, 9739, 2100, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
```

According to the [reply on my question on stackoverflow](https://stackoverflow.com/questions/64669365/huggingface-bert-tokenizer-add-new-token) it works fine for the slow tokenizer. But I haven't bee able to test this myself yet.

**Comment by Narsil** [comment]
This is a `transformers` code you are using here. I did the effort of digging the example down here:

```python
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

# Now this is a `tokenizers` object
tokenizer = tokenizer._tokenizer

tokenizer.encode("Somespecialcompany").ids
# [101, 2070, 13102, 8586, 4818, 9006, 9739, 2100, 102]

tokenizer.add_tokens(["Somespecialcompany"])
# 1

tokenizer.encode("Somespecialcompany").ids
# [101, 2070, 13102, 8586, 4818, 9006, 9739, 2100, 102]

### However
tokenizer.add_special_tokens(["Somespecialcompany"])
tokenizer.encode("Somespecialcompany").ids
# [101, 30522, 102]
```

Do you know that 

```python
tokenizer.add_tokens("Somespecialcompany", special_tokens=True)
```
will work ?

**Comment by suggestedUsername** [comment]
Ahh alright I see. No I didnt know that it works like that. Thank you so much for the fast reply.

**Comment by cronoik** [comment]
@Narsil and @suggestedUsername :+1: 

`Somespecialcompany` is just a normal token and not a special token like [CLS] or [SEP]. I am actually not sure if this is an issue for `tokenizers` or for `transformers`, but let me explain what I think is the issue here for the `tokenizers`:
```
from tokenizers import BertWordPieceTokenizer  
t = BertWordPieceTokenizer.from_file(vocab="thisismytest/vocab.txt")  
string2encode = 'Somespecialcompany'  
print(len(t.encode(string2encode).ids))  
#completely pointless
t.add_tokens([string2encode])  
print(len(t.encode(string2encode).ids))  
#not pointless when we add the token lowercased
t.add_tokens([string2encode.lower()])
print(len(t.encode(string2encode).ids))
```
Output:
```
9
9
3
```
As you can see in this small example, the tokenizer processes all words as lower case strings. This is correct in my opinion since it is the [default setting](https://github.com/huggingface/tokenizers/blob/558f2d87795ffc9d9786f1e923398e3eebe14187/bindings/python/py_src/tokenizers/implementations/bert_wordpiece.py#L25), but the tokenizer lets me add mixed case tokens with `add_tokens()` which will never be used. Should not the strings that are added with `add_tokens()` also be converted to lower case when the attribute `lowercase` is set to true? Otherwise, these added tokens are completely pointless, or do I miss something? 

When I look at the `transformers` implementation, I see the expected beheaviour for their BertTokenizer (this example shows also the `tokenizers` `BertWordPieceTokenizer` which is wrapped into `BertTokenizerFast`):
```
from transformers import BertTokenizer, BertTokenizerFast
t = BertTokenizer.from_pretrained('bert-base-uncased')
ft = BertTokenizerFast.from_pretrained('bert-base-uncased')
string2encode = 'Somespecialcompany'
print(len(t.tokenize(string2encode)))
print(len(ft.tokenize(string2encode)))
t.add_tokens(string2encode)
ft.add_tokens(string2encode)
print(len(t.tokenize(string2encode)))
print(len(ft.tokenize(string2encode)))
```
Output:
```
7
7
1
7
```

**Comment by cronoik** [comment]
@mfuntowicz
Could you please have a look?

**Comment by shiningliang** [comment]
Same error. 
When I add some phrases to the **fast tokenizer** as _additional_special_tokens_, some of them can't be recognized as a special token when encoding. And I didn't find the pattern.

**Comment by shiningliang** [comment]
Same question.
For example, I add ["arrive_time", "arrive_time_location"] to the additional_special_tokens. But the "arrive_time_location" still will be tokenized into ["arrive_time", "_", "location"]. 
I think it's because the first one is the sub-string of the second one and it's a characteristic of fast tokenizer. Is there any option to prevent this?

**Comment by miguelwon** [comment]
I'm having the same issue:

```
>>> from transformers import BertTokenizer
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
>>> num_added_toks = tokenizer.add_tokens(['new_tok1', 'my_new-tok2'])
>>> 'new_tok1' in tokenizer.vocab.keys()
False
```

Also, the same related issue, where the is adds the new tokens but does not save when saving the tokenizer locally:

```
>>> from transformers import AutoTokenizer
>>> model_name = "neuralmind/bert-base-portuguese-cased"
>>> tokenizer = AutoTokenizer.from_pretrained(model_name)
>>> num_added_toks = tokenizer.add_tokens(['new_tok1', 'my_new-tok2'])
>>> 'new_tok1' in tokenizer.vocab.keys()
True
>>> tokenizer.save_pretrained("./tokenizer")
('./tokenizer/tokenizer_config.json',
 './tokenizer/special_tokens_map.json',
 './tokenizer/vocab.txt',
 './tokenizer/added_tokens.json',
 './tokenizer/tokenizer.json')
>>> with open('tokenizer/vocab.txt') as f:
    vocac = [v.strip() for v in f]
>>> 'new_tok1' in vocab
False
>>> 'test' in vocab
True
```

**Comment by cronoik** [comment]
@miguelwon your issue is about `transformers tokenizer` and not about tokenizers. Please open an issue [there](https://github.com/huggingface/transformers).
