### ISSUE TITLE
How to get both the vocabulary.json and the merges.txt file when saving a BPE tokenizer

### ISSUE THREAD

**Issue by manueltonneau** [huggingface/tokenizers#521]
Hi all,

I've been trying to generate an encoder.json and vocab.bpe for GPT-2 encoding. I have read the related issues (#361 and related) but I haven't found anywhere the right way to save the tokenizer and get two files (`vocab.json` and `merges.txt`) and not just one json.

I tried `tokenizer.save("byte-level-bpe.tokenizer.json", pretty=True)` but this is just saving one json (by the way, what does the argument pretty stand for?). I also tried with `tokenizer.save(directory=output_dir)` and `tokenizer.save(args.out, args.name)` but both failed. 

Please let me know the right way to go. Thanks in advance!

**Comment by n1t0** [comment]
`tokenizer.save` let's you save the entire `Tokenizer` (with truncation/padding settings, the various components like Normalizer, PreTokenizer, ...) instead of *just* the vocab. It gives you a single JSON file that will let you load the entire tokenizer with a single line of code:
```python
tokenizer = Tokenizer.from_file("byte-level-bpe.tokenizer.json)
```
The `pretty` argument just specifies whether the JSON file should be pretty formated, letting you easily inspect it if you want to.

If you want to save the vocab only (`vocab.json` + `merges.txt` in the case of BPE), then you'll have to do:
```python
tokenizer.model.save(output_dir)
```

**Comment by kitkhai** [comment]
Hi @n1t0 

I get the error
`AttributeError: 'NllbTokenizerFast' object has no attribute 'model'
`
Is there a corresponding method for fast tokenizers?

**Comment by ArthurZucker** [comment]
This might be outdated, you should use `tokenizer._tokenizer.model` if you are working on a `NllbTokenizerFast`

**Comment by kitkhai** [comment]
Hi @ArthurZucker 
Thanks! That works! But is there an equivalent method for slow tokenizers?

**Comment by ArthurZucker** [comment]
For a slow simply fo `tokenizer.save_vocabulary(save_directory)`
