### ISSUE TITLE
Access to the `merges` object  from Python

### ISSUE THREAD

**Issue by esceptico** [huggingface/tokenizers#535]
We currently have access to the vocab object as `tokenizer.get_vocab()`. When I try to reinitialize my BPE model from memory, I need to provide both `vocab` and` merges` objects. But as I can see now, there is no access to the `merges` object from Python.

Сurrent workaround is extracting `merges` from the` tokenizer.as_str ()` via `json.loads`, or saving the` merges.txt` (and `vocab.json`) and reload via `BPE.read_files()`

**Comment by tarcey** [comment]
I second this.

I don't have access to the workaround because merges.txt is bust as soon as it's saved, due to issue https://github.com/huggingface/tokenizers/issues/645. Spaces and other whitespace in my vocabulary are sadly not optional.

I see no easy way to save and load a trained BPE encoder if the vocab has spaces.
