### ISSUE TITLE
train_from_iterator not available

### ISSUE THREAD

**Issue by hengdashi** [huggingface/tokenizers#548]
Hi,

Thank you so much for this amazing library! I have python binding version 0.9.4 installed with pip and tried to use train_from_iterator to train a custom tokenizer with the datasets package.

However, even though this function is documented in 0.9.4, it is not available in the source code. I'm wondering how long would it take to release the new version so that I can update the package and use this function?

**Comment by n1t0** [comment]
Thanks for pointing out that this is documented in `0.9.4`. This shouldn't be happening and this is actually a bug in our docs deployment process. (Opened an issue to track it here https://github.com/huggingface/tokenizers/issues/550)

We will release the `0.10rc1` version shortly so that you can start using all of the new features.

**Comment by n1t0** [comment]
You can try `0.10.0rc1` and access these features! I hope you'll enjoy it, and let us know if you find anything odd!
