### ISSUE TITLE
How to change the pad token ?

### ISSUE THREAD

**Issue by Jeevesh8** [huggingface/tokenizers#571]
Basically, I want to know how to assign the actual roles that the ```special_tokens``` specified in a ```Trainer``` are meant for? I know how to do this for ```<unk>``` ,where we just pass it to the model we are using, for e.g. ```BPE(unk_token='<unk>')``` . But how to do this for pad etc. ? The library uses the ```[PAD]``` token by default but I want to use ```<pad>``` , which I have specified in ```special_tokens``` argument in ```Trainer```. Couldn't find how to do this in docs.. And help is apprecited.

Yours gratefully
Jeevesh Juneja

**Comment by Jeevesh8** [comment]
I even tried ```pad_id=self.tokenizer.token_to_id('<pad>')``` in ```tokeniser.enable_padding()``` functions.

**Comment by n1t0** [comment]
Hi @Jeevesh8

You are using the right method to let the tokenizer know about the pad token.
I think in your case, maybe you are calling `tokenizer.token_to_id` before actually training the tokenizer, which happens to return `None` because the token doesn't exist yet.
If you call it after training, then it should work as expected.

If I'm mistaken, please provide a small snippet of code letting us reproduce it so that we can better help you.

**Comment by Jeevesh8** [comment]
Yes, it worked.. thanks a lot. Hope huggingface keeps blessing us with such good repos.
