### ISSUE TITLE
How to slice a BatchEncoding object into desired batch sizes?

### ISSUE THREAD

**Issue by davidlee321** [huggingface/tokenizers#577]
Hello community. Got a seemingly simple question but can't find the answer after google searching, a cursory read of the docs, and searching this repository's issues.

How can I do slice a BatchEncoding object into desired batch sizes?

That is, I'd like to:

```python
from transformers import *

tokenizer = tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = TFBertModel.from_pretrained('bert-base-cased')

batch_size = 32

texts = ["Hello, my dog is cute", "cats are cool.", "elephants are big hey.", ... ]
tokens = tokenizer(texts, return_tensors="tf")

outs = []
for batch in tokens.batch(batch_size):    # Pseudocode. how to slice into batches?
  out = model(batch)
  outs.append(out)
outs = outs.combine()               # Pseudocode. How to combine outputs of batches into a single TFBaseModelOutputWithPooling object?
```

**Comment by n1t0** [comment]
The `BatchEncoding` actually already represents a batch. You should just call the tokenizer with batches of `texts` of the right size, and feed the model with the output of the tokenizer. Something along the lines of:
```python
for i in range(0, len(texts), batch_size):
        tokens = tokenizer(texts[i:i+batch_size], return_tensors="tf")
        out = model(tokens)
```

I won't be able to help you combine the output though. For questions like this, you should definitely post on the [:hugs: Forum](https://discuss.huggingface.co) where it will be easier to get an answer from the community. Issues on Github are reserved for bugs and feature requests.

**Comment by git-siddhesh** [comment]
Hi developer,
I am facing a similar kind of problem.

Due to limited amount of gpu memory, I can not just just load entire tokenized data to the gpu.

So I need some way implementing following algorithm

1. tokenize entire data, returning pytorch tensors, on cpu
2. create batches of tokenized data
3. load the batches to gpu
4. evaluate the batch on metric
5. remove the data from gpu

Please, help me out.
Thank you for your time.

`batch_size = 10
 prompts = self.tokenizer(self.data, return_tensors="pt",truncation=True, padding=True, max_length=50 ).to(self.device)
 for i in range(0, len(self.data), batch_size):
     torch.cuda.empty_cache()
     print("Batch number:", i)
     predictions = self.get_prediction(prompts)`
