### ISSUE TITLE
Is train_from_iterator available for SentencePieceBPETokenizer?

### ISSUE THREAD

**Issue by AliOskooeiTR** [huggingface/tokenizers#578]
My training files are very large and the normal train doesn't seem to be able to handle them. Now hoping to use the train_from_iterator but I noticed it is not available for SentencePieceBPETokenizer. I tried to build a Tokenizer from a Model I built from SentencePieceBPETokenizer  so that I can make it work but did not manage as it is not possible to set the vocab_size, min_frequency and other args.  Any help/guidance would be appreciated.

**Comment by n1t0** [comment]
This method was indeed missing from the various implementations and will be added in #583 

That being said, I don't think it will change anything related to the resources needed to train. So if the training does not work because of an Out-of-Memory error or something similar, it won't be any different.
