### ISSUE TITLE
Exception: Error while initializing BPE: Merges text file invalid at line ... - have non-printable char (\n)

### ISSUE THREAD

**Issue by keotic** [huggingface/tokenizers#588]
Training a SentencePieceBPETokenizer generates a merge file which can't be loaded, and throws an exception:

Exception: Error while initializing BPE: Merges text file invalid at line 468

The issue does not happen on version 0.8.1, encountered the problem when upgrading from 0.8.1 to 0.9.4

input file is attached.

Train params:
tokenizer.train(files=[input_file], vocab_size=50000, min_frequency=2, show_progress=True, special_tokens=["pad", "unk", "/s", "s"])

[vocab_tmp_1610215215.724457.txt.zip](https://github.com/huggingface/tokenizers/files/5791641/vocab_tmp_1610215215.724457.txt.zip)

**Comment by n1t0** [comment]
Hi @keotic 

This is happening because there are `\n` characters in the dataset used to train, and the tokenizer learns to merge these characters. Unfortunately, the current format for `merges.txt` does not support having merge operations with `\n` as one of the tokens, and it results in the error you mentioned.

You could either:
 - Save your tokenizer in a single `.json` file after training it, and then start using `Tokenizer` directly instead of the `SentencePieceBPETokenizer` class:
```python
from tokenizers import SentencePieceBPETokenizer, Tokenizer

# train and save
tokenizer = SentencePieceBPETokenizer()
tokenizer.train(files=files, vocab_size=50000, ...)
tokenizer.save("my-tokenizer.json")

# reload it
tokenizer = Tokenizer.from_file("my-tokenizer.json")
```
 - Update the tokenizer somehow, to normalize the input text and remove any `\n` or replace them with a single space ` ` for example. This will ensure the resulting `merges.txt` doesn't end up being invalid.

**Comment by keotic** [comment]
@n1t0 Thank you for the elaborated reply.

I have added a BertNormalizer with the 'clean_text' flag in the following manner:
 
 bert_normalizer = BertNormalizer(clean_text=True,
                                         handle_chinese_chars=False,
                                         lowercase=lower)

tokenizer.normalizer = normalizers.Sequence([bert_normalizer, normalizers.NFKC()])

according to the documentation it should
"removing any control characters and replacing all whitespaces by the classic one"

but the problem persists.

Is there a bug in the normalizer or am I am doing something wrong?

**Comment by n1t0** [comment]
The `normalizer` property is not exposed on `SentencePieceBPETokenizer` so you should set it with:
```python
tokenizer._tokenizer.normalizer = ...
```
