### ISSUE TITLE
"!" and "!<\w" in vocab but "!" never used 

### ISSUE THREAD

**Issue by mannefedov** [huggingface/tokenizers#605]
I guess this is not a bug, but I couldn't figure out what is the purpose of this.

I trained CharBPETokenizer on a small corpus like this
```python
from tokenizers import CharBPETokenizer, Tokenizer
tok_sub = CharBPETokenizer()
tok_sub.train('corpus.txt', vocab_size=2000, min_frequency=10, )
```

There are two vocab items that contain "!" and two items that contain "2"
```python
[(x, y) for x,y in tok_sub.get_vocab().items() if '!' in x]
[('!</w>', 1197), ('!', 1)]
```
```python
[(x, y) for x,y in tok_sub.get_vocab().items() if '2' in x]
[('2</w>', 814), ('2', 17)]
```

For "2" both items are used in different contexts
```python
print(tok_sub.encode("2").ids)
print(tok_sub.encode("21").ids)
print(tok_sub.encode("2  2a a2 a2a").ids)
[814]
[17, 809]
[814, 17, 807, 35, 814, 35, 17, 807]
```

But it seems that "!" (which maps to id 1) is never used
```python
print(tok_sub.encode("!").ids)
print(tok_sub.encode("!?").ids)
print(tok_sub.encode("!!!! ! !a a! a!a").ids)
[1197]
[1197, 1277]
[1197, 1197, 1197, 1197, 1197, 1197, 807, 807, 1197, 807, 1197, 807]
```

I tried encoding all the lines in the corpus.txt and never got id 1 
```python
unique_ids = set()

for text in open('corpus.txt'):
    unique_ids.update(tok_sub.encode(text).ids)

print(1 in unique_ids, 1197 in unique_ids)
False True
```

It also seems to be the same for other punctuation characters.  

Could you please clarify why it happens? Doesn't it mean that the actual size of vocab is less than value passed to vocab_size in .train()? Could that potentially affect the performance?

**Comment by Narsil** [comment]
This is because `CharBPETokenizer` actually uses `BertPreTokenizer`:

https://huggingface.co/docs/tokenizers/python/latest/api/reference.html#tokenizers.pre_tokenizers.BertPreTokenizer

Which means every punctuation is pre-splitted into different tokens. which means only 1197 will be used.
That's the default way of Bert tokenizing, but you can easily change you `pre_tokenizing` needs:

Either `CharBPETokenizer(split_on_whitespace_only=True)`, or even building you own Tokenizer based on CharBPETokenizer.

https://github.com/huggingface/tokenizers/blob/fc0a50a272c3fad4ae2f07b4a5bd84e106d1e266/bindings/python/py_src/tokenizers/implementations/char_level_bpe.py#L79

It does not really affect global vocab_size, because for BPE algorithm, all `chars` are needed in the base vocabulary anyway, because larger tokens exist only by "merging" two subtokens (the smallest ones are the `chars`)

Feel free to reopen if that did not answer your question.
