### ISSUE TITLE
Comparison with YouTokenToMe

### ISSUE THREAD

**Issue by yutkin** [huggingface/tokenizers#66]
Are there any comparisons or benchmarks with [YouTokenToMe](https://github.com/VKCOM/YouTokenToMe)?

**Comment by epwalsh** [comment]
@yutkin impressive results with YouTokenToMe! As far as I know we haven't compared them yet, but I'd be interested to see the results. So far training of BPE / WordPiece is single threaded though.

Actually we've had several discussions about how to improve our benchmarking. Currently we only have some micro-benchmarks for the pure Rust lib to check for regressions when we're making changes, but it's been on the road map to add a library-level comparison script like ya'll have done for YouTokenToMe.

**Comment by prateekrastogi** [comment]
Thanks for ravishing implementation details. It would suffice my use-case. 🥉

**Comment by Oktai15** [comment]
@epwalsh, you can check our benchmark with yours here: https://github.com/VKCOM/YouTokenToMe/blob/master/benchmark.md

**Comment by UpwardTrajectory** [comment]
Cool to see some time comparisons, and I appreciate that YouTokenToMe being a C++ wrapper means it basically just works on every machine. I do feel like for production environments, it's only a fair comparison if you're doing C++  vs huggingface(rust) rather than huggingface(python) though. 
  
P.S. this "Issue" is what first introduced me to YouTokenToMe, so that's some good advertising :-D
