### ISSUE TITLE
Wordpiece Tokenizer only outputs "[UNK]" token

### ISSUE THREAD

**Issue by jafioti** [huggingface/tokenizers#662]
I am trying to use the Wordpiece tokenizer in rust, and I believe I am properly loading the vocab, but it only outputs a single "[UNK]"  token. Here is the code I use to load the tokenizer:
```
let wordpiece_builder = WordPiece::builder();
let lines: Vec<&str> = include_str!("../resources/wordpiece_vocab.txt").split("\n").collect();
let mut hashmap: HashMap<String, u32> = HashMap::new();
for (i, line) in lines.iter().enumerate() {
    hashmap.insert(line.to_string(), i as u32);
}
let wordpiece_builder = wordpiece_builder.vocab(hashmap);
let wordpiece = wordpiece_builder
    .build().expect("WordPiece Tokenizer failed to build!");
let tokenizer = Tokenizer::new(wordpiece);
```

I'm sure there is a better way to do this rather than build a hashmap manually, but for now this is where I'm at.
Here is the code I use to tokenize and convert to tokens:
```
// Tokenize
let encodings = tokenizer.encode_batch(strings, false).expect("WordPiece tokenization failed!");
// Convert back to strings
let mut tokens: Vec<Vec<String>> = Vec::with_capacity(encodings.len());
for encoding in encodings.iter() {
    tokens.push(encoding.get_tokens().to_vec());
}
```

Am I doing something wrong in the loading or tokenization?

**Comment by n1t0** [comment]
You need to specify a pre-tokenizer otherwise it will try to tokenize the entire sentence all at once, and there is no token in the vocabulary that represents the whole sentence. If you try to encode single words it should work without any problem.
You can try by adding a `Whitespace` for example, and I believe it will work when providing sentences.

Also, you should be able to simplify the loading by doing:
```rust
let wordpiece = WordPiece::builder()
    .files(String::from("../resources/wordpiece_vocab.txt"))
    .build().expect("WordPiece Tokenizer failed to build!");
```
