### ISSUE TITLE
Why Rust?

### ISSUE THREAD

**Issue by andyalmonte** [huggingface/tokenizers#67]
Hello team, congrats on this release!

I was wondering how the decision to implement this in Rust came about. Did you consider another language or was this based on skill set already existing on the team. 

Congrats again!

**Comment by epwalsh** [comment]
Thanks @andyalmonte! I can only speak for myself, but I started working with Rust because it's low level with performance on par with C/C++, yet comes with safety guarantees that langs like C/C++, Java, etc don't offer. It also has amazing tooling and documentation, and a great community. I was really excited when I saw huggingface was also taking an interest in Rust :smile:
