### ISSUE TITLE
How to reduce the length of tokenizer?

### ISSUE THREAD

**Issue by LakshmiSravya123** [huggingface/tokenizers#709]
tokenizer = AutoTokenizer.from_pretrained("bert-base-multilingual-cased")
tokenizer.save_pretrained(DATA_DIR).

Hi, I am using the above code and I am getting the vocab.txt and len(tokenizer) for the size of 119548. But I am looking for a 30522 vocab size.  I couldn't find a code where I can specify the vocab size.

Please let me know how can I do it?

**Comment by Narsil** [comment]
You cannot simply override the vocab size, or the model will definitely output bogus output (because it will use tokens in it's full range.

The model you mentionned explicitly uses that many tokens: https://huggingface.co/bert-base-multilingual-cased/blob/main/config.json

Perhaps you should look for another model ?

**Comment by LakshmiSravya123** [comment]
> You cannot simply override the vocab size, or the model will definitely output bogus output (because it will use tokens in it's full range.
> 
> The model you mentionned explicitly uses that many tokens: https://huggingface.co/bert-base-multilingual-cased/blob/main/config.json
> 
> Perhaps you should look for another model ?

thank you, I got now where I did the mistake.

**Comment by Narsil** [comment]
Glad it worked out !
