### ISSUE TITLE
Limiting number of processes

### ISSUE THREAD

**Issue by ArthurCamara** [huggingface/tokenizers#72]
It seems like the code is currently spawning an unbounded number of processes (is that correct?)

It would be really useful if we could limit that somehow. Especially on machines where we need to share with some other people.
Is it possible today?

**Comment by mfuntowicz** [comment]
HI @ArthurCamara, 

You're right, tokenizers is spawning plenty of processes but it should match the number of core/threads of the CPU you have.

_Possible simple solution_: As we use rayon under the hood can you try setting `RAYON_RS_NUM_CPUS` env variable which might limit rayon from spawning more threads than defined.

This is [expected to change](https://docs.rs/rayon/0.7.1/rayon/struct.Configuration.html#method.num_threads) so we may want to provide an alternative in the future.

Can you let us know if setting the env variable works ? So that we can update the documentation.

**Comment by ArthurCamara** [comment]
It seems like setting `RAYON_RS_NUM_CPUS` works. the number of threads is now limited to whatever I set it to.
Thanks!

**Comment by mfuntowicz** [comment]
@ArthurCamara glad it worked, I'm closing this issue, feel free to reopen :)

@n1t0 FYI, I'll update the doc accordingly.
