### ISSUE TITLE
Output is not very good

### ISSUE THREAD

**Issue by tsoernes** [huggingface/tokenizers#731]
Code
```
fn main() -> Result<()> {
    let text: String = fs::read_to_string("/tmp/example_desc.txt")?.parse()?;
    let dir = "/home/torstein/Downloads/";
    let vocab_path = [dir, "gpt2-medium-vocab.json"].concat();
    let merges_path = [dir, "gpt2-merges.txt"].concat();
    let bpe_builder = BPE::from_files(&vocab_path, &merges_path);
    let bpe = bpe_builder.build()?;

    let tokenizer = Tokenizer::new(Box::new(bpe));

    let encoding = tokenizer.encode(EncodeInput::Single(text), false)?;
    println!("{:?}", encoding.get_tokens());

    Ok(())
}
```
Text
```
"\\nPosition Description:  \\nThe qualified candidate will become part of a team of experienced professionals...
```

Output
```
["\"", "\\\\", "n", "Position", "Description", ":", "\\\\", "n", "The", "qualified", "cand", "idate", "will", "bec", "ome", "part", "of", "ate", "am", "of", "exper", "ienced", "prof", "ession", "als",
```
```
Why is `candidate`, `become`, not single words?

**Comment by luozhouyang** [comment]
**BPE** is one of subword tokenization methods

**Comment by tsoernes** [comment]
```
fn main() -> Result<()> {
    let text: String = fs::read_to_string("/tmp/example_desc.txt")?.parse()?;
    let dir = "/home/torstein/Downloads/";
    let vocab_path = [dir, "gpt2-medium-vocab.json"].concat();

    let wp_builder = WordPiece::from_files(&vocab_path);
    let wp = wp_builder.unk_token("[UNK]".into()).build()?;

    let tokenizer = Tokenizer::new(Box::new(wp));

    let encoding = tokenizer.encode(EncodeInput::Single(text), false)?;
    println!("{:?}", encoding.get_tokens());

    Ok(())
}
```
Then running: `Error: MissingUnkToken`

**Comment by n1t0** [comment]
I bet the `[UNK]` token you add in the builder does not exist in the `gpt2-medium-vocab.json`, hence the error saying `MissingUnkToken`. Also if the file you used is named accurately, then you won't be able to use it with WordPiece, because GPT-2 uses a BPE model, coupled with a ByteLevel pre-tokenizer. You could find more info about how to build a Tokenizer for GPT-2 by looking at the official one here: https://huggingface.co/gpt2/tree/main (the `tokenizer.json` file contains all the necessary information).

I would also advise you to read the docs entirely here: https://huggingface.co/docs/tokenizers to better grasp how this library works, and then you can feel free to ask for help on the forums here: https://discuss.huggingface.co

The Github issues are reserved for bugs and feature requests, so I will close this one here.
