### ISSUE TITLE
Error on load sentencepieceunigram?

### ISSUE THREAD

**Issue by darwinharianto** [huggingface/tokenizers#752]
Thank you for the easy to use module and trainer.
I have a bit problem on sentence piece trainer.

For the BPE sentencepiece, seems like there are some letters that arent included inside vocab.json
After i trained it, seems like '私' would not be included, but if I add more '私' (adding this in new line about hundreds times)  in corpus, it seems to be registering that word.
Is there any reason why?

For the unigram sentencepiece one, 
After i tried to train unigram sentence piece, i tried to load the model, it gives this error.
```

tokenizer = SentencePieceUnigramTokenizer(
    "./models/ptech/unigram.json"
)
```
`TypeError: Can't convert '.' to PyTuple`

What should i do about this?

**Comment by Narsil** [comment]
If you want to use `tokenizers` the default way to load is

```python
tokenizer = Tokenizer.from_file('./models/ptech/unigram.json')
```

`SentencePieceUnigramTokenizer` expects a vocab, which is a list of tuples of ("token", score) so that's why it does not work.


For the BPE question, it's hard to tell without more context it's hard to answer. It most likely is correct since, adding it in the corpus enables the letter.

**Comment by darwinharianto** [comment]
seems like SentencePieceUnigramTokenizer doesnt have `from_file` method

I could load it this way

```
with open("./models/ptech/unigram.json") as f:
  vocab = json.load(f)["vocab"]

tokenizer = SentencePieceUnigramTokenizer(vocab)
```

Will I lose information by loading this way?

**Comment by n1t0** [comment]
Yes it doesn't have `from_file` because the way to load it is, like @Narsil stated, by using `Tokenizer.from_file`. The class `SentencePieceUnigramTokenizer` only exist to help you train or import a tokenizer, that you then save in a json file.
To answer your question, yes you will lose all the customization of your tokenizer by loading it this way. It is not recommended.

**Comment by darwinharianto** [comment]
`load_from_file` gives me
```
Exception: expected `,` or `}` at line 2 column 9
```

Is my json a faulty?
