### ISSUE TITLE
How to set Unicode codes as smallest byte representation in BPETrainer?

### ISSUE THREAD

**Issue by fake-warrior8** [huggingface/tokenizers#754]
I found that 'Each Unicode code point is decomposed into bytes (1 byte for ASCII characters, and up to 4 bytes for UTF-8 Unicode code points)' in the following comment link
 https://github.com/huggingface/tokenizers/issues/203#issuecomment-605105611.

However, in my scenario(not NMT scenario), bytes smaller than Unicode code representation are meaningless, what can I do to just set the smallest tokens as Unicode code instead decomposed  bytes from Unicode codes in trainers.BpeTrainer?

**Comment by Narsil** [comment]
You need to not use ByteLevel part of the `pre_tokenizer` and `decoder`. By default, this is exactly what the BPE model will do.
Be mindful that you will *need* a unk token then for everything to work properly, because even though your training data won't contain unk, incoming data might, if you don't want the tokenizer to fail you need to properly set it.



I guess you're not having that issue, but unicode has a lot of values, so depending on your incoming data, beware of large part of the vocabulary being taken up with simple unicode characters.

**Comment by fake-warrior8** [comment]
> You need to not use ByteLevel part of the `pre_tokenizer` and `decoder`. By default, this is exactly what the BPE model will do.
> Be mindful that you will _need_ a unk token then for everything to work properly, because even though your training data won't contain unk, incoming data might, if you don't want the tokenizer to fail you need to properly set it.
> 
> I guess you're not having that issue, but unicode has a lot of values, so depending on your incoming data, beware of large part of the vocabulary being taken up with simple unicode characters.

Thank you, I'll try it.
