### ISSUE TITLE
Add Template post-processor

### ISSUE THREAD

**Issue by mfuntowicz** [huggingface/tokenizers#79]
Roberta tokenizer requires inputs (& pairs) to be wrapped around `<s> ... </s>` (respectively cls and eos tokens).

**Comment by n1t0** [comment]
Instead of adding a PostProcessor specific to Roberta, what about adding a TemplateProcessor that takes a list of tokens, and a template string, some like `[CLS] [A] [SEP] [SEP] [B] [EOS]` where A and B are the two sequences. We would be able to cover most cases with only one easily customizable PostProcessor this way.
