### ISSUE TITLE
ImportError: cannot import name 'auto_class_factory'

### ISSUE THREAD

**Issue by sz-lcw** [huggingface/tokenizers#803]
I upgraded the transformers from v4.5.1 to v4.10.0.
And when I run the code as follow:
`from transformers.models.auto.modeling_auto import auto_class_factory`
 I got the error below:
```
ImportError: cannot import name 'auto_class_factory' from 'transformers.models.auto.modeling_auto' 
(xxxxx/envs/huggingface/lib/python3.7/site-packages/transformers/models/auto/modeling_auto.py)
```
I couldn't find **auto_class_factory** in the source code and documents in v4.10.0.
How can I fixed this problem? Thanks.

**Comment by Narsil** [comment]
Hi @sz-lcw 

Thanks for this issue, but why did you open it here, was there any information linking this to `tokenizers` (this repo) ?
This issue is probably going to be better answered here https://github.com/huggingface/transformers/issues.

As a side note, `auto_class_factory` was most likely removed in favor of a better approach, solution for your code might depend what you are doing with it.

**Comment by sz-lcw** [comment]
> Hi @sz-lcw
> 
> Thanks for this issue, but why did you open it here, was there any information linking this to `tokenizers` (this repo) ?
> This issue is probably going to be better answered here https://github.com/huggingface/transformers/issues.
> 
> As a side note, `auto_class_factory` was most likely removed in favor of a better approach, solution for your code might depend what you are doing with it.

Thanks, I will sent a post a new issuse in **transformers** project.
