### ISSUE TITLE
Support tokenizing more than two sequences

### ISSUE THREAD

**Issue by cemilcengiz** [huggingface/tokenizers#804]
Currently, TemplateProcessing class can only be used in one or two (pair) sequences. However, there are some downstream tasks (especially in conditional text generation) that require processing more than two sequences and handling the special tokens between them. In that case, TemplateProcessing can not be used as post_processor. Can this be implemented in the future, or is there any other way to be able to use a tokenizer in more than two sequences without doing manual post-processing?

**Comment by fcakyon** [comment]
This is a very vital issue in our case too, waiting for the response.

**Comment by fcakyon** [comment]
What is your stance on this @Narsil ?

**Comment by Narsil** [comment]
It's not on the roadmap afaik.

I would require quite a bit of change in the underlying structure of the code to support that

Is there anything wrong with:

```python
ids =[tokenizer.encode(sequence).ids for sequence in sequences]
full_ids = [ids[0]]
for (ids, separator) in (ids, separators):
    full_ids.append(separator)
    full_ids.extend(ids)
```

It's not ideal ofc but it should do the trick and be easy to extend as much as you desire, no ?

**Comment by cemilcengiz** [comment]
> It's not on the roadmap afaik.
> 
> I would require quite a bit of change in the underlying structure of the code to support that
> 
> Is there anything wrong with:
> 
> ```python
> ids =[tokenizer.encode(sequence).ids for sequence in sequences]
> full_ids = [ids[0]]
> for (ids, separator) in (ids, separators):
>     full_ids.append(separator)
>     full_ids.extend(ids)
> ```
> 
> It's not ideal ofc but it should do the trick and be easy to extend as much as you desire, no ?

Thank you for your reply @Narsil . Your suggestion is indeed sufficient for a one time script for data processing, but unfortunately not enough for our needs.
HF tokenizers have extra capabilities including handling the special tokens, returning the type ids and attention mask, handling padding, batch encoding, truncation and more. This is fine, and I would be OK for using the tokenizers without these extra features. In fact, we have developed a full library, [Trapper](https://github.com/obss/trapper), that provides some wrapper classes that use the HF tokenizers to perform basic tokenization and handle the other required steps on their own. However, the problem (for us) is that the tokenizers are central in transformers, and the classes that needs them generally require their extra capabilities as well.  For example, the pipeline classes use the tokenizers extensively and are not open for a clean alternative. This make it very hard for us to reuse our data processing classes that fills the missing gaps by performing the extra steps normally performed by the HF tokenizers. We end up with a lot of duplicate code (almost all of the class) when trying to reuse a pipeline class from transformers. Note that I haven't even talked about the efficiency issues.

I think most of our problems would be solved if the tokenizers supported arbitrary number of sequences for an input as well as arbitrary special tokens. I think this can be done in by extending the Rust implementations of TemplateProcessing class and some change in a couple of files as well. I would even try to implement it myself but haven't done so since I don't have an experience with the language.

**Comment by Narsil** [comment]
You're free to open a PR for this, but unfortunately this won't be just a couple of files. It's not impossible for sure, but it will shift quite a bit of objects since you would be changing `EncodedInput` type, which is used in quite a bit of places.

I don't have the full picture of your library or what you are trying to do but.

1/ Overriding pipelines should be easy to do:

You can always pass your own object like so `pipeline(.... tokenizer=MyTokenizer())`
Should be easy to do since pipelines only call `__call__`  member of tokenizer.
Another option would be to subclass the pipeline but doesn't seem appropriate here.

2/ Handling, type_ids, offset_mapping etc..

Again, I recon it's not ideal, but overriding like I shown in your own wrapper class should be doable.

The best solution is to open a PR here. On our side, we try to keep additions to `tokenizers` minimal and when necessary for adding new models. I am sure putting a detailed use case for a model that could be added to `transformers` because of such a change could gain more momentum.

**Comment by hrdxwandg** [comment]
the issue start  a year ago, is there any updates?

**Comment by Narsil** [comment]
Yes the current `Decoder` actually supports chaining now and there is a `decoders.Sequence`, same with `TemplateProcessor` so there is no roadblock to implement this.

The only thing truly left would be a definite use case where there is a clear definite use case for it.
Having a real use case is super important because it helps creating features that actually serve a real world use case purpose, otherwise it's easy to implement some feature that's not useable.
PRs are welcome.

**Comment by hrdxwandg** [comment]
we can find many use cases. eg
1）in search engine, the relation is key problem.  A is query, B is product title. we want A is related with B or not. But the product title is not enough information. we want to add other info  for example  product brand, product Hierarchical category, ner etc. they are different indepent feature, we do not want to concat them to a single sentence. but belong to indepent segment
2）in chatbot, the dialogue is QAQQAAQ, Q is question， A is answer.  for every single A or Q， we want to have indepent segment, not concat to one single sentence simply.

**Comment by Narsil** [comment]
The docs are here: https://huggingface.co/docs/tokenizers/index

For chatbots, actually, there are many models doing conversation that do not require this feature, and that is here: https://huggingface.co/models?pipeline_tag=conversational&sort=downloads

The actual code depends on the various models, but basically it's up to higher up code to deal with that. And the reason is that's it's actually more complex than just using multiple sequences. For instance blenderbot will keep some *context* tokens, that cannot get truncated and the various inserted tokens between Q and A differ.
Given this context, that's why it wasn't implemented in this lib since the flexibility required would play well with the relatively static APIs provided here (It's always tradeoffs, but Rust is made for performance and it's harder to move code around than in Python, as long a Python is not the botteneck anymore it doesn't really provide a huge perf boost to handle complexity in Python).

For instance: https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/tokenization_gpt2.py#L355

 

And sorry if I wasn't clear, but when I meant real use cases, I meant "This code and model are doing this, and it's currently not supported so we need to support it". And probably also a little idea of why it's required in this library and cannot be done in Python ( performance could definitely be an argument).

I am basically solo maintaining this library which does work and should keep working, but undertaking massive changes just for the sake of it is not something I am willing to do at this time. So when opportunity was there for real world use cases that needed modifications, we took this issue into account to design the code, but we still don't have a real world model that really requires this as of now.

**Comment by hrdxwandg** [comment]
I see what you mean. Thank you for your patient reply @Narsil
