### ISSUE TITLE
Recommended way to use tokenizers in Pytorch module

### ISSUE THREAD

**Issue by aleSuglia** [huggingface/tokenizers#810]
Hi there,

I have a Pytorch module that generates text. During training I alternate between a training and validation loop. At validation time, I use the model to generate text given a reference. Then, I convert the generated ids to text using `batch_decode()`. Unfortunately, it looks like the model hangs in this situation. My guess is that is due to the tokenizers parallelism. Of course, I could disable it but then my data loader will likely slow down. Is there any way to fix this without sacrificing speed?

Thanks,
Alessandro

**Comment by Narsil** [comment]
Measure it, it's actually unlikely you're data loader will slow down.

If both `tokenizers` and `DataLoader` are using threads to speed up, it's likely they just compete for ressources so could slow down instead of speed up. Disabling parallelism for `tokenizers` when using `DataLoader` is probably for the best.

Please make some measurements to confirm this rule of thumb (if it doesn't work, then time=infinite :)).
You could also try removing the parallelism from DataLoader  (num_workers=0) itself but if you're sending to GPU you're likely to slow down because you won't be feeding it as fast as possible

**Comment by Narsil** [comment]
Closing since this is very old, feel free to reopen if problem persists and DataLoader did slow down.
