### ISSUE TITLE
Non-invertible tokenization

### ISSUE THREAD

**Issue by ashkamath** [huggingface/tokenizers#812]
Hello,

I was wondering if the de-tokenization should be guaranteed to invertible in HuggingFace.

Consider the following snippets

```
import transformers
from transformers import RobertaTokenizerFast
tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")

print(transformers.__version__) #4.11.2

# Case where the detokenization is reversible
ids = [42891, 232]
decoded = tokenizer.decode(token_ids=ids)
encoded_ids = tokenizer.encode_plus(decoded)["input_ids"][1:-1] #removes BOS and EOS
assert ids == encoded_ids  # works


# Case where it doesn't work
ids = [15239, 29288,  9812, 24240,  5911, 13115, 16597, 17710, 11376, 17309]
decoded = tokenizer.decode(token_ids=ids)
encoded_ids = tokenizer.encode_plus(decoded)["input_ids"][1:-1]
assert ids == encoded_ids, f"{ids} {decoded_ids}"

#Fails with because decoded_ids [15239, 29288, 229, 5593, 462, 3976, 282, 5911, 48655, 35678, 4349, 17710, 11376, 17309]
# Note that we don't even have len(ids) == len(decoded_ids)
```

In other words, two different inputs of the detokenizer can produce the same output.
Is this expected?
It also means that a given sentence can have several possible tokenizations under this tokenizer. Is there documentation on which one is selected by the encoder? Is it guaranteed to be always the same?

Thanks

**Comment by Narsil** [comment]
Hi,

Tokenization is by nature loosing information, so it's impossible to keep that sort of guarantee.
That being said `tokenizers` library was built with the goal (among others) to get some reversibility somehow.

`tokenizers` will give you

```
(text: str) -> (ids: [int],  offsets: [(int, int)])
```
The reversibility comes from the fact that offsets can tell where an ID is coming from in the original text. It doesn't however guarantee that `decode(ids)` == `text`, because that's simply impossible. So if `decoded(ids) != original_text` then, reencoding will likely give a different set of ids.

Is that a bit clearer ?
Cheers,
Nicolas

**Comment by Narsil** [comment]
Closing for now feel free to reopen.
