### ISSUE TITLE
(Byte-level BPE)decoded output sentence is not same as input sentence

### ISSUE THREAD

**Issue by Kyeongpil** [huggingface/tokenizers#830]
Hi, I'm trying to train the byte-level BPE model.
I tested some sentences but the decoded output sentence is not the same as the input sentence.

For instance, the input sentence is "123 fdsafsfa ~_! ./" but the output sentence is ' 1 2 3 fdsafsfa ~ _ ! . /'.
I don't know why the space is not removed when decoding the output tokens.

Here are my codes:

```
tokenizer = Tokenizer(BPE(dropout=bpe_dropout))
tokenizer.normalizer = NFC()
tokenizer.pre_tokenizer = pre_tokenizers.Sequence(
    [Whitespace(), Digits(individual_digits=False), UnicodeScripts(), ByteLevel(add_prefix_space=True)]
)
tokenizer.post_processor = processors.ByteLevel(trim_offsets=True)
tokenizer.decoder = decoders.ByteLevel()

trainer = BpeTrainer(
    vocab_size=vocab_size,
    min_frequency=min_frequency,
    initial_alphabet=pre_tokenizers.ByteLevel.alphabet(),
    special_tokens=special_tokens,
)
tokenizer.train(corpus_paths, trainer)
```

Do I miss some points? How can I make the decoded sentences the same as the input sentences?

**Comment by Narsil** [comment]
In general you cannot.
Tokenization is a destructive process so you cannot recover input sentences after tokenization.
You can however have a better understanding of what tokens are by checking the `offsets` :

https://huggingface.co/docs/tokenizers/python/latest/quicktour.html?highlight=offsets#using-the-tokenizer

The offsets will allow you to fetch in the original string, what piece of string was used for a particular token.
Parts of the original string might be discarded, but overall you should be able to "reverse" in that case for most intent and purposes.

Another analogy is `string.lower()`, how would you expect the reverse operation to work ? Should all letters become uppercase ? In general it's not possible.

And finally, maybe setting `add_prefix_space` to `False` instead of `True` might yield better results for you (the encode operation still won't be fully reversible, it just might produce results closer to what you want).

**Comment by Kyeongpil** [comment]
@Narsil Thank you for your kind answer. I solved this problem by replacing Digits(individual_digits=True) to Digits(individual_digits=False).
