### ISSUE TITLE
Training the Custom GPT-2 BPE

### ISSUE THREAD

**Issue by cyk1337** [huggingface/tokenizers#835]
Hi, does the tokenizers toolkit support GPT-2 BPE? 

GPT-2 prevents BPE from merging across character categories except spaces for any byte sequence. It seems that there is no such feature in `ByteLevelBPETokenizer()`.  Any solutions to it?

**Comment by Narsil** [comment]
Where did you see that anywhere in the `GPT-2` code ?

AFAIK, gpt-2 didn't have any such capacity.
`sentencepiece` does it by default.

This library has `tokenizers.pre_tokenizers.UnicodeScripts()` that can do it, but is it what you are looking for ?
`UnicodeScripts` was added with `sentencepiece` compatibility in mind ,so it's actually incorrect, since it treats every japanese characters as HAN to allow fusion across those.

https://github.com/huggingface/tokenizers/blob/0fe9214f44f4e117a85e3880c20631cc70298d86/tokenizers/src/pre_tokenizers/unicode_scripts/pre_tokenizer.rs

**Comment by cyk1337** [comment]
GPT-2 paper: "We observed BPE including many versions of common words like dog since they occur in many variations such as dog. dog! dog? . This results in a sub-optimal allocation of limited vocabulary slots and model capacity. To avoid this, we **prevent BPE from merging across character categories for any byte sequence**. We add an exception for spaces which significantly improves the compression efficiency while adding only minimal fragmentation of words across multiple vocab tokens." This feature is what I am looking for.

The `UnicodeScripts()` splits on characters that belong to different language families, but not on various character categories. I am wondering whether such GPT-2 feature is supported.

**Comment by Narsil** [comment]
what are you referring to when you say `character categories`?

**Comment by cyk1337** [comment]
I think it should be different char classes, such as alphabet vs symbol.

**Comment by Narsil** [comment]
I see, this then: https://unicodebook.readthedocs.io/unicode.html#categories ?

I don't think there's anything implemented for that yet for sure. If you were to make a PR it would be welcome I think.

As a pointer this would probably need to be a `pretokenizers` (You can check out `UnicodeScript` or others for reference). If you manage to get the rust stuff going we can help with the bindings afterwards.

**Comment by cyk1337** [comment]
Thank you. Will do afterward.
