### ISSUE TITLE
how to add self-defined special token

### ISSUE THREAD

**Issue by siam1991** [huggingface/tokenizers#838]
hi,

I' reading the paper 《Matching the Blanks: Distributional Similarity for Relation Learning》，and I want to use chinese_roberta_L-12_H-768, I need to add self-defined special token [E1], [/E1], [E2], [/E2]. I modify those files:

special_tokens_maps.json

    {"unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]","e1_start_token": "[E1]","e1_end_token": "[/E1]","e2_start_token": "[E2]","e2_end_token": "[/E2]"}

tokenizer_config.json 

    {"do_lower_case": false, "do_basic_tokenize": true, "never_split": null, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]","e1_start_token": "[E1]","e1_end_token": "[/E1]","e2_start_token": "[E2]","e2_end_token": "[/E2]", "tokenize_chinese_chars": true, "strip_accents": null, "model_max_length": 512}

vocab.txt

    replace [unused1],[unused2],[unused3],[unused4] to [E1],[/E1],[E2],[/E2]

But when I load the tokenizer and use id ,it can return the special token ids as expect ,but could not tokenize the input sentence as expect,here is the example

when I get the special token id

    e1_start_id = tokenizer.convert_tokens_to_ids("[E1]")
    e1_end_id = tokenizer.convert_tokens_to_ids("[/E1]")
    e2_start_id = tokenizer.convert_tokens_to_ids("[E2]")
    e2_end_id = tokenizer.convert_tokens_to_ids("[/E2]")
    print(e1_start_id, e1_end_id, e2_start_id, e2_end_id)
    # 1,2,3,4

input: 

    3号炉平台劳动保护动火作业,[E1]砂轮机切割作业[/E1]时,未佩戴[E2]防护面罩[/E2],人员未系挂安全带

here is the tokenize result:

    ['[CLS]', '3', '号', '炉', '平', '台', '劳', '动', '保', '护', '动', '火', '作', '业', ',', '[', '[UNK]', ']', '砂', '轮', '机', '切', '割', '作', '业', '[', '/', '[UNK]', ']', '时', ',', '未', '佩', '戴', '[', '[UNK]', ']', '防', '护', '面', '罩', '[', '/', '[UNK]', ']', ',', '人', '员', '未', '系', '挂', '安', '全', '带', '[SEP]']

what else can I do?

**Comment by Narsil** [comment]
I think the problem lies from `special_tokens_map.json` and/or `tokenizer_config.json`.

Special tokens are a `transformers` thing, not a `tokenizers` thing (tokenizers tokenizes and that's it, not special meaning of any kind exist for any of the tokens.

So '[E1]' needs to be added to the `added_tokens` part of the tokenizer json:  https://huggingface.co/roberta-base/raw/main/tokenizer.json. Then `special_tokens_map.json` might have to be updated, but you'll have to look up `transformers` source code to check how this map is defined/used.

Also using the utilities functions from `transformers` should do the trick for you  `tokenizer.add_tokens(["[E1]", ....)`.
You can then save the tokenizer to see the output.

Does that answer your question?

**Comment by siam1991** [comment]
thanks for your answer , the key point is add special token to `tokenizer.json`, I also used the `bert-base-chinese`: https://huggingface.co/bert-base-chinese/tree/main before, the tokenizer.json is supplied and I modified this file too. so I could use `bert-base-chinese` as expect, but I don't know why it works. when I use model `chinese_roberta_L-12_H-768`: https://huggingface.co/uer/chinese_roberta_L-12_H-768/tree/main , it not supply the `tokenizer.json` ,now I add this file to the model dir and modify this file , it works. Thank you very much, now I know which file is in action.
