### ISSUE TITLE
FastTokenizer becomes slow when adding new tokens

### ISSUE THREAD

**Issue by AhmedIdr** [huggingface/tokenizers#848]
Hey, 
I'm trying to add a large number of new tokens (20k) to a pretrained tokenizer, but after adding the new tokens the needed time to tokenize the same data jumps from 1 minute to more than 10 hours. 
The new tokens were obtained by using a WordLevelTokenizer. This might be relevant to #615.
To reproduce: https://colab.research.google.com/drive/1PD0roGuH-eKMWrAJLTzd1UtkNBKJxd4R?usp=sharing

**Comment by Narsil** [comment]
This is not that surprising, it is quite uncommon to add such a massive amount of `added_tokens`.

Under the hood, `added_tokens` are fetched with the use of a regexp, which because humongous in your case. And also it causes probably many overlaps (`a` is an added token and `arrival` then `a`, `rrival`, `arrival`, `arriv`, `a`, `l` all need to be considered. This is an exponential process and there's no real way around it.

The current code was added to be in perfect alignment with `transformers` I think, but since then `transformers` uses a Trie (which is less powerful but much faster when the algorithm can be greedy). We could think of doing some modifications here.

However the colab you shared seems like just a proof of concept since you're readding the whole vocabulary. This will likely destroy the real tokenization with a Trie (since it would become greedy only the smallest matches would work for instance).

Do you mind sharing what kind of tokens you are really adding ? Having a real use case will push the need to make those modifications.

**Comment by AhmedIdr** [comment]
Maybe it is also worth mentioning that trying to use slow tokenizer with `use_fast=False` shows that it only needs around 20 minutes but keeps throwing this message `There was a bug in Trie algorithm in tokenization. Attempting to recover. Please report it anyway`.

**Comment by Narsil** [comment]
Or, for the bug in the Trie, do you mind trying to set up a reproducible example ? Seeing that error message is not good.

I can see what you are trying to achieve. I am by no means an expert, but using such a large portion of your vocabulary on unseen data will probably lead to very uneffective fine-tuning (since 50% is effectively being learned from scratch). So it's going to take a while to relearn all those new weights.
Ofc your mileage may vary since it depends how often those new tokens are seen during training.

It is indeed an interesting test case, if you succeed to prove it works with the slow algorithm that's definitely something worth investigating into making it efficient.

If the Python version takes 20mn then you should still expect a bump in execution time compared to the `20mn`. (Probably still much less if we do it properly, but still)

**Comment by AhmedIdr** [comment]
I just used the same notebook as above and set use_fast to False when loading the tokenizer from the pretrained model https://colab.research.google.com/drive/1PD0roGuH-eKMWrAJLTzd1UtkNBKJxd4R?usp=sharing. I get what you mean by saying that almost 50% is being learned from scratch, that's why I am planing to try the method described here https://nlp.stanford.edu/~johnhew/vocab-expansion.html#fnref:1 instead of just initializing the embeddings randomly, which is the default in hf transformers.

**Comment by Narsil** [comment]
Interesting, thanks for the refs !
