### ISSUE TITLE
Question about offsets returned for text starting with a space when using `add_prefix_space=True` and `trim_offsets=True`

### ISSUE THREAD

**Issue by SaulLu** [huggingface/tokenizers#852]
# Question

When creating a tokenizer with `add_prefix_space=True` and `trim_offsets=True` (for example with `ByteLevel` or `RobertaProcessing`), the offsets returned on a text starting with a text are not what I would have expected intuitively. Indeed, assuming that `the` belongs to the vocabulary, the text `text=" the the"` will be encoded in the following way:
- `[tokenizer.id_to_token(id) for id in encoding.ids] = ["Ġthe", "Ġthe"]`
- `encoding.offsets = [(0,4), (5,8)]`
- `[text[offset[0]:offset[1]] for offset in encoding.offsets] = [" the", "the"]`

So we notice that the first space is included in the offsets of the first token.

What do you think about it?

## Additional information

If we had created a tokenizer with `add_prefix_space=False` and `trim_offsets=True` instead, the result would have been:
- `[tokenizer.id_to_token(id) for id in encoding.ids] = ["Ġthe", "Ġthe"]`
- `encoding.offsets = [(1, 4), (5,8)]`
- `[text[offset[0]:offset[1]] for offset in encoding.offsets] = ["the", "the"]`

Note that the first space is not included in the offsets

# Code snippet

I have prepared a [small google colaboratory](https://colab.research.google.com/drive/11Hhq8JlJUOIwo3bG2YNjuhD7owBCQCIb?usp=sharing) which shows the behavior with 2 toy tokenizers (one using `RobertaProcessor` and the other `ByteLevel`).

I would love to hear your opinion on it @Narsil or @n1t0 :relaxed:

**Comment by Narsil** [comment]
I think we can close now, can you confirm ?

**Comment by SaulLu** [comment]
It seems to me that this behavior has not been changed with the new release of the tokenizers library(I juste re-runned the google colab and the outputs still the same).

**Comment by Narsil** [comment]
OK, this is a different problem than the `pretokenized` problem.

Here, you are yourself adding an extra space on a string, AND saying `add_prefix_space=True`. 
The issue is that no state is maintained if the extra space is actually added or not. If you provide it, we don't add it on top (otherwise tokenization is messed up since two spaces is never included in a vocabulary).

So the extra space provided is included in the offsets, whereas if the `PreTokenizer` adds the extra space on it's own, then the offsets DO NOT include the space:

1 -  "the the" -> PRETOK -> " the  the" (notice prepended space) (offsets (0, 3), (3, 7))
2  - " the the" -> PRETOK -> " the the" (same normalization but offsets are different) (offsets (0, 4), (4, 8))

And this is where we are in a pickle since we have two different offsets and no way to know which was prepended or not.

When we `post_process` and `trim_offsets` we see id `5` with offsets `(0, 3)` or id `5` with offsets `(0, 4)` and we have no way to know if the first space is actually ours or not.

Some options we can look into:
- Ignore it and consider it "working as normal". Not ideal, but definitely the easiest for a pretty edge case.
- Add some state into `NormalizedString`. Pretty intensive job, probably a net performance hit.
- Try some hacking workaround with looking into `token` length in addition to `is_first`. This one is likely to bite us later, since normalization can arbitrarily modify everything. It would be the easy "fix".

I think I favor the first option right now. The "pure" fix seems quite a lot of work for an edge case.
stripping original strings, `trim_offsets=False` both seem like reasonable options for users that might be encumbered by this.
We also have to take into account the risk of breaking other things when touching something as core as `NormalizedString`.

The biggest culprit when sending `pretokenized` strings is actually fixed.

Happy to hear some thoughts.
