### ISSUE TITLE
Export Trainer::train API into Python bindings

### ISSUE THREAD

**Issue by vilunov** [huggingface/tokenizers#89]
HI!
Currently [Trainer::train](https://docs.rs/tokenizers/0.6.0/tokenizers/tokenizer/trait.Trainer.html#tymethod.train) method of the built trainer is missing from the Python object returned by [BpeTrainer.new](https://github.com/huggingface/tokenizers/blob/ef21c9a7b0ac374a3bfe7f982abe10157912797a/bindings/python/src/trainers.rs#L7-L10). This is important to have if you want to construct models using token counters from Python.

**Comment by tRosenflanz** [comment]
Any news on this? Training from token counts would be very nice.
For instance, in my use case original data is processed in Spark so obtaining word counts is easy while dumping all of the strings into files would be very slow

**Comment by n1t0** [comment]
I'm really not sure giving the ability to feed word counts is a good idea because the `PreTokenizer` is in charge of doing the pre-tokenization and it would introduce potential discrepancies between training and tokenization. Also, this trainer API is subject to change in the future, and may not be compatible with word counts anymore.

What about being able to stream raw strings instead?

**Comment by tRosenflanz** [comment]
That would be useful too albeit more cumbersome. 

Would you mind expanding on the discrepancies you foresee? Currently, I use a custom loop using tfds subwordtextencoder methods that takes in word counts -> iterates over words, tokenizes them -> for each token increments token counter by the source word count -> builds encoder vocab using token counter.
