### ISSUE TITLE
Tokenizers for Node 16?

### ISSUE THREAD

**Issue by etiennelunetta** [huggingface/tokenizers#911]
Currently using node 16 and I'm not able to use the latest npm release. Is it possible to rebuild for v15+?

**Comment by Narsil** [comment]
Hi, this will require an update of `neon` which is the library we use for node bindings.

Unfortunately, `neon` introduces a lot of breaking changes (for the better it seems) since we made the bindings and so this is going to be a relatively big endeavor to rewrite.

Any help on that department will be appreciated.

Until then, we unfortunately can't build for Node 16.

**Comment by Narsil** [comment]
When we redo the bindings, we can also think about manylinux support: https://github.com/huggingface/tokenizers/issues/972

**Comment by markhughes** [comment]
But I can confirm it won't build for Node v16 in the current state. 

There are a lot of breaking changes: https://github.com/neon-bindings/neon/blob/0.10.0/MIGRATION_GUIDE_0.10.md

Would it be helpful if I wrote a script to highlight the changes and we can all start tackling them? 💪

**Comment by Narsil** [comment]
Hi @markhughes 

I think given the age of neon, it might even be more practical to start over from scratch.
Maybe take the current version as a starting point but that's all.

Help on that front would be highly appreciated ! 

Don't hesitate to share work early if you want to tackle it !

**Comment by rattrayalex** [comment]
For others blocked on this, [this analysis](https://github.com/transitive-bullshit/compare-tokenizers) finds that [`@dqbd/tiktoken`](https://www.npmjs.com/package/@dqbd/tiktoken) – a wasm port of OpenAI's official Rust tiktoken – works well.

**Comment by MatousAc** [comment]
I'm also stuck on this. I'm using SvelteKit and thus can't use Tokenizers.
I'm still a beginner, so I would appreciate help:
I've got a [`tokenizer.json`](https://raw.githubusercontent.com/MatousAc/aqg/main/pbe/src/assets/OptimumONNX/tokenizer.json) and am about to start making my own function to convert the words into numbers (which is what it looks like the tokenizer is doing to me when I run it in python). Is there a way to use [`@dqbd/tiktoken`](https://www.npmjs.com/package/@dqbd/tiktoken) instead of Tokenizers but still use my [`tokenizer.json`](https://raw.githubusercontent.com/MatousAc/aqg/main/pbe/src/assets/OptimumONNX/tokenizer.json)? My model is based on T5, so maybe I don't even need to do this?
