### ISSUE TITLE
Adding post-process function to the ByT5 tokenizer

### ISSUE THREAD

**Issue by vitalyshalumov** [huggingface/tokenizers#912]
Hi,
I'm trying to add a post-processing function to the ByT5 tokenizer
However, this tokenizer does not have this method so I cannot change the post-processing (it only adds the eos  token).
How can I add this method?
Adding post processor according to some template does not work because the tokenizer does not have the post_process method.
Simply put for the following line I wish to get a roberta-like post processing:

print(tokenizer.decode(tokenizer.encode('dssd')))

The desired output:
<s>dssd</s>

The output now:
dssd</s>

**Comment by Narsil** [comment]
Hi @vitalyshalumov ,

ByT5, is a pure bytes tokenizer. Meaning it does not use either `BPE` nor `Unigram` (the main 2 algo provided by this library).
The only implementation of this tokenizer is in `transformers`. There was some discussion wether we should port it to Rust, but it's not necessarily viable/interesting so it's not going to happen in the midterm future at least.

So there's no `post-processing` involved like you imagine with this lib. Everything is defined here: https://github.com/huggingface/transformers/blob/master/src/transformers/models/byt5/tokenization_byt5.py#L28

Feel free to hack away this tokenizer to your needs. `_add_eos_if_not_present` seems like a good target for you for instance.

I am closing this since this issue has nothing to do with `tokenizers`. Feel free to reopen one in `transformers` and ping me for visibility (I also look at ByT5).

**Comment by vitalyshalumov** [comment]
Thank you!
