### ISSUE TITLE
Addition of CONTRIBUTING.md to Repository

### ISSUE THREAD

**Issue by beneyal** [huggingface/tokenizers#926]
Hello, dear maintainers! 👋 

I was wondering whether a `CONTRIBUTING.md` file is planned for this repository. 🤗Tokenizers is a wonderful project, and I'd love to try and contribute to it, even though you might say I'm rusty at Rust 😉 

🤗Transformers and 🤗Datasets have such a file, which is why I'm wondering about this project.

And while we're at it, in case contributions are welcome, how would you recommend preparing? Things like required knowledge, project best practices, etc.

Thanks,
Ben

**Comment by Narsil** [comment]
Hi @beneyal ,

There's not at the moment anything planned, but contributions for one are very welcome ! :)
The main thing would be adding and adhering to the CODE_OF_CONDUCT of those projects which would be the same here.

In terms of technical contributions, there are no real constraints or recommendations.
If you are *shiny* in rust (*rusty* is experienced and old in rust :) ) , I would suggest sticking to the pure rust code, and trying anything you want to try. Adding more doc annotations, anything that could be reworked into better code things like that.

Some PRs are simple code changes and are still welcome.
https://github.com/huggingface/tokenizers/pull/923

Currently there are no triage, but looking at issues could give you ideas to get started.

That being said before doing work intensive PRs, don't hesitate to create issues in order to get feedback early on your proposed changes so you don't spend a lot of time on an approach that cannot/will not get merged for reasons that can be anticipated (like this is something outside of the scope of the library, the thing already exists in some form you are not aware of, etc...)

You can go look at resoled PRs too to get a sense of how the process works.

Thanks you very much for your interest, have a great day !

**Comment by msaroufim** [comment]
Hi @Narsil it may be nice to have a few `good-first-issue` populated, for one can think of 4 people I work with every day that know a lot about ML and ML systems and would look forward to having some small but meaningful contribution to a Rust library. To relate this back to `transformers` a meaningful contribution would be something like a new transformer, new layer typem so what users are expected to contribute is very clear.

**Comment by Narsil** [comment]
Hi @msaroufim ,

I went ahead and created a milestone to regroup various work that we need to get done at some point in the near future (as it will be required when the BigScience big model will be released):

https://github.com/huggingface/tokenizers/milestone/1

Only one is marked as a first issue, since the others do require some knowledge of the library, and carefulness to not break backward compatibility.

If either of you 4 want to take any of those on, you're more than welcome, and don't hesitate to ask questions early.

Additionally I added some long standing work that we would like to tackle at some point:

https://github.com/huggingface/tokenizers/milestone/2

But those are intrinsically harder (at least at the moment, M1 will get easier once GH actions support them)

Note: The number 0.12, 0.13 are arbitrary at the moment, but the issues inside to represent big enough changes to warrant a change a new minor version.

**Comment by eduardo-exists** [comment]
Hello! 

Sorry to necro this issue, but I'm curious about contributing as well! This post is from last year and I'm assuming may be out of date. Are there any good first issues at the moment I might be able to help with? :)

**Comment by Narsil** [comment]
Good first issues not really.

The biggest long standing request was rewriting the node bindings using latest neon to get support from latest node versions.

I have zero idea how hard it is, but most likely not trivial.

Current PRs being worked on: 
- https://github.com/huggingface/tokenizers/pull/1217
- https://github.com/huggingface/tokenizers/pull/1228

Those are probably simpler and you could maybe get an idea of what is being worked on.
