### ISSUE TITLE
Out of memory when training on very large corpus

### ISSUE THREAD

**Issue by marcmk6** [huggingface/tokenizers#994]
Hi,

I'm trying to train a BPE tokenizer on a very large corpus (dozens of GB) with ~180GB RAM. But this cannot be done due to OOM.
While trying to find solutions, I came across [this issue](https://github.com/huggingface/tokenizers/issues/422) created in 2020, which is still open. So I'm wondering if there's something new that I can try.

Thanks

**Comment by Narsil** [comment]
Hi @marcmk6 ,

Are you using a pretokenizer ?

As mentionned in the original issue, this has a huge impact on the RAM usage (and overall performance of the resulting tokenizer).

Are you able to share a subset of the data (let's say 100Mo) that take up (2Go RAM+) (keeping up a similar ratio) ? for instance?

There's a real issue on BPE when there's no space splitting as it will create huge chains, and the "pair" representation the algorithm has to keep to create the merges can grow extremely large. Without looking at a reproducible example it's hard to be 100% sure that's the issue you are seeing, but it's probably very likely. On non space separated languages you should be able to use other pretokenizers.

**Comment by marcmk6** [comment]
Hi Nicolas,

Thanks for you reply.
No, I'm not using a pre-tokenizer. I believe there's no pre-tokenizer for my case since I'm dealing with protein segments (amino acid sequences) and there's no way to "pre-tokenize" as for human languages. 
Some examples are [here](https://gist.github.com/marcmk6/63a717cb307cd6eb7dd3d271e0be54b8).

I think your guess is right. Although a single sequence is not very long, I got tons of them.

**Comment by Narsil** [comment]
I see ! 

Then I may suggest using `Unigram` then which might be more appropriate.

Try both with `sentencepiece` and `tokenizers`. `tokenizers` does implement the `Unigram` training algorithm and it should match the sentencepiece algorithm, however we never got to 100% compliant implem just because the 2 libs have very different structure. This algorithm uses a `trainers.UnigramTrainer(max_piece_length=16)` for instance, which can limit the size of the resulting tokens, which should yield a good result.

No matter where you train your tokenizer, you can always port it to `tokenizers` later if you want.

**Comment by Narsil** [comment]
And since you are using a huge amount of data, so probably a big machine, you can try

https://github.com/huggingface/tokenizers/pull/921

Which contains the parallelization code which should boost quite a bit the speed of training there !

**Comment by marcmk6** [comment]
Thanks for your advices!
It seems I need to use `sentencepiece` to better fit the training into my memory.
